// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package postgres

import (
	"context"
	"time"
)

const refreshTokenCreate = `-- name: RefreshTokenCreate :one
INSERT INTO refresh_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3) RETURNING id
`

type RefreshTokenCreateParams struct {
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) RefreshTokenCreate(ctx context.Context, arg RefreshTokenCreateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, refreshTokenCreate, arg.UserID, arg.Token, arg.ExpiresAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const refreshTokenDeleteByToken = `-- name: RefreshTokenDeleteByToken :one
DELETE FROM refresh_tokens WHERE token = $1 RETURNING id, user_id, token, expires_at, created_at
`

func (q *Queries) RefreshTokenDeleteByToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, refreshTokenDeleteByToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
