// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_lease.sql

package postgres

import (
	"context"
)

const nodeLeaseClaim = `-- name: NodeLeaseClaim :execrows
INSERT INTO snowflake_node_leases (node_id, holder, acquired_at, expires_at)
VALUES ($1, $2, now(), now() + make_interval(secs => $3::int))
ON CONFLICT (node_id) DO UPDATE
SET holder = EXCLUDED.holder, acquired_at = now(), expires_at = EXCLUDED.expires_at
WHERE snowflake_node_leases.expires_at < now()
`

type NodeLeaseClaimParams struct {
	NodeID     int64  `json:"node_id"`
	Holder     string `json:"holder"`
	TtlSeconds int64  `json:"ttl_seconds"`
}

func (q *Queries) NodeLeaseClaim(ctx context.Context, arg NodeLeaseClaimParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, nodeLeaseClaim, arg.NodeID, arg.Holder, arg.TtlSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const nodeLeaseRelease = `-- name: NodeLeaseRelease :exec
DELETE FROM snowflake_node_leases
WHERE node_id = $1 AND holder = $2
`

type NodeLeaseReleaseParams struct {
	NodeID int64  `json:"node_id"`
	Holder string `json:"holder"`
}

func (q *Queries) NodeLeaseRelease(ctx context.Context, arg NodeLeaseReleaseParams) error {
	_, err := q.db.ExecContext(ctx, nodeLeaseRelease, arg.NodeID, arg.Holder)
	return err
}

const nodeLeaseRenew = `-- name: NodeLeaseRenew :execrows
UPDATE snowflake_node_leases
SET expires_at = now() + make_interval(secs => $1::int)
WHERE node_id = $2 AND holder = $3
`

type NodeLeaseRenewParams struct {
	TtlSeconds int64  `json:"ttl_seconds"`
	NodeID     int64  `json:"node_id"`
	Holder     string `json:"holder"`
}

func (q *Queries) NodeLeaseRenew(ctx context.Context, arg NodeLeaseRenewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, nodeLeaseRenew, arg.TtlSeconds, arg.NodeID, arg.Holder)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
