// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package postgres

import (
	"context"
	"database/sql"
)

const userCreate = `-- name: UserCreate :one
INSERT INTO users (id, name, email, password, photo_url, is_admin)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type UserCreateParams struct {
	ID       int64          `json:"id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	PhotoUrl sql.NullString `json:"photo_url"`
	IsAdmin  bool           `json:"is_admin"`
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, userCreate,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.PhotoUrl,
		arg.IsAdmin,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const userDeleteByID = `-- name: UserDeleteByID :exec
UPDATE users SET deleted = true, deleted_at = now() WHERE id = $1 AND deleted = false
`

func (q *Queries) UserDeleteByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, userDeleteByID, id)
	return err
}

const userGetByEmail = `-- name: UserGetByEmail :one
SELECT id, name, email, password, photo_url, is_super_admin, is_admin, notify_email, created_at, updated_at, deleted, deleted_at FROM users WHERE email = $1 AND deleted = false LIMIT 1
`

func (q *Queries) UserGetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userGetByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.PhotoUrl,
		&i.IsSuperAdmin,
		&i.IsAdmin,
		&i.NotifyEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
		&i.DeletedAt,
	)
	return i, err
}

const userGetById = `-- name: UserGetById :one
SELECT id, name, email, password, photo_url, is_super_admin, is_admin, notify_email, created_at, updated_at, deleted, deleted_at FROM users WHERE id = $1 AND deleted = false LIMIT 1
`

func (q *Queries) UserGetById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, userGetById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.PhotoUrl,
		&i.IsSuperAdmin,
		&i.IsAdmin,
		&i.NotifyEmail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
		&i.DeletedAt,
	)
	return i, err
}

const userList = `-- name: UserList :many
SELECT id, name, email, password, photo_url, is_super_admin, is_admin, notify_email, created_at, updated_at, deleted, deleted_at FROM users WHERE deleted = false ORDER BY name, id
`

func (q *Queries) UserList(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, userList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.PhotoUrl,
			&i.IsSuperAdmin,
			&i.IsAdmin,
			&i.NotifyEmail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userUpdateAdminFlags = `-- name: UserUpdateAdminFlags :exec
UPDATE users SET is_admin = $1, is_super_admin = $2 WHERE id = $3 AND deleted = false
`

type UserUpdateAdminFlagsParams struct {
	IsAdmin      bool  `json:"is_admin"`
	IsSuperAdmin bool  `json:"is_super_admin"`
	ID           int64 `json:"id"`
}

func (q *Queries) UserUpdateAdminFlags(ctx context.Context, arg UserUpdateAdminFlagsParams) error {
	_, err := q.db.ExecContext(ctx, userUpdateAdminFlags, arg.IsAdmin, arg.IsSuperAdmin, arg.ID)
	return err
}

const userUpdateEmail = `-- name: UserUpdateEmail :exec
UPDATE users SET email = $1 WHERE id = $2 AND deleted = false
`

type UserUpdateEmailParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) UserUpdateEmail(ctx context.Context, arg UserUpdateEmailParams) error {
	_, err := q.db.ExecContext(ctx, userUpdateEmail, arg.Email, arg.ID)
	return err
}

const userUpdatePassword = `-- name: UserUpdatePassword :exec
UPDATE users SET password = $1
WHERE id = $2 AND deleted = false
`

type UserUpdatePasswordParams struct {
	Password string `json:"password"`
	ID       int64  `json:"id"`
}

func (q *Queries) UserUpdatePassword(ctx context.Context, arg UserUpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, userUpdatePassword, arg.Password, arg.ID)
	return err
}

const userUpdateProfile = `-- name: UserUpdateProfile :exec
UPDATE users SET name = $1, photo_url = $2,
    notify_email = COALESCE($3::boolean, notify_email)
WHERE id = $4 AND deleted = false
`

type UserUpdateProfileParams struct {
	Name        string         `json:"name"`
	PhotoUrl    sql.NullString `json:"photo_url"`
	NotifyEmail sql.NullBool   `json:"notify_email"`
	ID          int64          `json:"id"`
}

func (q *Queries) UserUpdateProfile(ctx context.Context, arg UserUpdateProfileParams) error {
	_, err := q.db.ExecContext(ctx, userUpdateProfile,
		arg.Name,
		arg.PhotoUrl,
		arg.NotifyEmail,
		arg.ID,
	)
	return err
}
