sonar.projectKey=nipalab_nipa
sonar.organization=nipalab

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=nipa
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

sonar.language=go

sonar.exclusions=**/*_test.go,internal/repository/sqlc/**,internal/http/swagger/**,db/**,cmd/migrate/main.go,cmd/nipad/main.go,cmd/nipad/registry.go,cmd/nipa/main.go,cmd/nipa/registry.go,web/src/**,web/vite.config.ts

sonar.go.coverage.reportPaths=coverage.out

sonar.go.tests.reportPaths=report.json

sonar.sources=.

sonar.tests=.

sonar.test.inclusions=**/*_test.go

# sonar.cpd.exclusions=internal/adapter/repository/**