// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"database/sql"
	"time"
)

type Organization struct {
	ID              int64         `json:"id"`
	Slug            string        `json:"slug"`
	Name            string        `json:"name"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
	Deleted         bool          `json:"deleted"`
	DeletedAt       sql.NullTime  `json:"deleted_at"`
	CreatedByUserID sql.NullInt64 `json:"created_by_user_id"`
}

type Project struct {
	ID          int64        `json:"id"`
	OrgID       int64        `json:"org_id"`
	Slug        string       `json:"slug"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Deleted     bool         `json:"deleted"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}
