// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_lock.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"
)

const fileLockCreate = `-- name: FileLockCreate :one
INSERT INTO file_locks (id, project_id, branch_id, path, held_by, merge_request_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, project_id, branch_id, path, held_by, merge_request_id, acquired_at
`

type FileLockCreateParams struct {
	ID             int64         `json:"id"`
	ProjectID      int64         `json:"project_id"`
	BranchID       sql.NullInt64 `json:"branch_id"`
	Path           string        `json:"path"`
	HeldBy         int64         `json:"held_by"`
	MergeRequestID sql.NullInt64 `json:"merge_request_id"`
}

func (q *Queries) FileLockCreate(ctx context.Context, arg FileLockCreateParams) (FileLock, error) {
	row := q.db.QueryRowContext(ctx, fileLockCreate,
		arg.ID,
		arg.ProjectID,
		arg.BranchID,
		arg.Path,
		arg.HeldBy,
		arg.MergeRequestID,
	)
	var i FileLock
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BranchID,
		&i.Path,
		&i.HeldBy,
		&i.MergeRequestID,
		&i.AcquiredAt,
	)
	return i, err
}

const fileLockDelete = `-- name: FileLockDelete :execrows
DELETE FROM file_locks WHERE id = ?
`

func (q *Queries) FileLockDelete(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, fileLockDelete, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const fileLockDeleteByBranch = `-- name: FileLockDeleteByBranch :execrows
DELETE FROM file_locks WHERE project_id = ? AND branch_id = ?
`

type FileLockDeleteByBranchParams struct {
	ProjectID int64         `json:"project_id"`
	BranchID  sql.NullInt64 `json:"branch_id"`
}

func (q *Queries) FileLockDeleteByBranch(ctx context.Context, arg FileLockDeleteByBranchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, fileLockDeleteByBranch, arg.ProjectID, arg.BranchID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const fileLockDeleteByMergeRequest = `-- name: FileLockDeleteByMergeRequest :execrows
DELETE FROM file_locks WHERE project_id = ? AND merge_request_id = ?
`

type FileLockDeleteByMergeRequestParams struct {
	ProjectID      int64         `json:"project_id"`
	MergeRequestID sql.NullInt64 `json:"merge_request_id"`
}

func (q *Queries) FileLockDeleteByMergeRequest(ctx context.Context, arg FileLockDeleteByMergeRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, fileLockDeleteByMergeRequest, arg.ProjectID, arg.MergeRequestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const fileLockGet = `-- name: FileLockGet :one
SELECT id, project_id, branch_id, path, held_by, merge_request_id, acquired_at FROM file_locks
WHERE project_id = ? AND path = ? AND branch_id IS ?3
`

type FileLockGetParams struct {
	ProjectID int64         `json:"project_id"`
	Path      string        `json:"path"`
	BranchID  sql.NullInt64 `json:"branch_id"`
}

func (q *Queries) FileLockGet(ctx context.Context, arg FileLockGetParams) (FileLock, error) {
	row := q.db.QueryRowContext(ctx, fileLockGet, arg.ProjectID, arg.Path, arg.BranchID)
	var i FileLock
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BranchID,
		&i.Path,
		&i.HeldBy,
		&i.MergeRequestID,
		&i.AcquiredAt,
	)
	return i, err
}

const fileLockListProject = `-- name: FileLockListProject :many
SELECT
    fl.id, fl.project_id, fl.branch_id, fl.path, fl.held_by, fl.merge_request_id, fl.acquired_at,
    u.name AS held_by_name,
    b.name AS branch_name,
    mr.number AS merge_request_number
FROM file_locks fl
JOIN users u ON u.id = fl.held_by
LEFT JOIN branches b ON b.id = fl.branch_id
LEFT JOIN merge_requests mr ON mr.id = fl.merge_request_id
WHERE fl.project_id = ?
ORDER BY fl.path
`

type FileLockListProjectRow struct {
	ID                 int64          `json:"id"`
	ProjectID          int64          `json:"project_id"`
	BranchID           sql.NullInt64  `json:"branch_id"`
	Path               string         `json:"path"`
	HeldBy             int64          `json:"held_by"`
	MergeRequestID     sql.NullInt64  `json:"merge_request_id"`
	AcquiredAt         time.Time      `json:"acquired_at"`
	HeldByName         string         `json:"held_by_name"`
	BranchName         sql.NullString `json:"branch_name"`
	MergeRequestNumber sql.NullInt64  `json:"merge_request_number"`
}

func (q *Queries) FileLockListProject(ctx context.Context, projectID int64) ([]FileLockListProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, fileLockListProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileLockListProjectRow
	for rows.Next() {
		var i FileLockListProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BranchID,
			&i.Path,
			&i.HeldBy,
			&i.MergeRequestID,
			&i.AcquiredAt,
			&i.HeldByName,
			&i.BranchName,
			&i.MergeRequestNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
