// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group.sql

package sqlite

import (
	"context"
	"database/sql"
)

const groupCreate = `-- name: GroupCreate :one
INSERT INTO groups (id, org_id, name, description)
VALUES (?, ?, ?, ?)
RETURNING id, org_id, name, description, created_at, updated_at, deleted, deleted_at
`

type GroupCreateParams struct {
	ID          int64          `json:"id"`
	OrgID       int64          `json:"org_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) GroupCreate(ctx context.Context, arg GroupCreateParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, groupCreate,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Description,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
		&i.DeletedAt,
	)
	return i, err
}

const groupListByOrg = `-- name: GroupListByOrg :many
SELECT id, org_id, name, description, created_at, updated_at, deleted, deleted_at FROM groups WHERE org_id = ? AND deleted = false ORDER BY name
`

func (q *Queries) GroupListByOrg(ctx context.Context, orgID int64) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, groupListByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupListByUser = `-- name: GroupListByUser :many
SELECT g.id, g.org_id, g.name, g.description, g.created_at, g.updated_at, g.deleted, g.deleted_at FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = ? AND g.deleted = false
ORDER BY g.name
`

func (q *Queries) GroupListByUser(ctx context.Context, userID int64) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, groupListByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupMemberAdd = `-- name: GroupMemberAdd :exec
INSERT OR IGNORE INTO group_members (group_id, user_id) VALUES (?, ?)
`

type GroupMemberAddParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) GroupMemberAdd(ctx context.Context, arg GroupMemberAddParams) error {
	_, err := q.db.ExecContext(ctx, groupMemberAdd, arg.GroupID, arg.UserID)
	return err
}

const groupMemberRemove = `-- name: GroupMemberRemove :exec
DELETE FROM group_members WHERE group_id = ? AND user_id = ?
`

type GroupMemberRemoveParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) GroupMemberRemove(ctx context.Context, arg GroupMemberRemoveParams) error {
	_, err := q.db.ExecContext(ctx, groupMemberRemove, arg.GroupID, arg.UserID)
	return err
}
