// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merge_request_review.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"
)

const mergeRequestCommentCreate = `-- name: MergeRequestCommentCreate :one
INSERT INTO merge_request_comments (id, thread_id, user_id, body)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, thread_id, user_id, body, system, created_at, updated_at
`

type MergeRequestCommentCreateParams struct {
	ID       int64  `json:"id"`
	ThreadID int64  `json:"thread_id"`
	UserID   int64  `json:"user_id"`
	Body     string `json:"body"`
}

func (q *Queries) MergeRequestCommentCreate(ctx context.Context, arg MergeRequestCommentCreateParams) (MergeRequestComment, error) {
	row := q.db.QueryRowContext(ctx, mergeRequestCommentCreate,
		arg.ID,
		arg.ThreadID,
		arg.UserID,
		arg.Body,
	)
	var i MergeRequestComment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.UserID,
		&i.Body,
		&i.System,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mergeRequestCommentDelete = `-- name: MergeRequestCommentDelete :execrows
DELETE FROM merge_request_comments
WHERE thread_id = ?1 AND id = ?2
`

type MergeRequestCommentDeleteParams struct {
	ThreadID int64 `json:"thread_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) MergeRequestCommentDelete(ctx context.Context, arg MergeRequestCommentDeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, mergeRequestCommentDelete, arg.ThreadID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const mergeRequestCommentGet = `-- name: MergeRequestCommentGet :one
SELECT id, thread_id, user_id, body, system, created_at, updated_at FROM merge_request_comments
WHERE thread_id = ?1 AND id = ?2
`

type MergeRequestCommentGetParams struct {
	ThreadID int64 `json:"thread_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) MergeRequestCommentGet(ctx context.Context, arg MergeRequestCommentGetParams) (MergeRequestComment, error) {
	row := q.db.QueryRowContext(ctx, mergeRequestCommentGet, arg.ThreadID, arg.ID)
	var i MergeRequestComment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.UserID,
		&i.Body,
		&i.System,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mergeRequestCommentListByThread = `-- name: MergeRequestCommentListByThread :many
SELECT
    c.id, c.thread_id, c.user_id, c.body, c.system, c.created_at, c.updated_at,
    u.name AS user_name,
    u.photo_url AS user_photo_url
FROM merge_request_comments c
JOIN users u ON u.id = c.user_id
WHERE c.thread_id IN (
    SELECT id FROM merge_request_threads WHERE merge_request_id = ?1
)
ORDER BY c.thread_id, c.id
`

type MergeRequestCommentListByThreadRow struct {
	ID           int64          `json:"id"`
	ThreadID     int64          `json:"thread_id"`
	UserID       int64          `json:"user_id"`
	Body         string         `json:"body"`
	System       bool           `json:"system"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	UserName     string         `json:"user_name"`
	UserPhotoUrl sql.NullString `json:"user_photo_url"`
}

func (q *Queries) MergeRequestCommentListByThread(ctx context.Context, mergeRequestID int64) ([]MergeRequestCommentListByThreadRow, error) {
	rows, err := q.db.QueryContext(ctx, mergeRequestCommentListByThread, mergeRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MergeRequestCommentListByThreadRow
	for rows.Next() {
		var i MergeRequestCommentListByThreadRow
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.UserID,
			&i.Body,
			&i.System,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserPhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeRequestCommentUpdate = `-- name: MergeRequestCommentUpdate :one
UPDATE merge_request_comments
SET body = ?1, updated_at = CURRENT_TIMESTAMP
WHERE thread_id = ?2 AND id = ?3
RETURNING id, thread_id, user_id, body, system, created_at, updated_at
`

type MergeRequestCommentUpdateParams struct {
	Body     string `json:"body"`
	ThreadID int64  `json:"thread_id"`
	ID       int64  `json:"id"`
}

func (q *Queries) MergeRequestCommentUpdate(ctx context.Context, arg MergeRequestCommentUpdateParams) (MergeRequestComment, error) {
	row := q.db.QueryRowContext(ctx, mergeRequestCommentUpdate, arg.Body, arg.ThreadID, arg.ID)
	var i MergeRequestComment
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.UserID,
		&i.Body,
		&i.System,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mergeRequestEventCreate = `-- name: MergeRequestEventCreate :one
INSERT INTO merge_request_events (
    id, merge_request_id, actor_id, subject_user_id, kind, body, commit_id, commit_hash
)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
RETURNING id, merge_request_id, actor_id, subject_user_id, kind, body, commit_id, commit_hash, created_at
`

type MergeRequestEventCreateParams struct {
	ID             int64          `json:"id"`
	MergeRequestID int64          `json:"merge_request_id"`
	ActorID        int64          `json:"actor_id"`
	SubjectUserID  sql.NullInt64  `json:"subject_user_id"`
	Kind           string         `json:"kind"`
	Body           string         `json:"body"`
	CommitID       sql.NullInt64  `json:"commit_id"`
	CommitHash     sql.NullString `json:"commit_hash"`
}

func (q *Queries) MergeRequestEventCreate(ctx context.Context, arg MergeRequestEventCreateParams) (MergeRequestEvent, error) {
	row := q.db.QueryRowContext(ctx, mergeRequestEventCreate,
		arg.ID,
		arg.MergeRequestID,
		arg.ActorID,
		arg.SubjectUserID,
		arg.Kind,
		arg.Body,
		arg.CommitID,
		arg.CommitHash,
	)
	var i MergeRequestEvent
	err := row.Scan(
		&i.ID,
		&i.MergeRequestID,
		&i.ActorID,
		&i.SubjectUserID,
		&i.Kind,
		&i.Body,
		&i.CommitID,
		&i.CommitHash,
		&i.CreatedAt,
	)
	return i, err
}

const mergeRequestEventList = `-- name: MergeRequestEventList :many
SELECT
    e.id, e.merge_request_id, e.actor_id, e.subject_user_id, e.kind, e.body, e.commit_id, e.commit_hash, e.created_at,
    u.name AS actor_name,
    u.photo_url AS actor_photo_url,
    s.name AS subject_name,
    s.photo_url AS subject_photo_url
FROM merge_request_events e
JOIN users u ON u.id = e.actor_id
LEFT JOIN users s ON s.id = e.subject_user_id
WHERE e.merge_request_id = ?
ORDER BY e.id
`

type MergeRequestEventListRow struct {
	ID              int64          `json:"id"`
	MergeRequestID  int64          `json:"merge_request_id"`
	ActorID         int64          `json:"actor_id"`
	SubjectUserID   sql.NullInt64  `json:"subject_user_id"`
	Kind            string         `json:"kind"`
	Body            string         `json:"body"`
	CommitID        sql.NullInt64  `json:"commit_id"`
	CommitHash      sql.NullString `json:"commit_hash"`
	CreatedAt       time.Time      `json:"created_at"`
	ActorName       string         `json:"actor_name"`
	ActorPhotoUrl   sql.NullString `json:"actor_photo_url"`
	SubjectName     sql.NullString `json:"subject_name"`
	SubjectPhotoUrl sql.NullString `json:"subject_photo_url"`
}

func (q *Queries) MergeRequestEventList(ctx context.Context, mergeRequestID int64) ([]MergeRequestEventListRow, error) {
	rows, err := q.db.QueryContext(ctx, mergeRequestEventList, mergeRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MergeRequestEventListRow
	for rows.Next() {
		var i MergeRequestEventListRow
		if err := rows.Scan(
			&i.ID,
			&i.MergeRequestID,
			&i.ActorID,
			&i.SubjectUserID,
			&i.Kind,
			&i.Body,
			&i.CommitID,
			&i.CommitHash,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorPhotoUrl,
			&i.SubjectName,
			&i.SubjectPhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeRequestListOpenBySourceBranch = `-- name: MergeRequestListOpenBySourceBranch :many
SELECT id, number, project_id, source_branch_id, target_branch_id, source_branch_name, target_branch_name, title, description, status, merge_commit_id, merge_base_commit_id, created_by, created_at, updated_at FROM merge_requests
WHERE project_id = ?1
  AND status = ?2
  AND source_branch_id = ?3
`

type MergeRequestListOpenBySourceBranchParams struct {
	ProjectID int64  `json:"project_id"`
	Status    string `json:"status"`
	BranchID  int64  `json:"branch_id"`
}

func (q *Queries) MergeRequestListOpenBySourceBranch(ctx context.Context, arg MergeRequestListOpenBySourceBranchParams) ([]MergeRequest, error) {
	rows, err := q.db.QueryContext(ctx, mergeRequestListOpenBySourceBranch, arg.ProjectID, arg.Status, arg.BranchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MergeRequest
	for rows.Next() {
		var i MergeRequest
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.ProjectID,
			&i.SourceBranchID,
			&i.TargetBranchID,
			&i.SourceBranchName,
			&i.TargetBranchName,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.MergeCommitID,
			&i.MergeBaseCommitID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeRequestReviewDelete = `-- name: MergeRequestReviewDelete :execrows
DELETE FROM merge_request_reviews
WHERE merge_request_id = ?1 AND id = ?2
`

type MergeRequestReviewDeleteParams struct {
	MergeRequestID int64 `json:"merge_request_id"`
	ID             int64 `json:"id"`
}

func (q *Queries) MergeRequestReviewDelete(ctx context.Context, arg MergeRequestReviewDeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, mergeRequestReviewDelete, arg.MergeRequestID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const mergeRequestReviewDismiss = `-- name: MergeRequestReviewDismiss :exec
UPDATE merge_request_reviews
SET dismissed_at = ?1,
    dismissed_by = ?2,
    dismissed_reason = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE merge_request_id = ?4 AND id = ?5
`

type MergeRequestReviewDismissParams struct {
	DismissedAt     sql.NullTime   `json:"dismissed_at"`
	DismissedBy     sql.NullInt64  `json:"dismissed_by"`
	DismissedReason sql.NullString `json:"dismissed_reason"`
	MergeRequestID  int64          `json:"merge_request_id"`
	ID              int64          `json:"id"`
}

func (q *Queries) MergeRequestReviewDismiss(ctx context.Context, arg MergeRequestReviewDismissParams) error {
	_, err := q.db.ExecContext(ctx, mergeRequestReviewDismiss,
		arg.DismissedAt,
		arg.DismissedBy,
		arg.DismissedReason,
		arg.MergeRequestID,
		arg.ID,
	)
	return err
}

const mergeRequestReviewDismissStale = `-- name: MergeRequestReviewDismissStale :exec
UPDATE merge_request_reviews
SET dismissed_at = ?1,
    dismissed_by = ?2,
    dismissed_reason = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE merge_request_id = ?4
  AND dismissed_at IS NULL
  AND head_commit_id != ?5
  AND state != 'commented'
`

type MergeRequestReviewDismissStaleParams struct {
	DismissedAt     sql.NullTime   `json:"dismissed_at"`
	DismissedBy     sql.NullInt64  `json:"dismissed_by"`
	DismissedReason sql.NullString `json:"dismissed_reason"`
	MergeRequestID  int64          `json:"merge_request_id"`
	HeadCommitID    int64          `json:"head_commit_id"`
}

func (q *Queries) MergeRequestReviewDismissStale(ctx context.Context, arg MergeRequestReviewDismissStaleParams) error {
	_, err := q.db.ExecContext(ctx, mergeRequestReviewDismissStale,
		arg.DismissedAt,
		arg.DismissedBy,
		arg.DismissedReason,
		arg.MergeRequestID,
		arg.HeadCommitID,
	)
	return err
}

const mergeRequestReviewGet = `-- name: MergeRequestReviewGet :one
SELECT id, merge_request_id, reviewer_id, state, body, head_commit_id, created_at, updated_at, dismissed_at, dismissed_by, dismissed_reason FROM merge_request_reviews
WHERE merge_request_id = ?1 AND id = ?2
`

type MergeRequestReviewGetParams struct {
	MergeRequestID int64 `json:"merge_request_id"`
	ID             int64 `json:"id"`
}

func (q *Queries) MergeRequestReviewGet(ctx context.Context, arg MergeRequestReviewGetParams) (MergeRequestReview, error) {
	row := q.db.QueryRowContext(ctx, mergeRequestReviewGet, arg.MergeRequestID, arg.ID)
	var i MergeRequestReview
	err := row.Scan(
		&i.ID,
		&i.MergeRequestID,
		&i.ReviewerID,
		&i.State,
		&i.Body,
		&i.HeadCommitID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DismissedAt,
		&i.DismissedBy,
		&i.DismissedReason,
	)
	return i, err
}

const mergeRequestReviewList = `-- name: MergeRequestReviewList :many
SELECT
    r.id, r.merge_request_id, r.reviewer_id, r.state, r.body, r.head_commit_id, r.created_at, r.updated_at, r.dismissed_at, r.dismissed_by, r.dismissed_reason,
    u.name AS reviewer_name,
    u.photo_url AS reviewer_photo_url,
    d.name AS dismissed_by_name
FROM merge_request_reviews r
JOIN users u ON u.id = r.reviewer_id
LEFT JOIN users d ON d.id = r.dismissed_by
WHERE r.merge_request_id = ?
ORDER BY r.id
`

type MergeRequestReviewListRow struct {
	ID               int64          `json:"id"`
	MergeRequestID   int64          `json:"merge_request_id"`
	ReviewerID       int64          `json:"reviewer_id"`
	State            string         `json:"state"`
	Body             string         `json:"body"`
	HeadCommitID     int64          `json:"head_commit_id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DismissedAt      sql.NullTime   `json:"dismissed_at"`
	DismissedBy      sql.NullInt64  `json:"dismissed_by"`
	DismissedReason  sql.NullString `json:"dismissed_reason"`
	ReviewerName     string         `json:"reviewer_name"`
	ReviewerPhotoUrl sql.NullString `json:"reviewer_photo_url"`
	DismissedByName  sql.NullString `json:"dismissed_by_name"`
}

func (q *Queries) MergeRequestReviewList(ctx context.Context, mergeRequestID int64) ([]MergeRequestReviewListRow, error) {
	rows, err := q.db.QueryContext(ctx, mergeRequestReviewList, mergeRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MergeRequestReviewListRow
	for rows.Next() {
		var i MergeRequestReviewListRow
		if err := rows.Scan(
			&i.ID,
			&i.MergeRequestID,
			&i.ReviewerID,
			&i.State,
			&i.Body,
			&i.HeadCommitID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DismissedAt,
			&i.DismissedBy,
			&i.DismissedReason,
			&i.ReviewerName,
			&i.ReviewerPhotoUrl,
			&i.DismissedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeRequestReviewRequestCreate = `-- name: MergeRequestReviewRequestCreate :one
INSERT INTO merge_request_review_requests (
    id, merge_request_id, reviewer_id, requested_by
)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (merge_request_id, reviewer_id) DO UPDATE SET
    requested_by = merge_request_review_requests.requested_by
RETURNING id, merge_request_id, reviewer_id, requested_by, created_at
`

type MergeRequestReviewRequestCreateParams struct {
	ID             int64 `json:"id"`
	MergeRequestID int64 `json:"merge_request_id"`
	ReviewerID     int64 `json:"reviewer_id"`
	RequestedBy    int64 `json:"requested_by"`
}

// Re-requesting the same reviewer keeps the original request: the self-update
// makes the conflict branch return the existing row, which DO NOTHING cannot do
// together with RETURNING.
func (q *Queries) MergeRequestReviewRequestCreate(ctx context.Context, arg MergeRequestReviewRequestCreateParams) (MergeRequestReviewRequest, error) {
	row := q.db.QueryRowContext(ctx, mergeRequestReviewRequestCreate,
		arg.ID,
		arg.MergeRequestID,
		arg.ReviewerID,
		arg.RequestedBy,
	)
	var i MergeRequestReviewRequest
	err := row.Scan(
		&i.ID,
		&i.MergeRequestID,
		&i.ReviewerID,
		&i.RequestedBy,
		&i.CreatedAt,
	)
	return i, err
}

const mergeRequestReviewRequestDelete = `-- name: MergeRequestReviewRequestDelete :execrows
DELETE FROM merge_request_review_requests
WHERE merge_request_id = ?1 AND reviewer_id = ?2
`

type MergeRequestReviewRequestDeleteParams struct {
	MergeRequestID int64 `json:"merge_request_id"`
	ReviewerID     int64 `json:"reviewer_id"`
}

func (q *Queries) MergeRequestReviewRequestDelete(ctx context.Context, arg MergeRequestReviewRequestDeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, mergeRequestReviewRequestDelete, arg.MergeRequestID, arg.ReviewerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const mergeRequestReviewRequestList = `-- name: MergeRequestReviewRequestList :many
SELECT
    rr.id, rr.merge_request_id, rr.reviewer_id, rr.requested_by, rr.created_at,
    u.name AS reviewer_name,
    u.photo_url AS reviewer_photo_url,
    q.name AS requested_by_name
FROM merge_request_review_requests rr
JOIN users u ON u.id = rr.reviewer_id
JOIN users q ON q.id = rr.requested_by
WHERE rr.merge_request_id = ?
ORDER BY rr.id
`

type MergeRequestReviewRequestListRow struct {
	ID               int64          `json:"id"`
	MergeRequestID   int64          `json:"merge_request_id"`
	ReviewerID       int64          `json:"reviewer_id"`
	RequestedBy      int64          `json:"requested_by"`
	CreatedAt        time.Time      `json:"created_at"`
	ReviewerName     string         `json:"reviewer_name"`
	ReviewerPhotoUrl sql.NullString `json:"reviewer_photo_url"`
	RequestedByName  string         `json:"requested_by_name"`
}

func (q *Queries) MergeRequestReviewRequestList(ctx context.Context, mergeRequestID int64) ([]MergeRequestReviewRequestListRow, error) {
	rows, err := q.db.QueryContext(ctx, mergeRequestReviewRequestList, mergeRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MergeRequestReviewRequestListRow
	for rows.Next() {
		var i MergeRequestReviewRequestListRow
		if err := rows.Scan(
			&i.ID,
			&i.MergeRequestID,
			&i.ReviewerID,
			&i.RequestedBy,
			&i.CreatedAt,
			&i.ReviewerName,
			&i.ReviewerPhotoUrl,
			&i.RequestedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeRequestReviewStaleList = `-- name: MergeRequestReviewStaleList :many
SELECT id, merge_request_id, reviewer_id, state, body, head_commit_id, created_at, updated_at, dismissed_at, dismissed_by, dismissed_reason FROM merge_request_reviews
WHERE merge_request_id = ?1
  AND dismissed_at IS NULL
  AND state != 'commented'
  AND head_commit_id != ?2
`

type MergeRequestReviewStaleListParams struct {
	MergeRequestID int64 `json:"merge_request_id"`
	HeadCommitID   int64 `json:"head_commit_id"`
}

func (q *Queries) MergeRequestReviewStaleList(ctx context.Context, arg MergeRequestReviewStaleListParams) ([]MergeRequestReview, error) {
	rows, err := q.db.QueryContext(ctx, mergeRequestReviewStaleList, arg.MergeRequestID, arg.HeadCommitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MergeRequestReview
	for rows.Next() {
		var i MergeRequestReview
		if err := rows.Scan(
			&i.ID,
			&i.MergeRequestID,
			&i.ReviewerID,
			&i.State,
			&i.Body,
			&i.HeadCommitID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DismissedAt,
			&i.DismissedBy,
			&i.DismissedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeRequestReviewSummary = `-- name: MergeRequestReviewSummary :many
SELECT
    mr.number AS merge_request_number,
    b.commit_id AS head_commit_id,
    r.state   AS state,
    COUNT(*)  AS count
FROM merge_request_reviews r
JOIN merge_requests mr ON mr.id = r.merge_request_id
LEFT JOIN branches b ON b.id = mr.source_branch_id AND b.deleted = FALSE
WHERE mr.project_id = ?1
  AND r.dismissed_at IS NULL
  AND r.state != 'commented'
  AND r.head_commit_id = COALESCE(b.commit_id, r.head_commit_id)
GROUP BY mr.number, b.commit_id, r.state
`

type MergeRequestReviewSummaryRow struct {
	MergeRequestNumber int64         `json:"merge_request_number"`
	HeadCommitID       sql.NullInt64 `json:"head_commit_id"`
	State              string        `json:"state"`
	Count              int64         `json:"count"`
}

// Aggregates the live review decisions per merge request for the list view.
// The head comparison mirrors the read-time staleness rule the usecase applies
// to individual reviews: a decision given for a head other than the current
// source branch head no longer counts.
func (q *Queries) MergeRequestReviewSummary(ctx context.Context, projectID int64) ([]MergeRequestReviewSummaryRow, error) {
	rows, err := q.db.QueryContext(ctx, mergeRequestReviewSummary, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MergeRequestReviewSummaryRow
	for rows.Next() {
		var i MergeRequestReviewSummaryRow
		if err := rows.Scan(
			&i.MergeRequestNumber,
			&i.HeadCommitID,
			&i.State,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeRequestReviewUpsert = `-- name: MergeRequestReviewUpsert :one
INSERT INTO merge_request_reviews (
    id, merge_request_id, reviewer_id, state, body, head_commit_id
)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (merge_request_id, reviewer_id, head_commit_id) DO UPDATE SET
    state = excluded.state,
    body = excluded.body,
    updated_at = CURRENT_TIMESTAMP,
    dismissed_at = NULL,
    dismissed_by = NULL,
    dismissed_reason = NULL
RETURNING id, merge_request_id, reviewer_id, state, body, head_commit_id, created_at, updated_at, dismissed_at, dismissed_by, dismissed_reason
`

type MergeRequestReviewUpsertParams struct {
	ID             int64  `json:"id"`
	MergeRequestID int64  `json:"merge_request_id"`
	ReviewerID     int64  `json:"reviewer_id"`
	State          string `json:"state"`
	Body           string `json:"body"`
	HeadCommitID   int64  `json:"head_commit_id"`
}

// sqlc only numbers the parameters of the VALUES clause, so the conflict branch
// reads the pending row through excluded instead of repeating named parameters.
func (q *Queries) MergeRequestReviewUpsert(ctx context.Context, arg MergeRequestReviewUpsertParams) (MergeRequestReview, error) {
	row := q.db.QueryRowContext(ctx, mergeRequestReviewUpsert,
		arg.ID,
		arg.MergeRequestID,
		arg.ReviewerID,
		arg.State,
		arg.Body,
		arg.HeadCommitID,
	)
	var i MergeRequestReview
	err := row.Scan(
		&i.ID,
		&i.MergeRequestID,
		&i.ReviewerID,
		&i.State,
		&i.Body,
		&i.HeadCommitID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DismissedAt,
		&i.DismissedBy,
		&i.DismissedReason,
	)
	return i, err
}

const mergeRequestThreadCreate = `-- name: MergeRequestThreadCreate :one
INSERT INTO merge_request_threads (
    id, merge_request_id, file_path, old_line, new_line,
    base_commit_id, head_commit_id, created_by
)
VALUES (?1, ?2, ?3, ?4, ?5,
        ?6, ?7, ?8)
RETURNING id, merge_request_id, file_path, old_line, new_line, base_commit_id, head_commit_id, resolved, resolved_by, resolved_at, created_by, created_at, updated_at, review_id
`

type MergeRequestThreadCreateParams struct {
	ID             int64          `json:"id"`
	MergeRequestID int64          `json:"merge_request_id"`
	FilePath       sql.NullString `json:"file_path"`
	OldLine        sql.NullInt64  `json:"old_line"`
	NewLine        sql.NullInt64  `json:"new_line"`
	BaseCommitID   sql.NullInt64  `json:"base_commit_id"`
	HeadCommitID   sql.NullInt64  `json:"head_commit_id"`
	CreatedBy      int64          `json:"created_by"`
}

func (q *Queries) MergeRequestThreadCreate(ctx context.Context, arg MergeRequestThreadCreateParams) (MergeRequestThread, error) {
	row := q.db.QueryRowContext(ctx, mergeRequestThreadCreate,
		arg.ID,
		arg.MergeRequestID,
		arg.FilePath,
		arg.OldLine,
		arg.NewLine,
		arg.BaseCommitID,
		arg.HeadCommitID,
		arg.CreatedBy,
	)
	var i MergeRequestThread
	err := row.Scan(
		&i.ID,
		&i.MergeRequestID,
		&i.FilePath,
		&i.OldLine,
		&i.NewLine,
		&i.BaseCommitID,
		&i.HeadCommitID,
		&i.Resolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewID,
	)
	return i, err
}

const mergeRequestThreadDelete = `-- name: MergeRequestThreadDelete :execrows
DELETE FROM merge_request_threads
WHERE merge_request_id = ?1 AND id = ?2
`

type MergeRequestThreadDeleteParams struct {
	MergeRequestID int64 `json:"merge_request_id"`
	ID             int64 `json:"id"`
}

func (q *Queries) MergeRequestThreadDelete(ctx context.Context, arg MergeRequestThreadDeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, mergeRequestThreadDelete, arg.MergeRequestID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const mergeRequestThreadGet = `-- name: MergeRequestThreadGet :one
SELECT id, merge_request_id, file_path, old_line, new_line, base_commit_id, head_commit_id, resolved, resolved_by, resolved_at, created_by, created_at, updated_at, review_id FROM merge_request_threads
WHERE merge_request_id = ?1 AND id = ?2
`

type MergeRequestThreadGetParams struct {
	MergeRequestID int64 `json:"merge_request_id"`
	ID             int64 `json:"id"`
}

func (q *Queries) MergeRequestThreadGet(ctx context.Context, arg MergeRequestThreadGetParams) (MergeRequestThread, error) {
	row := q.db.QueryRowContext(ctx, mergeRequestThreadGet, arg.MergeRequestID, arg.ID)
	var i MergeRequestThread
	err := row.Scan(
		&i.ID,
		&i.MergeRequestID,
		&i.FilePath,
		&i.OldLine,
		&i.NewLine,
		&i.BaseCommitID,
		&i.HeadCommitID,
		&i.Resolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewID,
	)
	return i, err
}

const mergeRequestThreadList = `-- name: MergeRequestThreadList :many
SELECT
    t.id, t.merge_request_id, t.file_path, t.old_line, t.new_line, t.base_commit_id, t.head_commit_id, t.resolved, t.resolved_by, t.resolved_at, t.created_by, t.created_at, t.updated_at, t.review_id,
    u.name AS created_by_name,
    u.photo_url AS created_by_photo_url,
    r.name AS resolved_by_name
FROM merge_request_threads t
JOIN users u ON u.id = t.created_by
LEFT JOIN users r ON r.id = t.resolved_by
WHERE t.merge_request_id = ?1
  AND (?2 IS NULL OR t.resolved = ?2)
ORDER BY t.id
`

type MergeRequestThreadListParams struct {
	MergeRequestID int64       `json:"merge_request_id"`
	Resolved       interface{} `json:"resolved"`
}

type MergeRequestThreadListRow struct {
	ID                int64          `json:"id"`
	MergeRequestID    int64          `json:"merge_request_id"`
	FilePath          sql.NullString `json:"file_path"`
	OldLine           sql.NullInt64  `json:"old_line"`
	NewLine           sql.NullInt64  `json:"new_line"`
	BaseCommitID      sql.NullInt64  `json:"base_commit_id"`
	HeadCommitID      sql.NullInt64  `json:"head_commit_id"`
	Resolved          bool           `json:"resolved"`
	ResolvedBy        sql.NullInt64  `json:"resolved_by"`
	ResolvedAt        sql.NullTime   `json:"resolved_at"`
	CreatedBy         int64          `json:"created_by"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	ReviewID          sql.NullInt64  `json:"review_id"`
	CreatedByName     string         `json:"created_by_name"`
	CreatedByPhotoUrl sql.NullString `json:"created_by_photo_url"`
	ResolvedByName    sql.NullString `json:"resolved_by_name"`
}

func (q *Queries) MergeRequestThreadList(ctx context.Context, arg MergeRequestThreadListParams) ([]MergeRequestThreadListRow, error) {
	rows, err := q.db.QueryContext(ctx, mergeRequestThreadList, arg.MergeRequestID, arg.Resolved)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MergeRequestThreadListRow
	for rows.Next() {
		var i MergeRequestThreadListRow
		if err := rows.Scan(
			&i.ID,
			&i.MergeRequestID,
			&i.FilePath,
			&i.OldLine,
			&i.NewLine,
			&i.BaseCommitID,
			&i.HeadCommitID,
			&i.Resolved,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewID,
			&i.CreatedByName,
			&i.CreatedByPhotoUrl,
			&i.ResolvedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeRequestThreadSetResolved = `-- name: MergeRequestThreadSetResolved :one
UPDATE merge_request_threads
SET resolved = ?1,
    resolved_by = ?2,
    resolved_at = ?3,
    updated_at = CURRENT_TIMESTAMP
WHERE merge_request_id = ?4 AND id = ?5
RETURNING id, merge_request_id, file_path, old_line, new_line, base_commit_id, head_commit_id, resolved, resolved_by, resolved_at, created_by, created_at, updated_at, review_id
`

type MergeRequestThreadSetResolvedParams struct {
	Resolved       bool          `json:"resolved"`
	ResolvedBy     sql.NullInt64 `json:"resolved_by"`
	ResolvedAt     sql.NullTime  `json:"resolved_at"`
	MergeRequestID int64         `json:"merge_request_id"`
	ID             int64         `json:"id"`
}

func (q *Queries) MergeRequestThreadSetResolved(ctx context.Context, arg MergeRequestThreadSetResolvedParams) (MergeRequestThread, error) {
	row := q.db.QueryRowContext(ctx, mergeRequestThreadSetResolved,
		arg.Resolved,
		arg.ResolvedBy,
		arg.ResolvedAt,
		arg.MergeRequestID,
		arg.ID,
	)
	var i MergeRequestThread
	err := row.Scan(
		&i.ID,
		&i.MergeRequestID,
		&i.FilePath,
		&i.OldLine,
		&i.NewLine,
		&i.BaseCommitID,
		&i.HeadCommitID,
		&i.Resolved,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewID,
	)
	return i, err
}

const mergeRequestThreadSetReview = `-- name: MergeRequestThreadSetReview :exec
UPDATE merge_request_threads SET review_id = ?1
WHERE merge_request_id = ?2 AND id = ?3
`

type MergeRequestThreadSetReviewParams struct {
	ReviewID       sql.NullInt64 `json:"review_id"`
	MergeRequestID int64         `json:"merge_request_id"`
	ID             int64         `json:"id"`
}

func (q *Queries) MergeRequestThreadSetReview(ctx context.Context, arg MergeRequestThreadSetReviewParams) error {
	_, err := q.db.ExecContext(ctx, mergeRequestThreadSetReview, arg.ReviewID, arg.MergeRequestID, arg.ID)
	return err
}
