// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"database/sql"
	"time"
)

type Branch struct {
	ID          int64         `json:"id"`
	ProjectID   int64         `json:"project_id"`
	Name        string        `json:"name"`
	Key         string        `json:"key"`
	IsProtected bool          `json:"is_protected"`
	IsDefault   bool          `json:"is_default"`
	CommitID    sql.NullInt64 `json:"commit_id"`
	UpdatedAt   time.Time     `json:"updated_at"`
	CreatedAt   time.Time     `json:"created_at"`
	Deleted     bool          `json:"deleted"`
	DeletedAt   sql.NullTime  `json:"deleted_at"`
}

type Chunk struct {
	ID        int64        `json:"id"`
	Hash      []byte       `json:"hash"`
	SizeBytes int64        `json:"size_bytes"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Commit struct {
	ID        int64         `json:"id"`
	Hash      []byte        `json:"hash"`
	ProjectID int64         `json:"project_id"`
	TreeID    int64         `json:"tree_id"`
	Parent1ID sql.NullInt64 `json:"parent_1_id"`
	Parent2ID sql.NullInt64 `json:"parent_2_id"`
	UserID    int64         `json:"user_id"`
	Message   string        `json:"message"`
	CreatedAt time.Time     `json:"created_at"`
}

type File struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	Mode      int64         `json:"mode"`
	TreeID    sql.NullInt64 `json:"tree_id"`
	Hash      []byte        `json:"hash"`
	SizeBytes int64         `json:"size_bytes"`
	IsBinary  bool          `json:"is_binary"`
	Encoding  string        `json:"encoding"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type FileChunk struct {
	FileID     int64 `json:"file_id"`
	ChunkID    int64 `json:"chunk_id"`
	ChunkIndex int64 `json:"chunk_index"`
}

type FileLock struct {
	ID             int64         `json:"id"`
	ProjectID      int64         `json:"project_id"`
	BranchID       sql.NullInt64 `json:"branch_id"`
	Path           string        `json:"path"`
	HeldBy         int64         `json:"held_by"`
	MergeRequestID sql.NullInt64 `json:"merge_request_id"`
	AcquiredAt     time.Time     `json:"acquired_at"`
}

type Group struct {
	ID          int64          `json:"id"`
	OrgID       int64          `json:"org_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	Deleted     bool           `json:"deleted"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type GroupMember struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

type MergeRequest struct {
	ID                int64         `json:"id"`
	Number            int64         `json:"number"`
	ProjectID         int64         `json:"project_id"`
	SourceBranchID    int64         `json:"source_branch_id"`
	TargetBranchID    int64         `json:"target_branch_id"`
	SourceBranchName  string        `json:"source_branch_name"`
	TargetBranchName  string        `json:"target_branch_name"`
	Title             string        `json:"title"`
	Description       string        `json:"description"`
	Status            string        `json:"status"`
	MergeCommitID     sql.NullInt64 `json:"merge_commit_id"`
	MergeBaseCommitID sql.NullInt64 `json:"merge_base_commit_id"`
	CreatedBy         int64         `json:"created_by"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type MergeRequestComment struct {
	ID        int64     `json:"id"`
	ThreadID  int64     `json:"thread_id"`
	UserID    int64     `json:"user_id"`
	Body      string    `json:"body"`
	System    bool      `json:"system"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type MergeRequestEvent struct {
	ID             int64          `json:"id"`
	MergeRequestID int64          `json:"merge_request_id"`
	ActorID        int64          `json:"actor_id"`
	SubjectUserID  sql.NullInt64  `json:"subject_user_id"`
	Kind           string         `json:"kind"`
	Body           string         `json:"body"`
	CommitID       sql.NullInt64  `json:"commit_id"`
	CommitHash     sql.NullString `json:"commit_hash"`
	CreatedAt      time.Time      `json:"created_at"`
}

type MergeRequestReview struct {
	ID              int64          `json:"id"`
	MergeRequestID  int64          `json:"merge_request_id"`
	ReviewerID      int64          `json:"reviewer_id"`
	State           string         `json:"state"`
	Body            string         `json:"body"`
	HeadCommitID    int64          `json:"head_commit_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DismissedAt     sql.NullTime   `json:"dismissed_at"`
	DismissedBy     sql.NullInt64  `json:"dismissed_by"`
	DismissedReason sql.NullString `json:"dismissed_reason"`
}

type MergeRequestReviewRequest struct {
	ID             int64     `json:"id"`
	MergeRequestID int64     `json:"merge_request_id"`
	ReviewerID     int64     `json:"reviewer_id"`
	RequestedBy    int64     `json:"requested_by"`
	CreatedAt      time.Time `json:"created_at"`
}

type MergeRequestThread struct {
	ID             int64          `json:"id"`
	MergeRequestID int64          `json:"merge_request_id"`
	FilePath       sql.NullString `json:"file_path"`
	OldLine        sql.NullInt64  `json:"old_line"`
	NewLine        sql.NullInt64  `json:"new_line"`
	BaseCommitID   sql.NullInt64  `json:"base_commit_id"`
	HeadCommitID   sql.NullInt64  `json:"head_commit_id"`
	Resolved       bool           `json:"resolved"`
	ResolvedBy     sql.NullInt64  `json:"resolved_by"`
	ResolvedAt     sql.NullTime   `json:"resolved_at"`
	CreatedBy      int64          `json:"created_by"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	ReviewID       sql.NullInt64  `json:"review_id"`
}

type OrgMember struct {
	OrgID     int64     `json:"org_id"`
	UserID    int64     `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Organization struct {
	ID        int64        `json:"id"`
	Slug      string       `json:"slug"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	Deleted   bool         `json:"deleted"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type PbacRule struct {
	ID         int64         `json:"id"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UserID     sql.NullInt64 `json:"user_id"`
	GroupID    sql.NullInt64 `json:"group_id"`
	OrgID      int64         `json:"org_id"`
	ProjectID  sql.NullInt64 `json:"project_id"`
	PathPrefix string        `json:"path_prefix"`
	Permission int64         `json:"permission"`
}

type Project struct {
	ID          int64        `json:"id"`
	OrgID       int64        `json:"org_id"`
	Slug        string       `json:"slug"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	Deleted     bool         `json:"deleted"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

type ProjectPathsPermission struct {
	ID         int64        `json:"id"`
	ProjectID  int64        `json:"project_id"`
	PathPrefix string       `json:"path_prefix"`
	Permission int64        `json:"permission"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type RefreshToken struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type TreeNode struct {
	ID           int64         `json:"id"`
	Hash         []byte        `json:"hash"`
	Name         string        `json:"name"`
	Mode         int64         `json:"mode"`
	ParentTreeID sql.NullInt64 `json:"parent_tree_id"`
	CreatedAt    sql.NullTime  `json:"created_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	Password     string         `json:"password"`
	PhotoUrl     sql.NullString `json:"photo_url"`
	IsSuperAdmin bool           `json:"is_super_admin"`
	IsAdmin      bool           `json:"is_admin"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	Deleted      bool           `json:"deleted"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}
