// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_member.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"
)

const orgMemberCountByRole = `-- name: OrgMemberCountByRole :one
SELECT COUNT(*) FROM org_members WHERE org_id = ? AND role = ?
`

type OrgMemberCountByRoleParams struct {
	OrgID int64  `json:"org_id"`
	Role  string `json:"role"`
}

func (q *Queries) OrgMemberCountByRole(ctx context.Context, arg OrgMemberCountByRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, orgMemberCountByRole, arg.OrgID, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const orgMemberDelete = `-- name: OrgMemberDelete :exec
DELETE FROM org_members WHERE org_id = ? AND user_id = ?
`

type OrgMemberDeleteParams struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) OrgMemberDelete(ctx context.Context, arg OrgMemberDeleteParams) error {
	_, err := q.db.ExecContext(ctx, orgMemberDelete, arg.OrgID, arg.UserID)
	return err
}

const orgMemberGet = `-- name: OrgMemberGet :one
SELECT role FROM org_members WHERE org_id = ? AND user_id = ?
`

type OrgMemberGetParams struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) OrgMemberGet(ctx context.Context, arg OrgMemberGetParams) (string, error) {
	row := q.db.QueryRowContext(ctx, orgMemberGet, arg.OrgID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const orgMemberList = `-- name: OrgMemberList :many
SELECT u.id, u.name, u.email, u.photo_url, u.is_admin, u.is_super_admin, om.role, om.created_at
FROM org_members om
JOIN users u ON u.id = om.user_id
WHERE om.org_id = ? AND u.deleted = false
ORDER BY u.name, u.id
`

type OrgMemberListRow struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Email        string         `json:"email"`
	PhotoUrl     sql.NullString `json:"photo_url"`
	IsAdmin      bool           `json:"is_admin"`
	IsSuperAdmin bool           `json:"is_super_admin"`
	Role         string         `json:"role"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) OrgMemberList(ctx context.Context, orgID int64) ([]OrgMemberListRow, error) {
	rows, err := q.db.QueryContext(ctx, orgMemberList, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgMemberListRow
	for rows.Next() {
		var i OrgMemberListRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PhotoUrl,
			&i.IsAdmin,
			&i.IsSuperAdmin,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgMemberListForUser = `-- name: OrgMemberListForUser :many
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at, o.deleted, o.deleted_at, om.role
FROM org_members om
JOIN organizations o ON o.id = om.org_id
WHERE om.user_id = ? AND o.deleted = false
ORDER BY o.name, o.id
`

type OrgMemberListForUserRow struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Slug      string       `json:"slug"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	Deleted   bool         `json:"deleted"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	Role      string       `json:"role"`
}

func (q *Queries) OrgMemberListForUser(ctx context.Context, userID int64) ([]OrgMemberListForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, orgMemberListForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgMemberListForUserRow
	for rows.Next() {
		var i OrgMemberListForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
			&i.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgMemberUpsert = `-- name: OrgMemberUpsert :exec
INSERT INTO org_members (org_id, user_id, role) VALUES (?, ?, ?)
ON CONFLICT(org_id, user_id) DO UPDATE SET role = excluded.role, updated_at = CURRENT_TIMESTAMP
`

type OrgMemberUpsertParams struct {
	OrgID  int64  `json:"org_id"`
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) OrgMemberUpsert(ctx context.Context, arg OrgMemberUpsertParams) error {
	_, err := q.db.ExecContext(ctx, orgMemberUpsert, arg.OrgID, arg.UserID, arg.Role)
	return err
}
