// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package sqlite

import (
	"context"
	"database/sql"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, slug, created_by_user_id) VALUES (?, ?, ?, ?) RETURNING id, slug, name, created_at, updated_at, deleted, deleted_at, created_by_user_id
`

type CreateOrganizationParams struct {
	ID              int64         `json:"id"`
	Name            string        `json:"name"`
	Slug            string        `json:"slug"`
	CreatedByUserID sql.NullInt64 `json:"created_by_user_id"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedByUserID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
UPDATE organizations SET deleted = true, deleted_at = CURRENT_TIMESTAMP WHERE id = ? AND deleted = false
`

func (q *Queries) DeleteOrganization(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrganization, id)
	return err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, slug, name, created_at, updated_at, deleted, deleted_at, created_by_user_id FROM organizations WHERE id = ? AND deleted = false LIMIT 1
`

func (q *Queries) GetOrganization(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, slug, name, created_at, updated_at, deleted, deleted_at, created_by_user_id FROM organizations WHERE slug = ? AND deleted = false LIMIT 1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Deleted,
		&i.DeletedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, slug, name, created_at, updated_at, deleted, deleted_at, created_by_user_id FROM organizations WHERE deleted = false ORDER BY id
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Deleted,
			&i.DeletedAt,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
