// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pbac.sql

package sqlite

import (
	"context"
	"database/sql"
)

const pBACRuleCreate = `-- name: PBACRuleCreate :one
INSERT INTO pbac_rules (user_id, group_id, org_id, project_id, path_prefix, permission)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, created_at, user_id, group_id, org_id, project_id, path_prefix, permission
`

type PBACRuleCreateParams struct {
	UserID     sql.NullInt64 `json:"user_id"`
	GroupID    sql.NullInt64 `json:"group_id"`
	OrgID      int64         `json:"org_id"`
	ProjectID  sql.NullInt64 `json:"project_id"`
	PathPrefix string        `json:"path_prefix"`
	Permission int64         `json:"permission"`
}

func (q *Queries) PBACRuleCreate(ctx context.Context, arg PBACRuleCreateParams) (PbacRule, error) {
	row := q.db.QueryRowContext(ctx, pBACRuleCreate,
		arg.UserID,
		arg.GroupID,
		arg.OrgID,
		arg.ProjectID,
		arg.PathPrefix,
		arg.Permission,
	)
	var i PbacRule
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.GroupID,
		&i.OrgID,
		&i.ProjectID,
		&i.PathPrefix,
		&i.Permission,
	)
	return i, err
}

const pBACRuleDelete = `-- name: PBACRuleDelete :exec
DELETE FROM pbac_rules WHERE id = ?
`

func (q *Queries) PBACRuleDelete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, pBACRuleDelete, id)
	return err
}

const pBACRuleDeleteForProject = `-- name: PBACRuleDeleteForProject :execrows
DELETE FROM pbac_rules
WHERE pbac_rules.id = ?1
  AND (
      project_id = ?2
      OR (
          project_id IS NULL
          AND org_id = (SELECT projects.org_id FROM projects WHERE projects.id = ?2)
      )
  )
`

type PBACRuleDeleteForProjectParams struct {
	RuleID    int64         `json:"rule_id"`
	ProjectID sql.NullInt64 `json:"project_id"`
}

func (q *Queries) PBACRuleDeleteForProject(ctx context.Context, arg PBACRuleDeleteForProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pBACRuleDeleteForProject, arg.RuleID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pBACRuleGetForProject = `-- name: PBACRuleGetForProject :one
SELECT id, created_at, user_id, group_id, org_id, project_id, path_prefix, permission FROM pbac_rules
WHERE pbac_rules.id = ?1
  AND (
      project_id = ?2
      OR (
          project_id IS NULL
          AND org_id = (SELECT projects.org_id FROM projects WHERE projects.id = ?2)
      )
  )
`

type PBACRuleGetForProjectParams struct {
	RuleID    int64         `json:"rule_id"`
	ProjectID sql.NullInt64 `json:"project_id"`
}

func (q *Queries) PBACRuleGetForProject(ctx context.Context, arg PBACRuleGetForProjectParams) (PbacRule, error) {
	row := q.db.QueryRowContext(ctx, pBACRuleGetForProject, arg.RuleID, arg.ProjectID)
	var i PbacRule
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.GroupID,
		&i.OrgID,
		&i.ProjectID,
		&i.PathPrefix,
		&i.Permission,
	)
	return i, err
}

const pBACRuleListByProject = `-- name: PBACRuleListByProject :many
SELECT id, created_at, user_id, group_id, org_id, project_id, path_prefix, permission FROM pbac_rules WHERE project_id = ? ORDER BY id
`

func (q *Queries) PBACRuleListByProject(ctx context.Context, projectID sql.NullInt64) ([]PbacRule, error) {
	rows, err := q.db.QueryContext(ctx, pBACRuleListByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PbacRule
	for rows.Next() {
		var i PbacRule
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.GroupID,
			&i.OrgID,
			&i.ProjectID,
			&i.PathPrefix,
			&i.Permission,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pBACRuleListEffective = `-- name: PBACRuleListEffective :many
SELECT r.id, r.created_at, r.user_id, r.group_id, r.org_id, r.project_id, r.path_prefix, r.permission FROM pbac_rules r
LEFT JOIN group_members gm ON gm.group_id = r.group_id AND gm.user_id = ?1
LEFT JOIN groups g ON g.id = r.group_id
WHERE (
        r.project_id = ?2
        OR (
            r.project_id IS NULL
            AND r.org_id = (SELECT projects.org_id FROM projects WHERE projects.id = ?2)
        )
    )
    AND (
        r.user_id = ?1
        OR (gm.user_id IS NOT NULL AND g.org_id = r.org_id)
    )
ORDER BY r.id
`

type PBACRuleListEffectiveParams struct {
	UserID    int64         `json:"user_id"`
	ProjectID sql.NullInt64 `json:"project_id"`
}

func (q *Queries) PBACRuleListEffective(ctx context.Context, arg PBACRuleListEffectiveParams) ([]PbacRule, error) {
	rows, err := q.db.QueryContext(ctx, pBACRuleListEffective, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PbacRule
	for rows.Next() {
		var i PbacRule
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.GroupID,
			&i.OrgID,
			&i.ProjectID,
			&i.PathPrefix,
			&i.Permission,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectPathPermissionDelete = `-- name: ProjectPathPermissionDelete :exec
DELETE FROM project_paths_permissions WHERE project_id = ? AND path_prefix = ?
`

type ProjectPathPermissionDeleteParams struct {
	ProjectID  int64  `json:"project_id"`
	PathPrefix string `json:"path_prefix"`
}

func (q *Queries) ProjectPathPermissionDelete(ctx context.Context, arg ProjectPathPermissionDeleteParams) error {
	_, err := q.db.ExecContext(ctx, projectPathPermissionDelete, arg.ProjectID, arg.PathPrefix)
	return err
}

const projectPathPermissionList = `-- name: ProjectPathPermissionList :many
SELECT id, project_id, path_prefix, permission, created_at FROM project_paths_permissions WHERE project_id = ? ORDER BY path_prefix
`

func (q *Queries) ProjectPathPermissionList(ctx context.Context, projectID int64) ([]ProjectPathsPermission, error) {
	rows, err := q.db.QueryContext(ctx, projectPathPermissionList, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectPathsPermission
	for rows.Next() {
		var i ProjectPathsPermission
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.PathPrefix,
			&i.Permission,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectPathPermissionUpsert = `-- name: ProjectPathPermissionUpsert :one
INSERT INTO project_paths_permissions (project_id, path_prefix, permission)
VALUES (?, ?, ?)
ON CONFLICT(project_id, path_prefix) DO UPDATE SET permission = excluded.permission
RETURNING id, project_id, path_prefix, permission, created_at
`

type ProjectPathPermissionUpsertParams struct {
	ProjectID  int64  `json:"project_id"`
	PathPrefix string `json:"path_prefix"`
	Permission int64  `json:"permission"`
}

func (q *Queries) ProjectPathPermissionUpsert(ctx context.Context, arg ProjectPathPermissionUpsertParams) (ProjectPathsPermission, error) {
	row := q.db.QueryRowContext(ctx, projectPathPermissionUpsert, arg.ProjectID, arg.PathPrefix, arg.Permission)
	var i ProjectPathsPermission
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PathPrefix,
		&i.Permission,
		&i.CreatedAt,
	)
	return i, err
}
