// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
	"database/sql"
)

type Querier interface {
	BranchCreate(ctx context.Context, arg BranchCreateParams) error
	BranchGet(ctx context.Context, arg BranchGetParams) (Branch, error)
	BranchGetByName(ctx context.Context, arg BranchGetByNameParams) (Branch, error)
	BranchGetDefault(ctx context.Context, projectID int64) (Branch, error)
	BranchList(ctx context.Context, arg BranchListParams) ([]Branch, error)
	BranchMarkDefault(ctx context.Context, arg BranchMarkDefaultParams) error
	BranchRemoveDefault(ctx context.Context, projectID int64) error
	BranchSetName(ctx context.Context, arg BranchSetNameParams) error
	BranchSetProtection(ctx context.Context, arg BranchSetProtectionParams) error
	BranchSoftDelete(ctx context.Context, arg BranchSoftDeleteParams) (int64, error)
	BranchUpdate(ctx context.Context, arg BranchUpdateParams) error
	BranchUpdateCommit(ctx context.Context, arg BranchUpdateCommitParams) error
	BranchUpdateCommitIf(ctx context.Context, arg BranchUpdateCommitIfParams) (sql.Result, error)
	ChunkGetByHash(ctx context.Context, hash []byte) (Chunk, error)
	ChunkInsertOrIgnore(ctx context.Context, arg ChunkInsertOrIgnoreParams) error
	ChunkListByFile(ctx context.Context, fileID int64) ([]Chunk, error)
	CommitGet(ctx context.Context, id int64) (Commit, error)
	CommitGetByHash(ctx context.Context, hash []byte) (Commit, error)
	CommitInsert(ctx context.Context, arg CommitInsertParams) error
	CommitLog(ctx context.Context, arg CommitLogParams) ([]CommitLogRow, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteOrganization(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	FileChunkInsert(ctx context.Context, arg FileChunkInsertParams) error
	FileInsert(ctx context.Context, arg FileInsertParams) (int64, error)
	FileListByTree(ctx context.Context, treeID int64) ([]File, error)
	FileLockCreate(ctx context.Context, arg FileLockCreateParams) (FileLock, error)
	FileLockDelete(ctx context.Context, id int64) (int64, error)
	FileLockDeleteByBranch(ctx context.Context, arg FileLockDeleteByBranchParams) (int64, error)
	FileLockDeleteByMergeRequest(ctx context.Context, arg FileLockDeleteByMergeRequestParams) (int64, error)
	FileLockGet(ctx context.Context, arg FileLockGetParams) (FileLock, error)
	FileLockListProject(ctx context.Context, projectID int64) ([]FileLockListProjectRow, error)
	FileSetTree(ctx context.Context, arg FileSetTreeParams) error
	GetOrganization(ctx context.Context, id int64) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectByOrgIDAndID(ctx context.Context, arg GetProjectByOrgIDAndIDParams) (Project, error)
	GetProjectByOrgIDAndSlug(ctx context.Context, arg GetProjectByOrgIDAndSlugParams) (Project, error)
	GroupCreate(ctx context.Context, arg GroupCreateParams) (Group, error)
	GroupGet(ctx context.Context, id int64) (Group, error)
	GroupListByOrg(ctx context.Context, orgID int64) ([]Group, error)
	GroupListByUser(ctx context.Context, userID int64) ([]Group, error)
	GroupMemberAdd(ctx context.Context, arg GroupMemberAddParams) error
	GroupMemberList(ctx context.Context, groupID int64) ([]GroupMemberListRow, error)
	GroupMemberRemove(ctx context.Context, arg GroupMemberRemoveParams) error
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListProjectsByOrgId(ctx context.Context, orgID int64) ([]Project, error)
	MergeRequestCommentCreate(ctx context.Context, arg MergeRequestCommentCreateParams) (MergeRequestComment, error)
	MergeRequestCommentDelete(ctx context.Context, arg MergeRequestCommentDeleteParams) (int64, error)
	MergeRequestCommentGet(ctx context.Context, arg MergeRequestCommentGetParams) (MergeRequestComment, error)
	MergeRequestCommentListByThread(ctx context.Context, mergeRequestID int64) ([]MergeRequestCommentListByThreadRow, error)
	MergeRequestCommentUpdate(ctx context.Context, arg MergeRequestCommentUpdateParams) (MergeRequestComment, error)
	MergeRequestCountOpenByBranch(ctx context.Context, arg MergeRequestCountOpenByBranchParams) (int64, error)
	MergeRequestCreate(ctx context.Context, arg MergeRequestCreateParams) (MergeRequest, error)
	MergeRequestEventCreate(ctx context.Context, arg MergeRequestEventCreateParams) (MergeRequestEvent, error)
	MergeRequestEventList(ctx context.Context, mergeRequestID int64) ([]MergeRequestEventListRow, error)
	MergeRequestGet(ctx context.Context, arg MergeRequestGetParams) (MergeRequest, error)
	MergeRequestList(ctx context.Context, arg MergeRequestListParams) ([]MergeRequest, error)
	MergeRequestListByStatus(ctx context.Context, arg MergeRequestListByStatusParams) ([]MergeRequest, error)
	MergeRequestListOpenBySourceBranch(ctx context.Context, arg MergeRequestListOpenBySourceBranchParams) ([]MergeRequest, error)
	MergeRequestReviewDelete(ctx context.Context, arg MergeRequestReviewDeleteParams) (int64, error)
	MergeRequestReviewDismiss(ctx context.Context, arg MergeRequestReviewDismissParams) error
	MergeRequestReviewDismissStale(ctx context.Context, arg MergeRequestReviewDismissStaleParams) error
	MergeRequestReviewGet(ctx context.Context, arg MergeRequestReviewGetParams) (MergeRequestReview, error)
	MergeRequestReviewList(ctx context.Context, mergeRequestID int64) ([]MergeRequestReviewListRow, error)
	// Re-requesting the same reviewer keeps the original request: the self-update
	// makes the conflict branch return the existing row, which DO NOTHING cannot do
	// together with RETURNING.
	MergeRequestReviewRequestCreate(ctx context.Context, arg MergeRequestReviewRequestCreateParams) (MergeRequestReviewRequest, error)
	MergeRequestReviewRequestDelete(ctx context.Context, arg MergeRequestReviewRequestDeleteParams) (int64, error)
	MergeRequestReviewRequestList(ctx context.Context, mergeRequestID int64) ([]MergeRequestReviewRequestListRow, error)
	MergeRequestReviewStaleList(ctx context.Context, arg MergeRequestReviewStaleListParams) ([]MergeRequestReview, error)
	// Aggregates the live review decisions per merge request for the list view.
	// The head comparison mirrors the read-time staleness rule the usecase applies
	// to individual reviews: a decision given for a head other than the current
	// source branch head no longer counts.
	MergeRequestReviewSummary(ctx context.Context, projectID int64) ([]MergeRequestReviewSummaryRow, error)
	// sqlc only numbers the parameters of the VALUES clause, so the conflict branch
	// reads the pending row through excluded instead of repeating named parameters.
	MergeRequestReviewUpsert(ctx context.Context, arg MergeRequestReviewUpsertParams) (MergeRequestReview, error)
	MergeRequestThreadCreate(ctx context.Context, arg MergeRequestThreadCreateParams) (MergeRequestThread, error)
	MergeRequestThreadDelete(ctx context.Context, arg MergeRequestThreadDeleteParams) (int64, error)
	MergeRequestThreadGet(ctx context.Context, arg MergeRequestThreadGetParams) (MergeRequestThread, error)
	MergeRequestThreadList(ctx context.Context, arg MergeRequestThreadListParams) ([]MergeRequestThreadListRow, error)
	MergeRequestThreadSetResolved(ctx context.Context, arg MergeRequestThreadSetResolvedParams) (MergeRequestThread, error)
	MergeRequestThreadSetReview(ctx context.Context, arg MergeRequestThreadSetReviewParams) error
	MergeRequestUpdate(ctx context.Context, arg MergeRequestUpdateParams) (MergeRequest, error)
	MergeRequestUpdateStatus(ctx context.Context, arg MergeRequestUpdateStatusParams) error
	OrgMemberCountByRole(ctx context.Context, arg OrgMemberCountByRoleParams) (int64, error)
	OrgMemberDelete(ctx context.Context, arg OrgMemberDeleteParams) error
	OrgMemberGet(ctx context.Context, arg OrgMemberGetParams) (string, error)
	OrgMemberList(ctx context.Context, orgID int64) ([]OrgMemberListRow, error)
	OrgMemberListForUser(ctx context.Context, userID int64) ([]OrgMemberListForUserRow, error)
	OrgMemberUpsert(ctx context.Context, arg OrgMemberUpsertParams) error
	PBACRuleCreate(ctx context.Context, arg PBACRuleCreateParams) (PbacRule, error)
	PBACRuleDelete(ctx context.Context, id int64) error
	PBACRuleDeleteForProject(ctx context.Context, arg PBACRuleDeleteForProjectParams) (int64, error)
	PBACRuleGetForProject(ctx context.Context, arg PBACRuleGetForProjectParams) (PbacRule, error)
	PBACRuleListByProject(ctx context.Context, projectID sql.NullInt64) ([]PbacRule, error)
	PBACRuleListEffective(ctx context.Context, arg PBACRuleListEffectiveParams) ([]PbacRule, error)
	ProjectPathPermissionDelete(ctx context.Context, arg ProjectPathPermissionDeleteParams) error
	ProjectPathPermissionList(ctx context.Context, projectID int64) ([]ProjectPathsPermission, error)
	ProjectPathPermissionUpsert(ctx context.Context, arg ProjectPathPermissionUpsertParams) (ProjectPathsPermission, error)
	RefreshTokenCreate(ctx context.Context, arg RefreshTokenCreateParams) (int64, error)
	RefreshTokenDeleteByToken(ctx context.Context, token string) (RefreshToken, error)
	TreeNodeGet(ctx context.Context, id int64) (TreeNode, error)
	TreeNodeGetChildByName(ctx context.Context, arg TreeNodeGetChildByNameParams) (TreeNode, error)
	TreeNodeInsert(ctx context.Context, arg TreeNodeInsertParams) (int64, error)
	TreeNodeListChildren(ctx context.Context, parentTreeID int64) ([]TreeNode, error)
	TreeNodeSetParent(ctx context.Context, arg TreeNodeSetParentParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UserCreate(ctx context.Context, arg UserCreateParams) (int64, error)
	UserDeleteByID(ctx context.Context, id int64) error
	UserGetByEmail(ctx context.Context, email string) (User, error)
	UserGetById(ctx context.Context, id int64) (User, error)
	UserList(ctx context.Context) ([]User, error)
	UserUpdateAdminFlags(ctx context.Context, arg UserUpdateAdminFlagsParams) error
	UserUpdateEmail(ctx context.Context, arg UserUpdateEmailParams) error
	UserUpdatePassword(ctx context.Context, arg UserUpdatePasswordParams) error
	UserUpdateProfile(ctx context.Context, arg UserUpdateProfileParams) error
}

var _ Querier = (*Queries)(nil)
