// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
	"database/sql"
)

type Querier interface {
	BranchCreate(ctx context.Context, arg BranchCreateParams) error
	BranchGet(ctx context.Context, arg BranchGetParams) (Branch, error)
	BranchGetByName(ctx context.Context, arg BranchGetByNameParams) (Branch, error)
	BranchGetDefault(ctx context.Context, projectID int64) (Branch, error)
	BranchList(ctx context.Context, arg BranchListParams) ([]Branch, error)
	BranchMarkDefault(ctx context.Context, arg BranchMarkDefaultParams) error
	BranchRemoveDefault(ctx context.Context, projectID int64) error
	BranchSetName(ctx context.Context, arg BranchSetNameParams) error
	BranchSetProtection(ctx context.Context, arg BranchSetProtectionParams) error
	BranchSoftDelete(ctx context.Context, arg BranchSoftDeleteParams) (int64, error)
	BranchUpdate(ctx context.Context, arg BranchUpdateParams) error
	BranchUpdateCommit(ctx context.Context, arg BranchUpdateCommitParams) error
	BranchUpdateCommitIf(ctx context.Context, arg BranchUpdateCommitIfParams) (sql.Result, error)
	ChunkGetByHash(ctx context.Context, hash []byte) (Chunk, error)
	ChunkInsertOrIgnore(ctx context.Context, arg ChunkInsertOrIgnoreParams) error
	ChunkListByFile(ctx context.Context, fileID int64) ([]Chunk, error)
	CommitGet(ctx context.Context, id int64) (Commit, error)
	CommitGetByHash(ctx context.Context, hash []byte) (Commit, error)
	CommitInsert(ctx context.Context, arg CommitInsertParams) error
	CommitLog(ctx context.Context, arg CommitLogParams) ([]CommitLogRow, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteOrganization(ctx context.Context, id int64) error
	DeleteProject(ctx context.Context, id int64) error
	FileChunkInsert(ctx context.Context, arg FileChunkInsertParams) error
	FileInsert(ctx context.Context, arg FileInsertParams) (int64, error)
	FileListByTree(ctx context.Context, treeID int64) ([]File, error)
	FileSetTree(ctx context.Context, arg FileSetTreeParams) error
	GetOrganization(ctx context.Context, id int64) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectByOrgIDAndID(ctx context.Context, arg GetProjectByOrgIDAndIDParams) (Project, error)
	GetProjectByOrgIDAndSlug(ctx context.Context, arg GetProjectByOrgIDAndSlugParams) (Project, error)
	GroupCreate(ctx context.Context, arg GroupCreateParams) (Group, error)
	GroupGet(ctx context.Context, id int64) (Group, error)
	GroupListByOrg(ctx context.Context, orgID int64) ([]Group, error)
	GroupListByUser(ctx context.Context, userID int64) ([]Group, error)
	GroupMemberAdd(ctx context.Context, arg GroupMemberAddParams) error
	GroupMemberList(ctx context.Context, groupID int64) ([]GroupMemberListRow, error)
	GroupMemberRemove(ctx context.Context, arg GroupMemberRemoveParams) error
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListProjectsByOrgId(ctx context.Context, orgID int64) ([]Project, error)
	OrgMemberCountByRole(ctx context.Context, arg OrgMemberCountByRoleParams) (int64, error)
	OrgMemberDelete(ctx context.Context, arg OrgMemberDeleteParams) error
	OrgMemberGet(ctx context.Context, arg OrgMemberGetParams) (string, error)
	OrgMemberList(ctx context.Context, orgID int64) ([]OrgMemberListRow, error)
	OrgMemberListForUser(ctx context.Context, userID int64) ([]OrgMemberListForUserRow, error)
	OrgMemberUpsert(ctx context.Context, arg OrgMemberUpsertParams) error
	PBACRuleCreate(ctx context.Context, arg PBACRuleCreateParams) (PbacRule, error)
	PBACRuleDelete(ctx context.Context, id int64) error
	PBACRuleDeleteForProject(ctx context.Context, arg PBACRuleDeleteForProjectParams) (int64, error)
	PBACRuleGetForProject(ctx context.Context, arg PBACRuleGetForProjectParams) (PbacRule, error)
	PBACRuleListByProject(ctx context.Context, projectID sql.NullInt64) ([]PbacRule, error)
	PBACRuleListEffective(ctx context.Context, arg PBACRuleListEffectiveParams) ([]PbacRule, error)
	ProjectPathPermissionDelete(ctx context.Context, arg ProjectPathPermissionDeleteParams) error
	ProjectPathPermissionList(ctx context.Context, projectID int64) ([]ProjectPathsPermission, error)
	ProjectPathPermissionUpsert(ctx context.Context, arg ProjectPathPermissionUpsertParams) (ProjectPathsPermission, error)
	RefreshTokenCreate(ctx context.Context, arg RefreshTokenCreateParams) (int64, error)
	RefreshTokenDeleteByToken(ctx context.Context, token string) (RefreshToken, error)
	TreeNodeGet(ctx context.Context, id int64) (TreeNode, error)
	TreeNodeGetChildByName(ctx context.Context, arg TreeNodeGetChildByNameParams) (TreeNode, error)
	TreeNodeInsert(ctx context.Context, arg TreeNodeInsertParams) (int64, error)
	TreeNodeListChildren(ctx context.Context, parentTreeID int64) ([]TreeNode, error)
	TreeNodeSetParent(ctx context.Context, arg TreeNodeSetParentParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UserCreate(ctx context.Context, arg UserCreateParams) (int64, error)
	UserDeleteByID(ctx context.Context, id int64) error
	UserGetByEmail(ctx context.Context, email string) (User, error)
	UserGetById(ctx context.Context, id int64) (User, error)
	UserList(ctx context.Context) ([]User, error)
	UserUpdateAdminFlags(ctx context.Context, arg UserUpdateAdminFlagsParams) error
	UserUpdateEmail(ctx context.Context, arg UserUpdateEmailParams) error
	UserUpdatePassword(ctx context.Context, arg UserUpdatePasswordParams) error
	UserUpdateProfile(ctx context.Context, arg UserUpdateProfileParams) error
}

var _ Querier = (*Queries)(nil)
