// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag.sql

package sqlite

import (
	"context"
)

const tagCreate = `-- name: TagCreate :one
INSERT INTO tags (id, project_id, name, key, commit_id, message, user_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, name, "key", commit_id, message, user_id, created_at, updated_at
`

type TagCreateParams struct {
	ID        int64  `json:"id"`
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
	Key       string `json:"key"`
	CommitID  int64  `json:"commit_id"`
	Message   string `json:"message"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) TagCreate(ctx context.Context, arg TagCreateParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, tagCreate,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Key,
		arg.CommitID,
		arg.Message,
		arg.UserID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Key,
		&i.CommitID,
		&i.Message,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tagDelete = `-- name: TagDelete :execrows
DELETE FROM tags
WHERE project_id = ? AND id = ?
`

type TagDeleteParams struct {
	ProjectID int64 `json:"project_id"`
	ID        int64 `json:"id"`
}

func (q *Queries) TagDelete(ctx context.Context, arg TagDeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, tagDelete, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const tagGetByName = `-- name: TagGetByName :one
SELECT id, project_id, name, "key", commit_id, message, user_id, created_at, updated_at
FROM tags
WHERE project_id = ?1 AND key = ?2
LIMIT 1
`

type TagGetByNameParams struct {
	ProjectID int64  `json:"project_id"`
	Key       string `json:"key"`
}

func (q *Queries) TagGetByName(ctx context.Context, arg TagGetByNameParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, tagGetByName, arg.ProjectID, arg.Key)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Key,
		&i.CommitID,
		&i.Message,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tagList = `-- name: TagList :many
SELECT id, project_id, name, "key", commit_id, message, user_id, created_at, updated_at
FROM tags
WHERE project_id = ?1
  AND (?2 is null OR created_at < ?2 OR (created_at = ?2 AND id < ?3))
ORDER BY created_at DESC, id DESC
LIMIT ?4
`

type TagListParams struct {
	ProjectID     int64       `json:"project_id"`
	LastCreatedAt interface{} `json:"last_created_at"`
	LastID        int64       `json:"last_id"`
	Limit         int64       `json:"limit"`
}

func (q *Queries) TagList(ctx context.Context, arg TagListParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, tagList,
		arg.ProjectID,
		arg.LastCreatedAt,
		arg.LastID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Key,
			&i.CommitID,
			&i.Message,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
