// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tree.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"
)

const chunkListByFile = `-- name: ChunkListByFile :many
SELECT chunks.id, chunks.hash, chunks.size_bytes, chunks.created_at
FROM chunks
JOIN file_chunks ON file_chunks.chunk_id = chunks.id
WHERE file_chunks.file_id = ?1
ORDER BY file_chunks.chunk_index
`

func (q *Queries) ChunkListByFile(ctx context.Context, fileID int64) ([]Chunk, error) {
	rows, err := q.db.QueryContext(ctx, chunkListByFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chunk
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const commitGet = `-- name: CommitGet :one
SELECT id, hash, project_id, tree_id, parent_1_id, parent_2_id, user_id, message, created_at
FROM commits
WHERE id = ?1
LIMIT 1
`

func (q *Queries) CommitGet(ctx context.Context, id int64) (Commit, error) {
	row := q.db.QueryRowContext(ctx, commitGet, id)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.ProjectID,
		&i.TreeID,
		&i.Parent1ID,
		&i.Parent2ID,
		&i.UserID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const commitGetByHash = `-- name: CommitGetByHash :one
SELECT id, hash, project_id, tree_id, parent_1_id, parent_2_id, user_id, message, created_at
FROM commits
WHERE hash = ?1
LIMIT 1
`

func (q *Queries) CommitGetByHash(ctx context.Context, hash []byte) (Commit, error) {
	row := q.db.QueryRowContext(ctx, commitGetByHash, hash)
	var i Commit
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.ProjectID,
		&i.TreeID,
		&i.Parent1ID,
		&i.Parent2ID,
		&i.UserID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const commitLog = `-- name: CommitLog :many
WITH RECURSIVE commit_chain(id, depth) AS (
    SELECT ?3 AS id, 0 AS depth
    UNION ALL
    SELECT c.parent_1_id, cc.depth + 1 FROM commits c JOIN commit_chain cc ON c.id = cc.id
    WHERE c.parent_1_id IS NOT NULL
)
SELECT c.id, c.hash, c.project_id, c.tree_id, c.parent_1_id, c.parent_2_id, c.user_id, c.message, c.created_at,
       u.name AS author_name, u.email AS author_email
FROM commits c
JOIN users u ON c.user_id = u.id
JOIN commit_chain cc ON c.id = cc.id
WHERE c.project_id = ?1
ORDER BY cc.depth ASC, c.id DESC
LIMIT ?2
`

type CommitLogParams struct {
	ProjectID     int64 `json:"project_id"`
	Limit         int64 `json:"limit"`
	StartCommitID int64 `json:"start_commit_id"`
}

type CommitLogRow struct {
	ID          int64         `json:"id"`
	Hash        []byte        `json:"hash"`
	ProjectID   int64         `json:"project_id"`
	TreeID      int64         `json:"tree_id"`
	Parent1ID   sql.NullInt64 `json:"parent_1_id"`
	Parent2ID   sql.NullInt64 `json:"parent_2_id"`
	UserID      int64         `json:"user_id"`
	Message     string        `json:"message"`
	CreatedAt   time.Time     `json:"created_at"`
	AuthorName  string        `json:"author_name"`
	AuthorEmail string        `json:"author_email"`
}

func (q *Queries) CommitLog(ctx context.Context, arg CommitLogParams) ([]CommitLogRow, error) {
	rows, err := q.db.QueryContext(ctx, commitLog, arg.ProjectID, arg.Limit, arg.StartCommitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommitLogRow
	for rows.Next() {
		var i CommitLogRow
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.ProjectID,
			&i.TreeID,
			&i.Parent1ID,
			&i.Parent2ID,
			&i.UserID,
			&i.Message,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fileListByTree = `-- name: FileListByTree :many
SELECT f.id, f.name, f.mode, f.tree_id, f.hash, f.size_bytes, f.is_binary, f.created_at, f.encoding
FROM files f
WHERE f.tree_id = (
        SELECT content.id
        FROM tree_nodes content
        JOIN tree_nodes ref ON ref.hash = content.hash
        WHERE ref.id = ?1
          AND EXISTS (SELECT 1 FROM files cf WHERE cf.tree_id = content.id)
        ORDER BY content.id
        LIMIT 1
    )
ORDER BY f.name
`

func (q *Queries) FileListByTree(ctx context.Context, treeID int64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, fileListByTree, treeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Mode,
			&i.TreeID,
			&i.Hash,
			&i.SizeBytes,
			&i.IsBinary,
			&i.CreatedAt,
			&i.Encoding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const treeNodeGet = `-- name: TreeNodeGet :one
SELECT id, hash, name, mode, parent_tree_id, created_at
FROM tree_nodes
WHERE id = ?1
LIMIT 1
`

func (q *Queries) TreeNodeGet(ctx context.Context, id int64) (TreeNode, error) {
	row := q.db.QueryRowContext(ctx, treeNodeGet, id)
	var i TreeNode
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Mode,
		&i.ParentTreeID,
		&i.CreatedAt,
	)
	return i, err
}

const treeNodeGetChildByName = `-- name: TreeNodeGetChildByName :one
SELECT t.id, t.hash, t.name, t.mode, t.parent_tree_id, t.created_at
FROM tree_nodes t
WHERE t.parent_tree_id = (
        SELECT content.id
        FROM tree_nodes content
        JOIN tree_nodes ref ON ref.hash = content.hash
        WHERE ref.id = ?1
          AND (
              EXISTS (SELECT 1 FROM files f WHERE f.tree_id = content.id)
              OR EXISTS (SELECT 1 FROM tree_nodes c WHERE c.parent_tree_id = content.id)
          )
        ORDER BY content.id
        LIMIT 1
    )
    AND t.name = ?2
LIMIT 1
`

type TreeNodeGetChildByNameParams struct {
	ParentTreeID int64  `json:"parent_tree_id"`
	Name         string `json:"name"`
}

func (q *Queries) TreeNodeGetChildByName(ctx context.Context, arg TreeNodeGetChildByNameParams) (TreeNode, error) {
	row := q.db.QueryRowContext(ctx, treeNodeGetChildByName, arg.ParentTreeID, arg.Name)
	var i TreeNode
	err := row.Scan(
		&i.ID,
		&i.Hash,
		&i.Name,
		&i.Mode,
		&i.ParentTreeID,
		&i.CreatedAt,
	)
	return i, err
}

const treeNodeListChildren = `-- name: TreeNodeListChildren :many
SELECT t.id, t.hash, t.name, t.mode, t.parent_tree_id, t.created_at
FROM tree_nodes t
WHERE t.parent_tree_id = (
        SELECT content.id
        FROM tree_nodes content
        JOIN tree_nodes ref ON ref.hash = content.hash
        WHERE ref.id = ?1
          AND (
              EXISTS (SELECT 1 FROM files f WHERE f.tree_id = content.id)
              OR EXISTS (SELECT 1 FROM tree_nodes c WHERE c.parent_tree_id = content.id)
          )
        ORDER BY content.id
        LIMIT 1
    )
ORDER BY t.name
`

func (q *Queries) TreeNodeListChildren(ctx context.Context, parentTreeID int64) ([]TreeNode, error) {
	rows, err := q.db.QueryContext(ctx, treeNodeListChildren, parentTreeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TreeNode
	for rows.Next() {
		var i TreeNode
		if err := rows.Scan(
			&i.ID,
			&i.Hash,
			&i.Name,
			&i.Mode,
			&i.ParentTreeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
