syntax = "proto3";

package greet;
option go_package = "./pb";

import "google/protobuf/timestamp.proto";

message ProjectContext {
    string org = 1;
    string project = 2;
}

enum FileMode {
    FILE_MODE_UNSPECIFIED = 0;
    FILE_MODE_READ_ONLY = 1;
    FILE_MODE_READ_WRITE = 2;
    FILE_MODE_EXECUTABLE = 3;
}

message FileNode {
    string path = 1;
    FileMode mode = 2;
    int64 size_bytes = 3;
    bool is_binary = 4;
    repeated string chunk_hashes = 5;
}

message TreeManifest {
    string tree_hash = 1;
    string path = 2; // Subdirectory path, e.g., "assets/shaders"
    repeated TreeManifest sub_trees = 3; // Child directory trees
    repeated FileNode files = 4;
}

message GetTreeManifestRequest {
    ProjectContext context = 1;
    string branch = 2;
    string path = 3;
    optional string tree_hash = 4;
    bool recursive = 5;
}

message GetTreeManifestResponse {
    string branch = 1;
    TreeManifest root_tree = 2;
}

message Branch {
    google.protobuf.Timestamp created_at = 1;
    google.protobuf.Timestamp updated_at = 2;
    string id = 3;
    string name = 4;
    string commit_id = 5;
    bool is_protected = 6;
    bool is_default = 7;
}

message GetListBranchRequest {
    ProjectContext context = 1;
    int32 limit = 2;
    optional google.protobuf.Timestamp last_updated_at = 3;
    optional string last_id = 4;
}

message GetListBranchResponse {
    repeated Branch branches = 1;
}

message GetBranchRequest {
    ProjectContext context = 1;
    string branch_id = 2;
}

message GetDefaultBranchRequest {
    ProjectContext context = 1;
}

message GetBranchResponse {
    Branch branch = 1;
}

message LoginUsernamePasswordRequest {
    string username = 1;
    string password = 2;
}

message LoginWithRefreshRequest {
    string refresh_token = 1;
}

message LoginResponse {
    string access_token = 1;
    string refresh_token = 2;
    int32 expires_in = 3;
}

service NipaService {
    rpc LoginWithUsernamePassword(LoginUsernamePasswordRequest) returns (LoginResponse);
    rpc LoginWithRefreshToken(LoginWithRefreshRequest) returns (LoginResponse);

    rpc GetListBranch(GetListBranchRequest) returns (GetListBranchResponse);
    rpc GetBranch(GetBranchRequest) returns (GetBranchResponse);
    rpc GetDefaultBranch(GetDefaultBranchRequest) returns (GetBranchResponse);
    rpc GetTreeManifest(GetTreeManifestRequest) returns (GetTreeManifestResponse);
}
