-- Nipa Enterprise Edition postgres schema. Server entities carry app-generated
-- snowflake ids (BIGINT, no identity); surrogate row ids (trees, files, chunks,
-- rules, path permissions, refresh tokens) use identity columns.

CREATE TABLE users (
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    photo_url TEXT,
    is_super_admin BOOLEAN NOT NULL DEFAULT false,
    is_admin BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE organizations (
    id BIGINT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMPTZ,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id)
);

CREATE TABLE projects (
    id BIGINT PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    slug TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMPTZ,
    UNIQUE(org_id, slug)
);

CREATE TABLE groups (
    id BIGINT PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted BOOLEAN NOT NULL DEFAULT false,
    deleted_at TIMESTAMPTZ,
    UNIQUE (org_id, name)
);

CREATE TABLE group_members (
    group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, user_id)
);

CREATE INDEX idx_group_members_user ON group_members(user_id);

CREATE TABLE pbac_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    group_id BIGINT REFERENCES groups(id) ON DELETE CASCADE,
    org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
    path_prefix TEXT NOT NULL DEFAULT '',
    permission BIGINT NOT NULL DEFAULT 0,
    CHECK (user_id IS NOT NULL OR group_id IS NOT NULL),
    CHECK (user_id IS NULL OR group_id IS NULL)
);

CREATE INDEX idx_pbac_rules_project ON pbac_rules(project_id);
CREATE INDEX idx_pbac_rules_user ON pbac_rules(user_id);
CREATE INDEX idx_pbac_rules_group ON pbac_rules(group_id);

CREATE TABLE project_paths_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    path_prefix TEXT NOT NULL,
    permission BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (project_id, path_prefix)
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE org_members (
    org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'member',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (org_id, user_id),
    CHECK (role IN ('owner', 'member'))
);

CREATE INDEX idx_org_members_user ON org_members (user_id);

CREATE TABLE tree_nodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash BYTEA NOT NULL,
    name TEXT NOT NULL,
    mode BIGINT NOT NULL DEFAULT 444,
    parent_tree_id BIGINT REFERENCES tree_nodes(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(parent_tree_id, name)
);

CREATE INDEX idx_tree_nodes_hash ON tree_nodes(hash);
CREATE INDEX idx_tree_nodes_parent ON tree_nodes(parent_tree_id);

CREATE TABLE chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash BYTEA NOT NULL UNIQUE,
    size_bytes BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    mode BIGINT NOT NULL DEFAULT 444,
    tree_id BIGINT REFERENCES tree_nodes(id) ON DELETE CASCADE,
    hash BYTEA NOT NULL,
    size_bytes BIGINT NOT NULL,
    is_binary BOOLEAN NOT NULL DEFAULT FALSE,
    encoding TEXT NOT NULL DEFAULT 'raw',
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(tree_id, name)
);

CREATE INDEX idx_files_tree_id ON files(tree_id);

CREATE TABLE file_chunks (
    file_id BIGINT NOT NULL REFERENCES files(id) ON DELETE CASCADE,
    chunk_id BIGINT NOT NULL REFERENCES chunks(id),
    chunk_index BIGINT NOT NULL,
    PRIMARY KEY (file_id, chunk_index)
);

CREATE TABLE commits (
    id BIGINT PRIMARY KEY,
    hash BYTEA NOT NULL UNIQUE,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    tree_id BIGINT NOT NULL REFERENCES tree_nodes(id),
    parent_1_id BIGINT REFERENCES commits(id),
    parent_2_id BIGINT REFERENCES commits(id),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE branches (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    key TEXT NOT NULL,
    is_protected BOOLEAN NOT NULL DEFAULT FALSE,
    required_approvals BIGINT NOT NULL DEFAULT 0,
    dismiss_stale_approvals BOOLEAN NOT NULL DEFAULT TRUE,
    require_status_checks BOOLEAN NOT NULL DEFAULT FALSE,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    commit_id BIGINT REFERENCES commits(id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX idx_branches_project_key
    ON branches (project_id, key)
    WHERE deleted = FALSE;

CREATE INDEX idx_branches_project_updated_id
    ON branches (project_id, updated_at DESC, id DESC);

CREATE UNIQUE INDEX idx_branches_one_default_per_project
    ON branches (project_id)
    WHERE is_default = TRUE;

CREATE TABLE branches_required_reviewers (
    branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    PRIMARY KEY (branch_id, user_id)
);

CREATE TABLE branches_required_checks (
    branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    PRIMARY KEY (branch_id, name)
);

CREATE TABLE merge_requests (
    id BIGINT PRIMARY KEY,
    number BIGINT NOT NULL,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    source_branch_id BIGINT NOT NULL REFERENCES branches(id),
    target_branch_id BIGINT NOT NULL REFERENCES branches(id),
    source_branch_name TEXT NOT NULL,
    target_branch_name TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'open',
    is_draft BOOLEAN NOT NULL DEFAULT FALSE,
    merge_commit_id BIGINT REFERENCES commits(id),
    merge_base_commit_id BIGINT REFERENCES commits(id),
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (status IN ('open', 'merged', 'closed'))
);

CREATE INDEX idx_merge_requests_project ON merge_requests (project_id, id DESC);

CREATE UNIQUE INDEX idx_merge_requests_project_number ON merge_requests (project_id, number);

CREATE TABLE merge_request_assignees (
    merge_request_id BIGINT NOT NULL REFERENCES merge_requests(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    PRIMARY KEY (merge_request_id, user_id)
);

CREATE INDEX idx_merge_request_assignees_user ON merge_request_assignees (user_id);

CREATE TABLE merge_request_checks (
    id BIGINT PRIMARY KEY,
    merge_request_id BIGINT NOT NULL REFERENCES merge_requests(id) ON DELETE CASCADE,
    head_commit_id BIGINT NOT NULL REFERENCES commits(id),
    name TEXT NOT NULL,
    state TEXT NOT NULL,
    details_url TEXT NOT NULL DEFAULT '',
    reporter_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (state IN ('pending', 'success', 'failed')),
    UNIQUE (merge_request_id, head_commit_id, name)
);

CREATE INDEX idx_merge_request_checks_mr ON merge_request_checks (merge_request_id, head_commit_id);

CREATE TABLE merge_request_reviews (
    id BIGINT PRIMARY KEY,
    merge_request_id BIGINT NOT NULL REFERENCES merge_requests(id) ON DELETE CASCADE,
    reviewer_id BIGINT NOT NULL REFERENCES users(id),
    state TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    head_commit_id BIGINT NOT NULL REFERENCES commits(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    dismissed_at TIMESTAMPTZ,
    dismissed_by BIGINT REFERENCES users(id),
    dismissed_reason TEXT,
    CHECK (state IN ('commented', 'approved', 'changes_requested'))
);

CREATE UNIQUE INDEX idx_merge_request_reviews_round
    ON merge_request_reviews (merge_request_id, reviewer_id, head_commit_id);

CREATE INDEX idx_merge_request_reviews_mr
    ON merge_request_reviews (merge_request_id, id);

CREATE TABLE merge_request_review_requests (
    id BIGINT PRIMARY KEY,
    merge_request_id BIGINT NOT NULL REFERENCES merge_requests(id) ON DELETE CASCADE,
    reviewer_id BIGINT NOT NULL REFERENCES users(id),
    requested_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (merge_request_id, reviewer_id)
);

CREATE INDEX idx_merge_request_review_requests_mr
    ON merge_request_review_requests (merge_request_id);

CREATE TABLE merge_request_threads (
    id BIGINT PRIMARY KEY,
    merge_request_id BIGINT NOT NULL REFERENCES merge_requests(id) ON DELETE CASCADE,
    file_path TEXT,
    old_line BIGINT,
    new_line BIGINT,
    base_commit_id BIGINT REFERENCES commits(id),
    head_commit_id BIGINT REFERENCES commits(id),
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_by BIGINT REFERENCES users(id),
    resolved_at TIMESTAMPTZ,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    review_id BIGINT REFERENCES merge_request_reviews(id) ON DELETE SET NULL
);

CREATE INDEX idx_merge_request_threads_mr ON merge_request_threads (merge_request_id, id);

CREATE INDEX idx_merge_request_threads_position
    ON merge_request_threads (merge_request_id, file_path, new_line);

CREATE INDEX idx_merge_request_threads_unresolved
    ON merge_request_threads (merge_request_id) WHERE resolved = FALSE;

CREATE TABLE merge_request_comments (
    id BIGINT PRIMARY KEY,
    thread_id BIGINT NOT NULL REFERENCES merge_request_threads(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_merge_request_comments_thread ON merge_request_comments (thread_id, id);

CREATE TABLE merge_request_events (
    id BIGINT PRIMARY KEY,
    merge_request_id BIGINT NOT NULL REFERENCES merge_requests(id) ON DELETE CASCADE,
    actor_id BIGINT NOT NULL REFERENCES users(id),
    subject_user_id BIGINT REFERENCES users(id),
    kind TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    commit_id BIGINT REFERENCES commits(id),
    commit_hash TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_merge_request_events_mr ON merge_request_events (merge_request_id, id);

CREATE TABLE file_locks (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    branch_id BIGINT REFERENCES branches(id),
    path TEXT NOT NULL,
    held_by BIGINT NOT NULL REFERENCES users(id),
    merge_request_id BIGINT REFERENCES merge_requests(id),
    acquired_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_file_locks_global ON file_locks (project_id, path) WHERE branch_id IS NULL;

CREATE UNIQUE INDEX idx_file_locks_scoped ON file_locks (project_id, branch_id, path) WHERE branch_id IS NOT NULL;

CREATE INDEX idx_file_locks_project ON file_locks (project_id);

CREATE INDEX idx_file_locks_branch ON file_locks (branch_id);

CREATE TABLE webhooks (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL DEFAULT '',
    url TEXT NOT NULL,
    secret TEXT NOT NULL,
    events TEXT NOT NULL,
    path_prefix TEXT NOT NULL DEFAULT '',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    insecure_tls BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_webhooks_project ON webhooks (project_id, id);

CREATE TABLE webhook_deliveries (
    id BIGINT PRIMARY KEY,
    webhook_id BIGINT NOT NULL REFERENCES webhooks(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    payload BYTEA NOT NULL,
    state TEXT NOT NULL DEFAULT 'pending',
    attempt BIGINT NOT NULL DEFAULT 0,
    response_status BIGINT,
    last_error TEXT NOT NULL DEFAULT '',
    next_retry_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (state IN ('pending', 'delivered', 'failed'))
);

CREATE INDEX idx_webhook_deliveries_webhook ON webhook_deliveries (webhook_id, id);

CREATE INDEX idx_webhook_deliveries_retry
    ON webhook_deliveries (state, next_retry_at) WHERE next_retry_at IS NOT NULL;

CREATE TABLE tags (
    id BIGINT PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    key TEXT NOT NULL,
    commit_id BIGINT NOT NULL REFERENCES commits(id),
    message TEXT NOT NULL DEFAULT '',
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_tags_project_key ON tags (project_id, key);

CREATE INDEX idx_tags_project_created_id ON tags (project_id, created_at DESC, id DESC);

INSERT INTO users (id, name, email, password, is_super_admin) VALUES (1, 'Super Admin', 'nipa', '$2a$10$ErgrBnd6ahfz6eZkVzfnlu6dcE4T0HUcxvAjwmI0ItFsMReHVCdYO', TRUE);
INSERT INTO organizations (id, slug, name, created_by_user_id) VALUES (1, 'default', 'Default Organization', 1);
INSERT INTO projects (id, org_id, slug, name) VALUES (1, 1, 'default', 'Default Project');
INSERT INTO org_members (org_id, user_id, role) VALUES (1, 1, 'owner');
INSERT INTO branches (id, project_id, name, key, is_default) VALUES (1, 1, 'main', 'main', TRUE);
