// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: localrepo.sql

package localrepo

import (
	"context"
)

const chunkUpsert = `-- name: ChunkUpsert :one
INSERT INTO chunks (hash, size_bytes)
VALUES (?1, ?2)
ON CONFLICT(hash) DO UPDATE SET hash = excluded.hash
RETURNING id
`

type ChunkUpsertParams struct {
	Hash      []byte `json:"hash"`
	SizeBytes int64  `json:"size_bytes"`
}

func (q *Queries) ChunkUpsert(ctx context.Context, arg ChunkUpsertParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, chunkUpsert, arg.Hash, arg.SizeBytes)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const fileChunkInsert = `-- name: FileChunkInsert :exec
INSERT INTO file_chunks (file_path, chunk_id, chunk_index)
VALUES (?1, ?2, ?3)
ON CONFLICT(file_path, chunk_index) DO UPDATE SET chunk_id = excluded.chunk_id
`

type FileChunkInsertParams struct {
	FilePath   string `json:"file_path"`
	ChunkID    int64  `json:"chunk_id"`
	ChunkIndex int64  `json:"chunk_index"`
}

func (q *Queries) FileChunkInsert(ctx context.Context, arg FileChunkInsertParams) error {
	_, err := q.db.ExecContext(ctx, fileChunkInsert, arg.FilePath, arg.ChunkID, arg.ChunkIndex)
	return err
}

const fileUpsert = `-- name: FileUpsert :exec
INSERT INTO files (path, tree_path, hash, size_bytes, mode, is_binary, snapshot_id)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT(path) DO UPDATE SET
    tree_path = excluded.tree_path,
    hash = excluded.hash,
    size_bytes = excluded.size_bytes,
    mode = excluded.mode,
    is_binary = excluded.is_binary,
    snapshot_id = excluded.snapshot_id
`

type FileUpsertParams struct {
	Path       string `json:"path"`
	TreePath   string `json:"tree_path"`
	Hash       []byte `json:"hash"`
	SizeBytes  int64  `json:"size_bytes"`
	Mode       int64  `json:"mode"`
	IsBinary   bool   `json:"is_binary"`
	SnapshotID string `json:"snapshot_id"`
}

func (q *Queries) FileUpsert(ctx context.Context, arg FileUpsertParams) error {
	_, err := q.db.ExecContext(ctx, fileUpsert,
		arg.Path,
		arg.TreePath,
		arg.Hash,
		arg.SizeBytes,
		arg.Mode,
		arg.IsBinary,
		arg.SnapshotID,
	)
	return err
}

const metaGet = `-- name: MetaGet :one
SELECT value
FROM meta
WHERE key = ?1
LIMIT 1
`

func (q *Queries) MetaGet(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, metaGet, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const metaSet = `-- name: MetaSet :exec
INSERT INTO meta (key, value)
VALUES (?1, ?2)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type MetaSetParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) MetaSet(ctx context.Context, arg MetaSetParams) error {
	_, err := q.db.ExecContext(ctx, metaSet, arg.Key, arg.Value)
	return err
}

const snapshotFileChunkList = `-- name: SnapshotFileChunkList :many
SELECT file_chunks.file_path, chunks.hash, chunks.size_bytes
FROM file_chunks
JOIN chunks ON chunks.id = file_chunks.chunk_id
JOIN files ON files.path = file_chunks.file_path
WHERE files.snapshot_id = ?1
ORDER BY file_chunks.file_path, file_chunks.chunk_index
`

type SnapshotFileChunkListRow struct {
	FilePath  string `json:"file_path"`
	Hash      []byte `json:"hash"`
	SizeBytes int64  `json:"size_bytes"`
}

func (q *Queries) SnapshotFileChunkList(ctx context.Context, snapshotID string) ([]SnapshotFileChunkListRow, error) {
	rows, err := q.db.QueryContext(ctx, snapshotFileChunkList, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotFileChunkListRow
	for rows.Next() {
		var i SnapshotFileChunkListRow
		if err := rows.Scan(&i.FilePath, &i.Hash, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotFileList = `-- name: SnapshotFileList :many
SELECT path, hash, size_bytes, mode, is_binary
FROM files
WHERE snapshot_id = ?1
ORDER BY path
`

type SnapshotFileListRow struct {
	Path      string `json:"path"`
	Hash      []byte `json:"hash"`
	SizeBytes int64  `json:"size_bytes"`
	Mode      int64  `json:"mode"`
	IsBinary  bool   `json:"is_binary"`
}

func (q *Queries) SnapshotFileList(ctx context.Context, snapshotID string) ([]SnapshotFileListRow, error) {
	rows, err := q.db.QueryContext(ctx, snapshotFileList, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotFileListRow
	for rows.Next() {
		var i SnapshotFileListRow
		if err := rows.Scan(
			&i.Path,
			&i.Hash,
			&i.SizeBytes,
			&i.Mode,
			&i.IsBinary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stagedFileDelete = `-- name: StagedFileDelete :exec
DELETE FROM staged_files
WHERE path = ?1
`

func (q *Queries) StagedFileDelete(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, stagedFileDelete, path)
	return err
}

const stagedFileInsert = `-- name: StagedFileInsert :exec
INSERT INTO staged_files (path)
VALUES (?1)
ON CONFLICT(path) DO NOTHING
`

func (q *Queries) StagedFileInsert(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, stagedFileInsert, path)
	return err
}

const stagedFileList = `-- name: StagedFileList :many
SELECT path
FROM staged_files
ORDER BY path
`

func (q *Queries) StagedFileList(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, stagedFileList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staleFileDelete = `-- name: StaleFileDelete :exec
DELETE FROM files
WHERE snapshot_id <> ?1
`

func (q *Queries) StaleFileDelete(ctx context.Context, snapshotID string) error {
	_, err := q.db.ExecContext(ctx, staleFileDelete, snapshotID)
	return err
}

const staleTreeNodeDelete = `-- name: StaleTreeNodeDelete :exec
DELETE FROM tree_nodes
WHERE snapshot_id <> ?1
`

func (q *Queries) StaleTreeNodeDelete(ctx context.Context, snapshotID string) error {
	_, err := q.db.ExecContext(ctx, staleTreeNodeDelete, snapshotID)
	return err
}

const treeNodeUpsert = `-- name: TreeNodeUpsert :exec
INSERT INTO tree_nodes (path, parent_path, hash, mode, snapshot_id)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(path) DO UPDATE SET
    parent_path = excluded.parent_path,
    hash = excluded.hash,
    mode = excluded.mode,
    snapshot_id = excluded.snapshot_id
`

type TreeNodeUpsertParams struct {
	Path       string `json:"path"`
	ParentPath string `json:"parent_path"`
	Hash       []byte `json:"hash"`
	Mode       int64  `json:"mode"`
	SnapshotID string `json:"snapshot_id"`
}

func (q *Queries) TreeNodeUpsert(ctx context.Context, arg TreeNodeUpsertParams) error {
	_, err := q.db.ExecContext(ctx, treeNodeUpsert,
		arg.Path,
		arg.ParentPath,
		arg.Hash,
		arg.Mode,
		arg.SnapshotID,
	)
	return err
}
