// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: localrepo.sql

package localrepo

import (
	"context"
)

const fileUpsert = `-- name: FileUpsert :exec
INSERT INTO files (path, tree_path, hash, size_bytes, mode, is_binary, encoding, chunks, snapshot_id)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
ON CONFLICT(path) DO UPDATE SET
    tree_path = excluded.tree_path,
    hash = excluded.hash,
    size_bytes = excluded.size_bytes,
    mode = excluded.mode,
    is_binary = excluded.is_binary,
    encoding = excluded.encoding,
    chunks = excluded.chunks,
    snapshot_id = excluded.snapshot_id
`

type FileUpsertParams struct {
	Path       string `json:"path"`
	TreePath   string `json:"tree_path"`
	Hash       []byte `json:"hash"`
	SizeBytes  int64  `json:"size_bytes"`
	Mode       int64  `json:"mode"`
	IsBinary   bool   `json:"is_binary"`
	Encoding   string `json:"encoding"`
	Chunks     []byte `json:"chunks"`
	SnapshotID string `json:"snapshot_id"`
}

func (q *Queries) FileUpsert(ctx context.Context, arg FileUpsertParams) error {
	_, err := q.db.ExecContext(ctx, fileUpsert,
		arg.Path,
		arg.TreePath,
		arg.Hash,
		arg.SizeBytes,
		arg.Mode,
		arg.IsBinary,
		arg.Encoding,
		arg.Chunks,
		arg.SnapshotID,
	)
	return err
}

const metaDelete = `-- name: MetaDelete :exec
DELETE FROM meta
WHERE key = ?1
`

func (q *Queries) MetaDelete(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, metaDelete, key)
	return err
}

const metaGet = `-- name: MetaGet :one
SELECT value
FROM meta
WHERE key = ?1
LIMIT 1
`

func (q *Queries) MetaGet(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, metaGet, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const metaSet = `-- name: MetaSet :exec
INSERT INTO meta (key, value)
VALUES (?1, ?2)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type MetaSetParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) MetaSet(ctx context.Context, arg MetaSetParams) error {
	_, err := q.db.ExecContext(ctx, metaSet, arg.Key, arg.Value)
	return err
}

const snapshotFileList = `-- name: SnapshotFileList :many
SELECT path, hash, size_bytes, mode, is_binary, encoding, chunks
FROM files
WHERE snapshot_id = ?1
ORDER BY path
`

type SnapshotFileListRow struct {
	Path      string `json:"path"`
	Hash      []byte `json:"hash"`
	SizeBytes int64  `json:"size_bytes"`
	Mode      int64  `json:"mode"`
	IsBinary  bool   `json:"is_binary"`
	Encoding  string `json:"encoding"`
	Chunks    []byte `json:"chunks"`
}

func (q *Queries) SnapshotFileList(ctx context.Context, snapshotID string) ([]SnapshotFileListRow, error) {
	rows, err := q.db.QueryContext(ctx, snapshotFileList, snapshotID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotFileListRow
	for rows.Next() {
		var i SnapshotFileListRow
		if err := rows.Scan(
			&i.Path,
			&i.Hash,
			&i.SizeBytes,
			&i.Mode,
			&i.IsBinary,
			&i.Encoding,
			&i.Chunks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stagedFileDelete = `-- name: StagedFileDelete :exec
DELETE FROM staged_files
WHERE path = ?1
`

func (q *Queries) StagedFileDelete(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, stagedFileDelete, path)
	return err
}

const stagedFileDeleteAll = `-- name: StagedFileDeleteAll :exec
DELETE FROM staged_files
WHERE path IS NOT NULL
`

func (q *Queries) StagedFileDeleteAll(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, stagedFileDeleteAll)
	return err
}

const stagedFileInsert = `-- name: StagedFileInsert :exec
INSERT INTO staged_files (path)
VALUES (?1)
ON CONFLICT(path) DO NOTHING
`

func (q *Queries) StagedFileInsert(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, stagedFileInsert, path)
	return err
}

const stagedFileList = `-- name: StagedFileList :many
SELECT path
FROM staged_files
ORDER BY path
`

func (q *Queries) StagedFileList(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, stagedFileList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var path string
		if err := rows.Scan(&path); err != nil {
			return nil, err
		}
		items = append(items, path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staleFileDelete = `-- name: StaleFileDelete :exec
DELETE FROM files
WHERE snapshot_id <> ?1
`

func (q *Queries) StaleFileDelete(ctx context.Context, snapshotID string) error {
	_, err := q.db.ExecContext(ctx, staleFileDelete, snapshotID)
	return err
}

const staleTreeNodeDelete = `-- name: StaleTreeNodeDelete :exec
DELETE FROM tree_nodes
WHERE snapshot_id <> ?1
`

func (q *Queries) StaleTreeNodeDelete(ctx context.Context, snapshotID string) error {
	_, err := q.db.ExecContext(ctx, staleTreeNodeDelete, snapshotID)
	return err
}

const statCacheList = `-- name: StatCacheList :many
SELECT path, size_bytes, mtime_ns, mode, hash, cached_at
FROM stat_cache
ORDER BY path
`

func (q *Queries) StatCacheList(ctx context.Context) ([]StatCache, error) {
	rows, err := q.db.QueryContext(ctx, statCacheList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatCache
	for rows.Next() {
		var i StatCache
		if err := rows.Scan(
			&i.Path,
			&i.SizeBytes,
			&i.MtimeNs,
			&i.Mode,
			&i.Hash,
			&i.CachedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statCacheSweep = `-- name: StatCacheSweep :exec
DELETE FROM stat_cache
WHERE path NOT IN (SELECT ltrim(path, '/') FROM files)
`

func (q *Queries) StatCacheSweep(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, statCacheSweep)
	return err
}

const statCacheUpsert = `-- name: StatCacheUpsert :exec
INSERT INTO stat_cache (path, size_bytes, mtime_ns, mode, hash, cached_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT(path) DO UPDATE SET
    size_bytes = excluded.size_bytes,
    mtime_ns = excluded.mtime_ns,
    mode = excluded.mode,
    hash = excluded.hash,
    cached_at = excluded.cached_at
`

type StatCacheUpsertParams struct {
	Path      string `json:"path"`
	SizeBytes int64  `json:"size_bytes"`
	MtimeNs   int64  `json:"mtime_ns"`
	Mode      int64  `json:"mode"`
	Hash      []byte `json:"hash"`
	CachedAt  int64  `json:"cached_at"`
}

func (q *Queries) StatCacheUpsert(ctx context.Context, arg StatCacheUpsertParams) error {
	_, err := q.db.ExecContext(ctx, statCacheUpsert,
		arg.Path,
		arg.SizeBytes,
		arg.MtimeNs,
		arg.Mode,
		arg.Hash,
		arg.CachedAt,
	)
	return err
}

const treeNodeUpsert = `-- name: TreeNodeUpsert :exec
INSERT INTO tree_nodes (path, parent_path, hash, mode, snapshot_id)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(path) DO UPDATE SET
    parent_path = excluded.parent_path,
    hash = excluded.hash,
    mode = excluded.mode,
    snapshot_id = excluded.snapshot_id
`

type TreeNodeUpsertParams struct {
	Path       string `json:"path"`
	ParentPath string `json:"parent_path"`
	Hash       []byte `json:"hash"`
	Mode       int64  `json:"mode"`
	SnapshotID string `json:"snapshot_id"`
}

func (q *Queries) TreeNodeUpsert(ctx context.Context, arg TreeNodeUpsertParams) error {
	_, err := q.db.ExecContext(ctx, treeNodeUpsert,
		arg.Path,
		arg.ParentPath,
		arg.Hash,
		arg.Mode,
		arg.SnapshotID,
	)
	return err
}
