// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package localrepo

import (
	"database/sql"
)

type Chunk struct {
	ID        int64        `json:"id"`
	Hash      []byte       `json:"hash"`
	SizeBytes int64        `json:"size_bytes"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type File struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	Mode      int64         `json:"mode"`
	TreeID    sql.NullInt64 `json:"tree_id"`
	Hash      []byte        `json:"hash"`
	SizeBytes int64         `json:"size_bytes"`
	IsBinary  bool          `json:"is_binary"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type FileChunk struct {
	FileID     int64 `json:"file_id"`
	ChunkID    int64 `json:"chunk_id"`
	ChunkIndex int64 `json:"chunk_index"`
}

type Meta struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type TreeNode struct {
	ID           int64         `json:"id"`
	Hash         []byte        `json:"hash"`
	Name         string        `json:"name"`
	Mode         int64         `json:"mode"`
	ParentTreeID sql.NullInt64 `json:"parent_tree_id"`
}
