// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package localrepo

import (
	"context"
)

type Querier interface {
	ChunkClear(ctx context.Context) error
	ChunkUpsert(ctx context.Context, arg ChunkUpsertParams) (int64, error)
	FileChunkClear(ctx context.Context) error
	FileChunkInsert(ctx context.Context, arg FileChunkInsertParams) error
	FileClear(ctx context.Context) error
	FileInsert(ctx context.Context, arg FileInsertParams) (int64, error)
	MetaGet(ctx context.Context, key string) (string, error)
	MetaSet(ctx context.Context, arg MetaSetParams) error
	TreeInsert(ctx context.Context, arg TreeInsertParams) (int64, error)
	TreeNodeClear(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
