// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: internal/grpc/proto/server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileMode int32

const (
	FileMode_FILE_MODE_UNSPECIFIED FileMode = 0
	FileMode_FILE_MODE_READ_ONLY   FileMode = 1
	FileMode_FILE_MODE_READ_WRITE  FileMode = 2
	FileMode_FILE_MODE_EXECUTABLE  FileMode = 3
)

// Enum value maps for FileMode.
var (
	FileMode_name = map[int32]string{
		0: "FILE_MODE_UNSPECIFIED",
		1: "FILE_MODE_READ_ONLY",
		2: "FILE_MODE_READ_WRITE",
		3: "FILE_MODE_EXECUTABLE",
	}
	FileMode_value = map[string]int32{
		"FILE_MODE_UNSPECIFIED": 0,
		"FILE_MODE_READ_ONLY":   1,
		"FILE_MODE_READ_WRITE":  2,
		"FILE_MODE_EXECUTABLE":  3,
	}
)

func (x FileMode) Enum() *FileMode {
	p := new(FileMode)
	*p = x
	return p
}

func (x FileMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_server_proto_enumTypes[0].Descriptor()
}

func (FileMode) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_server_proto_enumTypes[0]
}

func (x FileMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileMode.Descriptor instead.
func (FileMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{0}
}

type ProjectContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectContext) Reset() {
	*x = ProjectContext{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectContext) ProtoMessage() {}

func (x *ProjectContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectContext.ProtoReflect.Descriptor instead.
func (*ProjectContext) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectContext) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ProjectContext) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type FileNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          FileMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=greet.FileMode" json:"mode,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IsBinary      bool                   `protobuf:"varint,4,opt,name=is_binary,json=isBinary,proto3" json:"is_binary,omitempty"`
	ChunkHashes   []string               `protobuf:"bytes,5,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileNode) Reset() {
	*x = FileNode{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileNode) ProtoMessage() {}

func (x *FileNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileNode.ProtoReflect.Descriptor instead.
func (*FileNode) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *FileNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileNode) GetMode() FileMode {
	if x != nil {
		return x.Mode
	}
	return FileMode_FILE_MODE_UNSPECIFIED
}

func (x *FileNode) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileNode) GetIsBinary() bool {
	if x != nil {
		return x.IsBinary
	}
	return false
}

func (x *FileNode) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type TreeManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeHash      string                 `protobuf:"bytes,1,opt,name=tree_hash,json=treeHash,proto3" json:"tree_hash,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                         // Subdirectory path, e.g., "assets/shaders"
	SubTrees      []*TreeManifest        `protobuf:"bytes,3,rep,name=sub_trees,json=subTrees,proto3" json:"sub_trees,omitempty"` // Child directory trees
	Files         []*FileNode            `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeManifest) Reset() {
	*x = TreeManifest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeManifest) ProtoMessage() {}

func (x *TreeManifest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeManifest.ProtoReflect.Descriptor instead.
func (*TreeManifest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *TreeManifest) GetTreeHash() string {
	if x != nil {
		return x.TreeHash
	}
	return ""
}

func (x *TreeManifest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TreeManifest) GetSubTrees() []*TreeManifest {
	if x != nil {
		return x.SubTrees
	}
	return nil
}

func (x *TreeManifest) GetFiles() []*FileNode {
	if x != nil {
		return x.Files
	}
	return nil
}

type GetTreeManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	TreeHash      *string                `protobuf:"bytes,4,opt,name=tree_hash,json=treeHash,proto3,oneof" json:"tree_hash,omitempty"`
	Recursive     bool                   `protobuf:"varint,5,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeManifestRequest) Reset() {
	*x = GetTreeManifestRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeManifestRequest) ProtoMessage() {}

func (x *GetTreeManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeManifestRequest.ProtoReflect.Descriptor instead.
func (*GetTreeManifestRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetTreeManifestRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetTreeManifestRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetTreeManifestRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetTreeManifestRequest) GetTreeHash() string {
	if x != nil && x.TreeHash != nil {
		return *x.TreeHash
	}
	return ""
}

func (x *GetTreeManifestRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type GetTreeManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	RootTree      *TreeManifest          `protobuf:"bytes,2,opt,name=root_tree,json=rootTree,proto3" json:"root_tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeManifestResponse) Reset() {
	*x = GetTreeManifestResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeManifestResponse) ProtoMessage() {}

func (x *GetTreeManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeManifestResponse.ProtoReflect.Descriptor instead.
func (*GetTreeManifestResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetTreeManifestResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetTreeManifestResponse) GetRootTree() *TreeManifest {
	if x != nil {
		return x.RootTree
	}
	return nil
}

type PushFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // repository-relative file path, e.g. "assets/logo.png"
	Mode          FileMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=greet.FileMode" json:"mode,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IsBinary      bool                   `protobuf:"varint,4,opt,name=is_binary,json=isBinary,proto3" json:"is_binary,omitempty"`
	FileHash      string                 `protobuf:"bytes,5,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	ChunkHashes   []string               `protobuf:"bytes,6,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFile) Reset() {
	*x = PushFile{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFile) ProtoMessage() {}

func (x *PushFile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFile.ProtoReflect.Descriptor instead.
func (*PushFile) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{5}
}

func (x *PushFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PushFile) GetMode() FileMode {
	if x != nil {
		return x.Mode
	}
	return FileMode_FILE_MODE_UNSPECIFIED
}

func (x *PushFile) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PushFile) GetIsBinary() bool {
	if x != nil {
		return x.IsBinary
	}
	return false
}

func (x *PushFile) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *PushFile) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type ChunkUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // hex-encoded BLAKE3 hash of data
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadRequest) Reset() {
	*x = ChunkUploadRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadRequest) ProtoMessage() {}

func (x *ChunkUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadRequest.ProtoReflect.Descriptor instead.
func (*ChunkUploadRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkUploadRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ChunkUploadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uploaded      int32                  `protobuf:"varint,1,opt,name=uploaded,proto3" json:"uploaded,omitempty"`
	Skipped       int32                  `protobuf:"varint,2,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunksResponse) Reset() {
	*x = UploadChunksResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunksResponse) ProtoMessage() {}

func (x *UploadChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunksResponse.ProtoReflect.Descriptor instead.
func (*UploadChunksResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{7}
}

func (x *UploadChunksResponse) GetUploaded() int32 {
	if x != nil {
		return x.Uploaded
	}
	return 0
}

func (x *UploadChunksResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

type DownloadChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // hex-encoded BLAKE3 hash of data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunksRequest) Reset() {
	*x = DownloadChunksRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunksRequest) ProtoMessage() {}

func (x *DownloadChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunksRequest.ProtoReflect.Descriptor instead.
func (*DownloadChunksRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadChunksRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type DownloadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // hex-encoded BLAKE3 hash of data
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunk) Reset() {
	*x = DownloadChunk{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunk) ProtoMessage() {}

func (x *DownloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunk.ProtoReflect.Descriptor instead.
func (*DownloadChunk) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadChunk) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DownloadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	BaseTreeHash  string                 `protobuf:"bytes,3,opt,name=base_tree_hash,json=baseTreeHash,proto3" json:"base_tree_hash,omitempty"` // tree hash the client is based on, empty for branches without commits
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Files         []*PushFile            `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	RemovedFiles  []string               `protobuf:"bytes,6,rep,name=removed_files,json=removedFiles,proto3" json:"removed_files,omitempty"` // paths removed relative to the base tree
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{10}
}

func (x *PushRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PushRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *PushRequest) GetBaseTreeHash() string {
	if x != nil {
		return x.BaseTreeHash
	}
	return ""
}

func (x *PushRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PushRequest) GetFiles() []*PushFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *PushRequest) GetRemovedFiles() []string {
	if x != nil {
		return x.RemovedFiles
	}
	return nil
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitId      string                 `protobuf:"bytes,1,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	TreeHash      string                 `protobuf:"bytes,3,opt,name=tree_hash,json=treeHash,proto3" json:"tree_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{11}
}

func (x *PushResponse) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *PushResponse) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *PushResponse) GetTreeHash() string {
	if x != nil {
		return x.TreeHash
	}
	return ""
}

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CommitId      *string                `protobuf:"bytes,5,opt,name=commit_id,json=commitId,proto3,oneof" json:"commit_id,omitempty"`
	IsProtected   bool                   `protobuf:"varint,6,opt,name=is_protected,json=isProtected,proto3" json:"is_protected,omitempty"`
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{12}
}

func (x *Branch) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Branch) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Branch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetCommitId() string {
	if x != nil && x.CommitId != nil {
		return *x.CommitId
	}
	return ""
}

func (x *Branch) GetIsProtected() bool {
	if x != nil {
		return x.IsProtected
	}
	return false
}

func (x *Branch) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type GetListBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	LastUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated_at,json=lastUpdatedAt,proto3,oneof" json:"last_updated_at,omitempty"`
	LastId        *string                `protobuf:"bytes,4,opt,name=last_id,json=lastId,proto3,oneof" json:"last_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListBranchRequest) Reset() {
	*x = GetListBranchRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBranchRequest) ProtoMessage() {}

func (x *GetListBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListBranchRequest.ProtoReflect.Descriptor instead.
func (*GetListBranchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{13}
}

func (x *GetListBranchRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetListBranchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListBranchRequest) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

func (x *GetListBranchRequest) GetLastId() string {
	if x != nil && x.LastId != nil {
		return *x.LastId
	}
	return ""
}

type GetListBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*Branch              `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListBranchResponse) Reset() {
	*x = GetListBranchResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBranchResponse) ProtoMessage() {}

func (x *GetListBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListBranchResponse.ProtoReflect.Descriptor instead.
func (*GetListBranchResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{14}
}

func (x *GetListBranchResponse) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

type GetBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	BranchId      string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchRequest) Reset() {
	*x = GetBranchRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchRequest) ProtoMessage() {}

func (x *GetBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchRequest.ProtoReflect.Descriptor instead.
func (*GetBranchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{15}
}

func (x *GetBranchRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetBranchRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

type GetDefaultBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultBranchRequest) Reset() {
	*x = GetDefaultBranchRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultBranchRequest) ProtoMessage() {}

func (x *GetDefaultBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultBranchRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultBranchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{16}
}

func (x *GetDefaultBranchRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type GetBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchResponse) Reset() {
	*x = GetBranchResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchResponse) ProtoMessage() {}

func (x *GetBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchResponse.ProtoReflect.Descriptor instead.
func (*GetBranchResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{17}
}

func (x *GetBranchResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

type CreateBranchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FromBranch     string                 `protobuf:"bytes,3,opt,name=from_branch,json=fromBranch,proto3" json:"from_branch,omitempty"`               // branch to fork from; empty to fork from the default branch
	FromCommitId   string                 `protobuf:"bytes,4,opt,name=from_commit_id,json=fromCommitId,proto3" json:"from_commit_id,omitempty"`       // exact commit to fork from (base36 snow ID); takes precedence over from_commit_hash and from_branch
	FromCommitHash string                 `protobuf:"bytes,5,opt,name=from_commit_hash,json=fromCommitHash,proto3" json:"from_commit_hash,omitempty"` // exact commit to fork from (hex content hash); takes precedence over from_branch
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBranchRequest) Reset() {
	*x = CreateBranchRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchRequest) ProtoMessage() {}

func (x *CreateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchRequest.ProtoReflect.Descriptor instead.
func (*CreateBranchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{18}
}

func (x *CreateBranchRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateBranchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBranchRequest) GetFromBranch() string {
	if x != nil {
		return x.FromBranch
	}
	return ""
}

func (x *CreateBranchRequest) GetFromCommitId() string {
	if x != nil {
		return x.FromCommitId
	}
	return ""
}

func (x *CreateBranchRequest) GetFromCommitHash() string {
	if x != nil {
		return x.FromCommitHash
	}
	return ""
}

type CreateBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchResponse) Reset() {
	*x = CreateBranchResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchResponse) ProtoMessage() {}

func (x *CreateBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchResponse.ProtoReflect.Descriptor instead.
func (*CreateBranchResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{19}
}

func (x *CreateBranchResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

type LoginUsernamePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUsernamePasswordRequest) Reset() {
	*x = LoginUsernamePasswordRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUsernamePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUsernamePasswordRequest) ProtoMessage() {}

func (x *LoginUsernamePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUsernamePasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginUsernamePasswordRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{20}
}

func (x *LoginUsernamePasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginUsernamePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginWithRefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithRefreshRequest) Reset() {
	*x = LoginWithRefreshRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithRefreshRequest) ProtoMessage() {}

func (x *LoginWithRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithRefreshRequest.ProtoReflect.Descriptor instead.
func (*LoginWithRefreshRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{21}
}

func (x *LoginWithRefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{22}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_internal_grpc_proto_server_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_server_proto_rawDesc = "" +
	"\n" +
	" internal/grpc/proto/server.proto\x12\x05greet\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\x0eProjectContext\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\"\xa2\x01\n" +
	"\bFileNode\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x0f.greet.FileModeR\x04mode\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tis_binary\x18\x04 \x01(\bR\bisBinary\x12!\n" +
	"\fchunk_hashes\x18\x05 \x03(\tR\vchunkHashes\"\x98\x01\n" +
	"\fTreeManifest\x12\x1b\n" +
	"\ttree_hash\x18\x01 \x01(\tR\btreeHash\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x120\n" +
	"\tsub_trees\x18\x03 \x03(\v2\x13.greet.TreeManifestR\bsubTrees\x12%\n" +
	"\x05files\x18\x04 \x03(\v2\x0f.greet.FileNodeR\x05files\"\xc3\x01\n" +
	"\x16GetTreeManifestRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12 \n" +
	"\ttree_hash\x18\x04 \x01(\tH\x00R\btreeHash\x88\x01\x01\x12\x1c\n" +
	"\trecursive\x18\x05 \x01(\bR\trecursiveB\f\n" +
	"\n" +
	"_tree_hash\"c\n" +
	"\x17GetTreeManifestResponse\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x120\n" +
	"\troot_tree\x18\x02 \x01(\v2\x13.greet.TreeManifestR\brootTree\"\xbf\x01\n" +
	"\bPushFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x0f.greet.FileModeR\x04mode\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tis_binary\x18\x04 \x01(\bR\bisBinary\x12\x1b\n" +
	"\tfile_hash\x18\x05 \x01(\tR\bfileHash\x12!\n" +
	"\fchunk_hashes\x18\x06 \x03(\tR\vchunkHashes\"<\n" +
	"\x12ChunkUploadRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"L\n" +
	"\x14UploadChunksResponse\x12\x1a\n" +
	"\buploaded\x18\x01 \x01(\x05R\buploaded\x12\x18\n" +
	"\askipped\x18\x02 \x01(\x05R\askipped\"+\n" +
	"\x15DownloadChunksRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"7\n" +
	"\rDownloadChunk\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xe2\x01\n" +
	"\vPushRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12$\n" +
	"\x0ebase_tree_hash\x18\x03 \x01(\tR\fbaseTreeHash\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12%\n" +
	"\x05files\x18\x05 \x03(\v2\x0f.greet.PushFileR\x05files\x12#\n" +
	"\rremoved_files\x18\x06 \x03(\tR\fremovedFiles\"i\n" +
	"\fPushResponse\x12\x1b\n" +
	"\tcommit_id\x18\x01 \x01(\tR\bcommitId\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12\x1b\n" +
	"\ttree_hash\x18\x03 \x01(\tR\btreeHash\"\x94\x02\n" +
	"\x06Branch\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\tcommit_id\x18\x05 \x01(\tH\x00R\bcommitId\x88\x01\x01\x12!\n" +
	"\fis_protected\x18\x06 \x01(\bR\visProtected\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefaultB\f\n" +
	"\n" +
	"_commit_id\"\xe4\x01\n" +
	"\x14GetListBranchRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12G\n" +
	"\x0flast_updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rlastUpdatedAt\x88\x01\x01\x12\x1c\n" +
	"\alast_id\x18\x04 \x01(\tH\x01R\x06lastId\x88\x01\x01B\x12\n" +
	"\x10_last_updated_atB\n" +
	"\n" +
	"\b_last_id\"B\n" +
	"\x15GetListBranchResponse\x12)\n" +
	"\bbranches\x18\x01 \x03(\v2\r.greet.BranchR\bbranches\"`\n" +
	"\x10GetBranchRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\"J\n" +
	"\x17GetDefaultBranchRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\":\n" +
	"\x11GetBranchResponse\x12%\n" +
	"\x06branch\x18\x01 \x01(\v2\r.greet.BranchR\x06branch\"\xcb\x01\n" +
	"\x13CreateBranchRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vfrom_branch\x18\x03 \x01(\tR\n" +
	"fromBranch\x12$\n" +
	"\x0efrom_commit_id\x18\x04 \x01(\tR\ffromCommitId\x12(\n" +
	"\x10from_commit_hash\x18\x05 \x01(\tR\x0efromCommitHash\"=\n" +
	"\x14CreateBranchResponse\x12%\n" +
	"\x06branch\x18\x01 \x01(\v2\r.greet.BranchR\x06branch\"V\n" +
	"\x1cLoginUsernamePasswordRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\x17LoginWithRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"v\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn*r\n" +
	"\bFileMode\x12\x19\n" +
	"\x15FILE_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FILE_MODE_READ_ONLY\x10\x01\x12\x18\n" +
	"\x14FILE_MODE_READ_WRITE\x10\x02\x12\x18\n" +
	"\x14FILE_MODE_EXECUTABLE\x10\x032\xee\x05\n" +
	"\vNipaService\x12V\n" +
	"\x19LoginWithUsernamePassword\x12#.greet.LoginUsernamePasswordRequest\x1a\x14.greet.LoginResponse\x12M\n" +
	"\x15LoginWithRefreshToken\x12\x1e.greet.LoginWithRefreshRequest\x1a\x14.greet.LoginResponse\x12J\n" +
	"\rGetListBranch\x12\x1b.greet.GetListBranchRequest\x1a\x1c.greet.GetListBranchResponse\x12>\n" +
	"\tGetBranch\x12\x17.greet.GetBranchRequest\x1a\x18.greet.GetBranchResponse\x12L\n" +
	"\x10GetDefaultBranch\x12\x1e.greet.GetDefaultBranchRequest\x1a\x18.greet.GetBranchResponse\x12G\n" +
	"\fCreateBranch\x12\x1a.greet.CreateBranchRequest\x1a\x1b.greet.CreateBranchResponse\x12P\n" +
	"\x0fGetTreeManifest\x12\x1d.greet.GetTreeManifestRequest\x1a\x1e.greet.GetTreeManifestResponse\x12/\n" +
	"\x04Push\x12\x12.greet.PushRequest\x1a\x13.greet.PushResponse\x12H\n" +
	"\fUploadChunks\x12\x19.greet.ChunkUploadRequest\x1a\x1b.greet.UploadChunksResponse(\x01\x12H\n" +
	"\x0eDownloadChunks\x12\x1c.greet.DownloadChunksRequest\x1a\x14.greet.DownloadChunk(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_internal_grpc_proto_server_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_server_proto_rawDescData []byte
)

func file_internal_grpc_proto_server_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_server_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_server_proto_rawDesc), len(file_internal_grpc_proto_server_proto_rawDesc)))
	})
	return file_internal_grpc_proto_server_proto_rawDescData
}

var file_internal_grpc_proto_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_internal_grpc_proto_server_proto_goTypes = []any{
	(FileMode)(0),                        // 0: greet.FileMode
	(*ProjectContext)(nil),               // 1: greet.ProjectContext
	(*FileNode)(nil),                     // 2: greet.FileNode
	(*TreeManifest)(nil),                 // 3: greet.TreeManifest
	(*GetTreeManifestRequest)(nil),       // 4: greet.GetTreeManifestRequest
	(*GetTreeManifestResponse)(nil),      // 5: greet.GetTreeManifestResponse
	(*PushFile)(nil),                     // 6: greet.PushFile
	(*ChunkUploadRequest)(nil),           // 7: greet.ChunkUploadRequest
	(*UploadChunksResponse)(nil),         // 8: greet.UploadChunksResponse
	(*DownloadChunksRequest)(nil),        // 9: greet.DownloadChunksRequest
	(*DownloadChunk)(nil),                // 10: greet.DownloadChunk
	(*PushRequest)(nil),                  // 11: greet.PushRequest
	(*PushResponse)(nil),                 // 12: greet.PushResponse
	(*Branch)(nil),                       // 13: greet.Branch
	(*GetListBranchRequest)(nil),         // 14: greet.GetListBranchRequest
	(*GetListBranchResponse)(nil),        // 15: greet.GetListBranchResponse
	(*GetBranchRequest)(nil),             // 16: greet.GetBranchRequest
	(*GetDefaultBranchRequest)(nil),      // 17: greet.GetDefaultBranchRequest
	(*GetBranchResponse)(nil),            // 18: greet.GetBranchResponse
	(*CreateBranchRequest)(nil),          // 19: greet.CreateBranchRequest
	(*CreateBranchResponse)(nil),         // 20: greet.CreateBranchResponse
	(*LoginUsernamePasswordRequest)(nil), // 21: greet.LoginUsernamePasswordRequest
	(*LoginWithRefreshRequest)(nil),      // 22: greet.LoginWithRefreshRequest
	(*LoginResponse)(nil),                // 23: greet.LoginResponse
	(*timestamppb.Timestamp)(nil),        // 24: google.protobuf.Timestamp
}
var file_internal_grpc_proto_server_proto_depIdxs = []int32{
	0,  // 0: greet.FileNode.mode:type_name -> greet.FileMode
	3,  // 1: greet.TreeManifest.sub_trees:type_name -> greet.TreeManifest
	2,  // 2: greet.TreeManifest.files:type_name -> greet.FileNode
	1,  // 3: greet.GetTreeManifestRequest.context:type_name -> greet.ProjectContext
	3,  // 4: greet.GetTreeManifestResponse.root_tree:type_name -> greet.TreeManifest
	0,  // 5: greet.PushFile.mode:type_name -> greet.FileMode
	1,  // 6: greet.PushRequest.context:type_name -> greet.ProjectContext
	6,  // 7: greet.PushRequest.files:type_name -> greet.PushFile
	24, // 8: greet.Branch.created_at:type_name -> google.protobuf.Timestamp
	24, // 9: greet.Branch.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 10: greet.GetListBranchRequest.context:type_name -> greet.ProjectContext
	24, // 11: greet.GetListBranchRequest.last_updated_at:type_name -> google.protobuf.Timestamp
	13, // 12: greet.GetListBranchResponse.branches:type_name -> greet.Branch
	1,  // 13: greet.GetBranchRequest.context:type_name -> greet.ProjectContext
	1,  // 14: greet.GetDefaultBranchRequest.context:type_name -> greet.ProjectContext
	13, // 15: greet.GetBranchResponse.branch:type_name -> greet.Branch
	1,  // 16: greet.CreateBranchRequest.context:type_name -> greet.ProjectContext
	13, // 17: greet.CreateBranchResponse.branch:type_name -> greet.Branch
	21, // 18: greet.NipaService.LoginWithUsernamePassword:input_type -> greet.LoginUsernamePasswordRequest
	22, // 19: greet.NipaService.LoginWithRefreshToken:input_type -> greet.LoginWithRefreshRequest
	14, // 20: greet.NipaService.GetListBranch:input_type -> greet.GetListBranchRequest
	16, // 21: greet.NipaService.GetBranch:input_type -> greet.GetBranchRequest
	17, // 22: greet.NipaService.GetDefaultBranch:input_type -> greet.GetDefaultBranchRequest
	19, // 23: greet.NipaService.CreateBranch:input_type -> greet.CreateBranchRequest
	4,  // 24: greet.NipaService.GetTreeManifest:input_type -> greet.GetTreeManifestRequest
	11, // 25: greet.NipaService.Push:input_type -> greet.PushRequest
	7,  // 26: greet.NipaService.UploadChunks:input_type -> greet.ChunkUploadRequest
	9,  // 27: greet.NipaService.DownloadChunks:input_type -> greet.DownloadChunksRequest
	23, // 28: greet.NipaService.LoginWithUsernamePassword:output_type -> greet.LoginResponse
	23, // 29: greet.NipaService.LoginWithRefreshToken:output_type -> greet.LoginResponse
	15, // 30: greet.NipaService.GetListBranch:output_type -> greet.GetListBranchResponse
	18, // 31: greet.NipaService.GetBranch:output_type -> greet.GetBranchResponse
	18, // 32: greet.NipaService.GetDefaultBranch:output_type -> greet.GetBranchResponse
	20, // 33: greet.NipaService.CreateBranch:output_type -> greet.CreateBranchResponse
	5,  // 34: greet.NipaService.GetTreeManifest:output_type -> greet.GetTreeManifestResponse
	12, // 35: greet.NipaService.Push:output_type -> greet.PushResponse
	8,  // 36: greet.NipaService.UploadChunks:output_type -> greet.UploadChunksResponse
	10, // 37: greet.NipaService.DownloadChunks:output_type -> greet.DownloadChunk
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_server_proto_init() }
func file_internal_grpc_proto_server_proto_init() {
	if File_internal_grpc_proto_server_proto != nil {
		return
	}
	file_internal_grpc_proto_server_proto_msgTypes[3].OneofWrappers = []any{}
	file_internal_grpc_proto_server_proto_msgTypes[12].OneofWrappers = []any{}
	file_internal_grpc_proto_server_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_server_proto_rawDesc), len(file_internal_grpc_proto_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_server_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_server_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_server_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_server_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_server_proto = out.File
	file_internal_grpc_proto_server_proto_goTypes = nil
	file_internal_grpc_proto_server_proto_depIdxs = nil
}
