// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: internal/grpc/proto/server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileMode int32

const (
	FileMode_FILE_MODE_UNSPECIFIED FileMode = 0
	FileMode_FILE_MODE_READ_ONLY   FileMode = 1
	FileMode_FILE_MODE_READ_WRITE  FileMode = 2
	FileMode_FILE_MODE_EXECUTABLE  FileMode = 3
)

// Enum value maps for FileMode.
var (
	FileMode_name = map[int32]string{
		0: "FILE_MODE_UNSPECIFIED",
		1: "FILE_MODE_READ_ONLY",
		2: "FILE_MODE_READ_WRITE",
		3: "FILE_MODE_EXECUTABLE",
	}
	FileMode_value = map[string]int32{
		"FILE_MODE_UNSPECIFIED": 0,
		"FILE_MODE_READ_ONLY":   1,
		"FILE_MODE_READ_WRITE":  2,
		"FILE_MODE_EXECUTABLE":  3,
	}
)

func (x FileMode) Enum() *FileMode {
	p := new(FileMode)
	*p = x
	return p
}

func (x FileMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileMode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_grpc_proto_server_proto_enumTypes[0].Descriptor()
}

func (FileMode) Type() protoreflect.EnumType {
	return &file_internal_grpc_proto_server_proto_enumTypes[0]
}

func (x FileMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileMode.Descriptor instead.
func (FileMode) EnumDescriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{0}
}

type ProjectContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectContext) Reset() {
	*x = ProjectContext{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectContext) ProtoMessage() {}

func (x *ProjectContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectContext.ProtoReflect.Descriptor instead.
func (*ProjectContext) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectContext) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *ProjectContext) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type FileNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          FileMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=greet.FileMode" json:"mode,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IsBinary      bool                   `protobuf:"varint,4,opt,name=is_binary,json=isBinary,proto3" json:"is_binary,omitempty"`
	ChunkHashes   []string               `protobuf:"bytes,5,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileNode) Reset() {
	*x = FileNode{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileNode) ProtoMessage() {}

func (x *FileNode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileNode.ProtoReflect.Descriptor instead.
func (*FileNode) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *FileNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileNode) GetMode() FileMode {
	if x != nil {
		return x.Mode
	}
	return FileMode_FILE_MODE_UNSPECIFIED
}

func (x *FileNode) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileNode) GetIsBinary() bool {
	if x != nil {
		return x.IsBinary
	}
	return false
}

func (x *FileNode) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type TreeManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TreeHash      string                 `protobuf:"bytes,1,opt,name=tree_hash,json=treeHash,proto3" json:"tree_hash,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                         // Subdirectory path, e.g., "assets/shaders"
	SubTrees      []*TreeManifest        `protobuf:"bytes,3,rep,name=sub_trees,json=subTrees,proto3" json:"sub_trees,omitempty"` // Child directory trees
	Files         []*FileNode            `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeManifest) Reset() {
	*x = TreeManifest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeManifest) ProtoMessage() {}

func (x *TreeManifest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeManifest.ProtoReflect.Descriptor instead.
func (*TreeManifest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *TreeManifest) GetTreeHash() string {
	if x != nil {
		return x.TreeHash
	}
	return ""
}

func (x *TreeManifest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TreeManifest) GetSubTrees() []*TreeManifest {
	if x != nil {
		return x.SubTrees
	}
	return nil
}

func (x *TreeManifest) GetFiles() []*FileNode {
	if x != nil {
		return x.Files
	}
	return nil
}

type GetTreeManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	TreeHash      *string                `protobuf:"bytes,4,opt,name=tree_hash,json=treeHash,proto3,oneof" json:"tree_hash,omitempty"`
	Recursive     bool                   `protobuf:"varint,5,opt,name=recursive,proto3" json:"recursive,omitempty"`
	Paths         []string               `protobuf:"bytes,6,rep,name=paths,proto3" json:"paths,omitempty"` // directory prefixes to include; empty = whole tree
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeManifestRequest) Reset() {
	*x = GetTreeManifestRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeManifestRequest) ProtoMessage() {}

func (x *GetTreeManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeManifestRequest.ProtoReflect.Descriptor instead.
func (*GetTreeManifestRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetTreeManifestRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetTreeManifestRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetTreeManifestRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetTreeManifestRequest) GetTreeHash() string {
	if x != nil && x.TreeHash != nil {
		return *x.TreeHash
	}
	return ""
}

func (x *GetTreeManifestRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *GetTreeManifestRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type GetTreeManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	RootTree      *TreeManifest          `protobuf:"bytes,2,opt,name=root_tree,json=rootTree,proto3" json:"root_tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeManifestResponse) Reset() {
	*x = GetTreeManifestResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeManifestResponse) ProtoMessage() {}

func (x *GetTreeManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeManifestResponse.ProtoReflect.Descriptor instead.
func (*GetTreeManifestResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetTreeManifestResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetTreeManifestResponse) GetRootTree() *TreeManifest {
	if x != nil {
		return x.RootTree
	}
	return nil
}

type PushFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // repository-relative file path, e.g. "assets/logo.png"
	Mode          FileMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=greet.FileMode" json:"mode,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IsBinary      bool                   `protobuf:"varint,4,opt,name=is_binary,json=isBinary,proto3" json:"is_binary,omitempty"`
	FileHash      string                 `protobuf:"bytes,5,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	ChunkHashes   []string               `protobuf:"bytes,6,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushFile) Reset() {
	*x = PushFile{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushFile) ProtoMessage() {}

func (x *PushFile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushFile.ProtoReflect.Descriptor instead.
func (*PushFile) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{5}
}

func (x *PushFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PushFile) GetMode() FileMode {
	if x != nil {
		return x.Mode
	}
	return FileMode_FILE_MODE_UNSPECIFIED
}

func (x *PushFile) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PushFile) GetIsBinary() bool {
	if x != nil {
		return x.IsBinary
	}
	return false
}

func (x *PushFile) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *PushFile) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type ChunkUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"` // required on the first message
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`       // hex-encoded BLAKE3 hash of data
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkUploadRequest) Reset() {
	*x = ChunkUploadRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkUploadRequest) ProtoMessage() {}

func (x *ChunkUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkUploadRequest.ProtoReflect.Descriptor instead.
func (*ChunkUploadRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{6}
}

func (x *ChunkUploadRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ChunkUploadRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ChunkUploadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uploaded      int32                  `protobuf:"varint,1,opt,name=uploaded,proto3" json:"uploaded,omitempty"`
	Skipped       int32                  `protobuf:"varint,2,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunksResponse) Reset() {
	*x = UploadChunksResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunksResponse) ProtoMessage() {}

func (x *UploadChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunksResponse.ProtoReflect.Descriptor instead.
func (*UploadChunksResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{7}
}

func (x *UploadChunksResponse) GetUploaded() int32 {
	if x != nil {
		return x.Uploaded
	}
	return 0
}

func (x *UploadChunksResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

type DownloadChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                            // hex-encoded BLAKE3 hash of data
	Context       *ProjectContext        `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`                      // required on the first message
	CommitIds     []string               `protobuf:"bytes,3,rep,name=commit_ids,json=commitIds,proto3" json:"commit_ids,omitempty"` // base36 snow IDs; visible chunks are the union of these trees
	Paths         []string               `protobuf:"bytes,4,rep,name=paths,proto3" json:"paths,omitempty"`                          // optional path prefixes narrowing the visible chunks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunksRequest) Reset() {
	*x = DownloadChunksRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunksRequest) ProtoMessage() {}

func (x *DownloadChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunksRequest.ProtoReflect.Descriptor instead.
func (*DownloadChunksRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadChunksRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DownloadChunksRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DownloadChunksRequest) GetCommitIds() []string {
	if x != nil {
		return x.CommitIds
	}
	return nil
}

func (x *DownloadChunksRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type DownloadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // hex-encoded BLAKE3 hash of data
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunk) Reset() {
	*x = DownloadChunk{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunk) ProtoMessage() {}

func (x *DownloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunk.ProtoReflect.Descriptor instead.
func (*DownloadChunk) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadChunk) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DownloadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PushRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Context            *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Branch             string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	BaseTreeHash       string                 `protobuf:"bytes,3,opt,name=base_tree_hash,json=baseTreeHash,proto3" json:"base_tree_hash,omitempty"` // tree hash the client is based on, empty for branches without commits
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Files              []*PushFile            `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	RemovedFiles       []string               `protobuf:"bytes,6,rep,name=removed_files,json=removedFiles,proto3" json:"removed_files,omitempty"`                          // paths removed relative to the base tree
	Parent_2CommitHash *string                `protobuf:"bytes,7,opt,name=parent_2_commit_hash,json=parent2CommitHash,proto3,oneof" json:"parent_2_commit_hash,omitempty"` // second parent for merge commits; empty for normal pushes
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{10}
}

func (x *PushRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *PushRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *PushRequest) GetBaseTreeHash() string {
	if x != nil {
		return x.BaseTreeHash
	}
	return ""
}

func (x *PushRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PushRequest) GetFiles() []*PushFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *PushRequest) GetRemovedFiles() []string {
	if x != nil {
		return x.RemovedFiles
	}
	return nil
}

func (x *PushRequest) GetParent_2CommitHash() string {
	if x != nil && x.Parent_2CommitHash != nil {
		return *x.Parent_2CommitHash
	}
	return ""
}

type PushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitId      string                 `protobuf:"bytes,1,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	TreeHash      string                 `protobuf:"bytes,3,opt,name=tree_hash,json=treeHash,proto3" json:"tree_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{11}
}

func (x *PushResponse) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *PushResponse) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *PushResponse) GetTreeHash() string {
	if x != nil {
		return x.TreeHash
	}
	return ""
}

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CommitId      *string                `protobuf:"bytes,5,opt,name=commit_id,json=commitId,proto3,oneof" json:"commit_id,omitempty"`
	IsProtected   bool                   `protobuf:"varint,6,opt,name=is_protected,json=isProtected,proto3" json:"is_protected,omitempty"`
	IsDefault     bool                   `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{12}
}

func (x *Branch) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Branch) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Branch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetCommitId() string {
	if x != nil && x.CommitId != nil {
		return *x.CommitId
	}
	return ""
}

func (x *Branch) GetIsProtected() bool {
	if x != nil {
		return x.IsProtected
	}
	return false
}

func (x *Branch) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type GetListBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	LastUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated_at,json=lastUpdatedAt,proto3,oneof" json:"last_updated_at,omitempty"`
	LastId        *string                `protobuf:"bytes,4,opt,name=last_id,json=lastId,proto3,oneof" json:"last_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListBranchRequest) Reset() {
	*x = GetListBranchRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBranchRequest) ProtoMessage() {}

func (x *GetListBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListBranchRequest.ProtoReflect.Descriptor instead.
func (*GetListBranchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{13}
}

func (x *GetListBranchRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetListBranchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetListBranchRequest) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

func (x *GetListBranchRequest) GetLastId() string {
	if x != nil && x.LastId != nil {
		return *x.LastId
	}
	return ""
}

type GetListBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branches      []*Branch              `protobuf:"bytes,1,rep,name=branches,proto3" json:"branches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListBranchResponse) Reset() {
	*x = GetListBranchResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBranchResponse) ProtoMessage() {}

func (x *GetListBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListBranchResponse.ProtoReflect.Descriptor instead.
func (*GetListBranchResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{14}
}

func (x *GetListBranchResponse) GetBranches() []*Branch {
	if x != nil {
		return x.Branches
	}
	return nil
}

type GetBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	BranchId      string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"` // base36 snow ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchRequest) Reset() {
	*x = GetBranchRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchRequest) ProtoMessage() {}

func (x *GetBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchRequest.ProtoReflect.Descriptor instead.
func (*GetBranchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{15}
}

func (x *GetBranchRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetBranchRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

type GetBranchByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchByNameRequest) Reset() {
	*x = GetBranchByNameRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchByNameRequest) ProtoMessage() {}

func (x *GetBranchByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchByNameRequest.ProtoReflect.Descriptor instead.
func (*GetBranchByNameRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{16}
}

func (x *GetBranchByNameRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetBranchByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBranchByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchByNameResponse) Reset() {
	*x = GetBranchByNameResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchByNameResponse) ProtoMessage() {}

func (x *GetBranchByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchByNameResponse.ProtoReflect.Descriptor instead.
func (*GetBranchByNameResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{17}
}

func (x *GetBranchByNameResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

type GetDefaultBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultBranchRequest) Reset() {
	*x = GetDefaultBranchRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultBranchRequest) ProtoMessage() {}

func (x *GetDefaultBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultBranchRequest.ProtoReflect.Descriptor instead.
func (*GetDefaultBranchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{18}
}

func (x *GetDefaultBranchRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type GetBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBranchResponse) Reset() {
	*x = GetBranchResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBranchResponse) ProtoMessage() {}

func (x *GetBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBranchResponse.ProtoReflect.Descriptor instead.
func (*GetBranchResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{19}
}

func (x *GetBranchResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

type CreateBranchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FromBranch     string                 `protobuf:"bytes,3,opt,name=from_branch,json=fromBranch,proto3" json:"from_branch,omitempty"`               // branch to fork from; empty to fork from the default branch
	FromCommitId   string                 `protobuf:"bytes,4,opt,name=from_commit_id,json=fromCommitId,proto3" json:"from_commit_id,omitempty"`       // exact commit to fork from (base36 snow ID); takes precedence over from_commit_hash and from_branch
	FromCommitHash string                 `protobuf:"bytes,5,opt,name=from_commit_hash,json=fromCommitHash,proto3" json:"from_commit_hash,omitempty"` // exact commit to fork from (hex content hash); takes precedence over from_branch
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBranchRequest) Reset() {
	*x = CreateBranchRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchRequest) ProtoMessage() {}

func (x *CreateBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchRequest.ProtoReflect.Descriptor instead.
func (*CreateBranchRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{20}
}

func (x *CreateBranchRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateBranchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBranchRequest) GetFromBranch() string {
	if x != nil {
		return x.FromBranch
	}
	return ""
}

func (x *CreateBranchRequest) GetFromCommitId() string {
	if x != nil {
		return x.FromCommitId
	}
	return ""
}

func (x *CreateBranchRequest) GetFromCommitHash() string {
	if x != nil {
		return x.FromCommitHash
	}
	return ""
}

type CreateBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBranchResponse) Reset() {
	*x = CreateBranchResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBranchResponse) ProtoMessage() {}

func (x *CreateBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBranchResponse.ProtoReflect.Descriptor instead.
func (*CreateBranchResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{21}
}

func (x *CreateBranchResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

type GetMergeBaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TargetBranch   string                 `protobuf:"bytes,2,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`               // used when target_commit_id is empty
	SourceBranch   string                 `protobuf:"bytes,3,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`               // used when source_commit_id is empty
	TargetCommitId *string                `protobuf:"bytes,4,opt,name=target_commit_id,json=targetCommitId,proto3,oneof" json:"target_commit_id,omitempty"` // base36 snow ID; takes precedence over target_branch
	SourceCommitId *string                `protobuf:"bytes,5,opt,name=source_commit_id,json=sourceCommitId,proto3,oneof" json:"source_commit_id,omitempty"` // base36 snow ID; takes precedence over source_branch
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMergeBaseRequest) Reset() {
	*x = GetMergeBaseRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMergeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMergeBaseRequest) ProtoMessage() {}

func (x *GetMergeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMergeBaseRequest.ProtoReflect.Descriptor instead.
func (*GetMergeBaseRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{22}
}

func (x *GetMergeBaseRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetMergeBaseRequest) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *GetMergeBaseRequest) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

func (x *GetMergeBaseRequest) GetTargetCommitId() string {
	if x != nil && x.TargetCommitId != nil {
		return *x.TargetCommitId
	}
	return ""
}

func (x *GetMergeBaseRequest) GetSourceCommitId() string {
	if x != nil && x.SourceCommitId != nil {
		return *x.SourceCommitId
	}
	return ""
}

type GetMergeBaseResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetBranch      string                 `protobuf:"bytes,1,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	SourceBranch      string                 `protobuf:"bytes,2,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`
	TargetCommitId    string                 `protobuf:"bytes,3,opt,name=target_commit_id,json=targetCommitId,proto3" json:"target_commit_id,omitempty"`            // base36 snow ID; empty when the branch has no commits
	SourceCommitId    string                 `protobuf:"bytes,4,opt,name=source_commit_id,json=sourceCommitId,proto3" json:"source_commit_id,omitempty"`            // base36 snow ID; empty when the branch has no commits
	MergeBaseCommitId string                 `protobuf:"bytes,5,opt,name=merge_base_commit_id,json=mergeBaseCommitId,proto3" json:"merge_base_commit_id,omitempty"` // base36 snow ID; empty when either head is empty
	MergeBaseTree     *TreeManifest          `protobuf:"bytes,6,opt,name=merge_base_tree,json=mergeBaseTree,proto3" json:"merge_base_tree,omitempty"`               // recursive manifest of the merge base tree
	TargetCommitHash  string                 `protobuf:"bytes,7,opt,name=target_commit_hash,json=targetCommitHash,proto3" json:"target_commit_hash,omitempty"`      // hex commit hash; empty when the branch has no commits
	SourceCommitHash  string                 `protobuf:"bytes,8,opt,name=source_commit_hash,json=sourceCommitHash,proto3" json:"source_commit_hash,omitempty"`      // hex commit hash; empty when the branch has no commits
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetMergeBaseResponse) Reset() {
	*x = GetMergeBaseResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMergeBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMergeBaseResponse) ProtoMessage() {}

func (x *GetMergeBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMergeBaseResponse.ProtoReflect.Descriptor instead.
func (*GetMergeBaseResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{23}
}

func (x *GetMergeBaseResponse) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *GetMergeBaseResponse) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

func (x *GetMergeBaseResponse) GetTargetCommitId() string {
	if x != nil {
		return x.TargetCommitId
	}
	return ""
}

func (x *GetMergeBaseResponse) GetSourceCommitId() string {
	if x != nil {
		return x.SourceCommitId
	}
	return ""
}

func (x *GetMergeBaseResponse) GetMergeBaseCommitId() string {
	if x != nil {
		return x.MergeBaseCommitId
	}
	return ""
}

func (x *GetMergeBaseResponse) GetMergeBaseTree() *TreeManifest {
	if x != nil {
		return x.MergeBaseTree
	}
	return nil
}

func (x *GetMergeBaseResponse) GetTargetCommitHash() string {
	if x != nil {
		return x.TargetCommitHash
	}
	return ""
}

func (x *GetMergeBaseResponse) GetSourceCommitHash() string {
	if x != nil {
		return x.SourceCommitHash
	}
	return ""
}

type MergeFastForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TargetBranch  string                 `protobuf:"bytes,2,opt,name=target_branch,json=targetBranch,proto3" json:"target_branch,omitempty"`
	SourceBranch  string                 `protobuf:"bytes,3,opt,name=source_branch,json=sourceBranch,proto3" json:"source_branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeFastForwardRequest) Reset() {
	*x = MergeFastForwardRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeFastForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeFastForwardRequest) ProtoMessage() {}

func (x *MergeFastForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeFastForwardRequest.ProtoReflect.Descriptor instead.
func (*MergeFastForwardRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{24}
}

func (x *MergeFastForwardRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *MergeFastForwardRequest) GetTargetBranch() string {
	if x != nil {
		return x.TargetBranch
	}
	return ""
}

func (x *MergeFastForwardRequest) GetSourceBranch() string {
	if x != nil {
		return x.SourceBranch
	}
	return ""
}

type MergeFastForwardResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Branch          *Branch                `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`                                              // the target branch after the head moved to the source head
	MovedToCommitId string                 `protobuf:"bytes,2,opt,name=moved_to_commit_id,json=movedToCommitId,proto3" json:"moved_to_commit_id,omitempty"` // base36 snow ID of the source head the target now points at
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MergeFastForwardResponse) Reset() {
	*x = MergeFastForwardResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeFastForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeFastForwardResponse) ProtoMessage() {}

func (x *MergeFastForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeFastForwardResponse.ProtoReflect.Descriptor instead.
func (*MergeFastForwardResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{25}
}

func (x *MergeFastForwardResponse) GetBranch() *Branch {
	if x != nil {
		return x.Branch
	}
	return nil
}

func (x *MergeFastForwardResponse) GetMovedToCommitId() string {
	if x != nil {
		return x.MovedToCommitId
	}
	return ""
}

type CommitLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitId      string                 `protobuf:"bytes,1,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`            // base36 snow ID
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`      // hex-encoded BLAKE3 content hash
	Parent_1Id    *string                `protobuf:"bytes,3,opt,name=parent_1_id,json=parent1Id,proto3,oneof" json:"parent_1_id,omitempty"` // base36 snow ID; empty for a root commit
	Parent_2Id    *string                `protobuf:"bytes,4,opt,name=parent_2_id,json=parent2Id,proto3,oneof" json:"parent_2_id,omitempty"` // base36 snow ID; set for merge commits
	AuthorName    string                 `protobuf:"bytes,5,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorEmail   string                 `protobuf:"bytes,6,opt,name=author_email,json=authorEmail,proto3" json:"author_email,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitLogEntry) Reset() {
	*x = CommitLogEntry{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitLogEntry) ProtoMessage() {}

func (x *CommitLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitLogEntry.ProtoReflect.Descriptor instead.
func (*CommitLogEntry) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{26}
}

func (x *CommitLogEntry) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *CommitLogEntry) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *CommitLogEntry) GetParent_1Id() string {
	if x != nil && x.Parent_1Id != nil {
		return *x.Parent_1Id
	}
	return ""
}

func (x *CommitLogEntry) GetParent_2Id() string {
	if x != nil && x.Parent_2Id != nil {
		return *x.Parent_2Id
	}
	return ""
}

func (x *CommitLogEntry) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *CommitLogEntry) GetAuthorEmail() string {
	if x != nil {
		return x.AuthorEmail
	}
	return ""
}

func (x *CommitLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitLogEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetCommitLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`                                            // empty to use the default branch
	StartCommitId *string                `protobuf:"bytes,3,opt,name=start_commit_id,json=startCommitId,proto3,oneof" json:"start_commit_id,omitempty"` // base36 snow ID; empty to start from the branch head
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitLogRequest) Reset() {
	*x = GetCommitLogRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitLogRequest) ProtoMessage() {}

func (x *GetCommitLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitLogRequest.ProtoReflect.Descriptor instead.
func (*GetCommitLogRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{27}
}

func (x *GetCommitLogRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetCommitLogRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetCommitLogRequest) GetStartCommitId() string {
	if x != nil && x.StartCommitId != nil {
		return *x.StartCommitId
	}
	return ""
}

func (x *GetCommitLogRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetCommitLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Branch        string                 `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	Commits       []*CommitLogEntry      `protobuf:"bytes,2,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitLogResponse) Reset() {
	*x = GetCommitLogResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitLogResponse) ProtoMessage() {}

func (x *GetCommitLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitLogResponse.ProtoReflect.Descriptor instead.
func (*GetCommitLogResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{28}
}

func (x *GetCommitLogResponse) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetCommitLogResponse) GetCommits() []*CommitLogEntry {
	if x != nil {
		return x.Commits
	}
	return nil
}

type CommitDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitId      string                 `protobuf:"bytes,1,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`            // base36 snow ID
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`      // hex-encoded BLAKE3 content hash
	TreeHash      string                 `protobuf:"bytes,3,opt,name=tree_hash,json=treeHash,proto3" json:"tree_hash,omitempty"`            // hex-encoded root tree hash
	Parent_1Id    *string                `protobuf:"bytes,4,opt,name=parent_1_id,json=parent1Id,proto3,oneof" json:"parent_1_id,omitempty"` // base36 snow ID; empty for a root commit
	Parent_2Id    *string                `protobuf:"bytes,5,opt,name=parent_2_id,json=parent2Id,proto3,oneof" json:"parent_2_id,omitempty"` // base36 snow ID; set for merge commits
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitDetail) Reset() {
	*x = CommitDetail{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDetail) ProtoMessage() {}

func (x *CommitDetail) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDetail.ProtoReflect.Descriptor instead.
func (*CommitDetail) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{29}
}

func (x *CommitDetail) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *CommitDetail) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *CommitDetail) GetTreeHash() string {
	if x != nil {
		return x.TreeHash
	}
	return ""
}

func (x *CommitDetail) GetParent_1Id() string {
	if x != nil && x.Parent_1Id != nil {
		return *x.Parent_1Id
	}
	return ""
}

func (x *CommitDetail) GetParent_2Id() string {
	if x != nil && x.Parent_2Id != nil {
		return *x.Parent_2Id
	}
	return ""
}

func (x *CommitDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetCommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	CommitId      string                 `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"` // base36 snow ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitRequest) Reset() {
	*x = GetCommitRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitRequest) ProtoMessage() {}

func (x *GetCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitRequest.ProtoReflect.Descriptor instead.
func (*GetCommitRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{30}
}

func (x *GetCommitRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetCommitRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

type GetCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commit        *CommitDetail          `protobuf:"bytes,1,opt,name=commit,proto3" json:"commit,omitempty"`
	RootTree      *TreeManifest          `protobuf:"bytes,2,opt,name=root_tree,json=rootTree,proto3" json:"root_tree,omitempty"` // recursive manifest of the commit tree
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitResponse) Reset() {
	*x = GetCommitResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitResponse) ProtoMessage() {}

func (x *GetCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitResponse.ProtoReflect.Descriptor instead.
func (*GetCommitResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{31}
}

func (x *GetCommitResponse) GetCommit() *CommitDetail {
	if x != nil {
		return x.Commit
	}
	return nil
}

func (x *GetCommitResponse) GetRootTree() *TreeManifest {
	if x != nil {
		return x.RootTree
	}
	return nil
}

type CommitWalkEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitId      string                 `protobuf:"bytes,1,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`            // base36 snow ID
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`      // hex-encoded BLAKE3 content hash
	Parent_1Id    *string                `protobuf:"bytes,3,opt,name=parent_1_id,json=parent1Id,proto3,oneof" json:"parent_1_id,omitempty"` // base36 snow ID; empty for a root commit
	Parent_2Id    *string                `protobuf:"bytes,4,opt,name=parent_2_id,json=parent2Id,proto3,oneof" json:"parent_2_id,omitempty"` // base36 snow ID; set for merge commits
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitWalkEntry) Reset() {
	*x = CommitWalkEntry{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitWalkEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitWalkEntry) ProtoMessage() {}

func (x *CommitWalkEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitWalkEntry.ProtoReflect.Descriptor instead.
func (*CommitWalkEntry) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{32}
}

func (x *CommitWalkEntry) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *CommitWalkEntry) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *CommitWalkEntry) GetParent_1Id() string {
	if x != nil && x.Parent_1Id != nil {
		return *x.Parent_1Id
	}
	return ""
}

func (x *CommitWalkEntry) GetParent_2Id() string {
	if x != nil && x.Parent_2Id != nil {
		return *x.Parent_2Id
	}
	return ""
}

func (x *CommitWalkEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitWalkEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type WalkCommitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *ProjectContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	StartCommitId string                 `protobuf:"bytes,2,opt,name=start_commit_id,json=startCommitId,proto3" json:"start_commit_id,omitempty"`    // base36 snow ID; walk starts here (inclusive)
	StopCommitId  *string                `protobuf:"bytes,3,opt,name=stop_commit_id,json=stopCommitId,proto3,oneof" json:"stop_commit_id,omitempty"` // base36 snow ID; exclusive boundary
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalkCommitsRequest) Reset() {
	*x = WalkCommitsRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkCommitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkCommitsRequest) ProtoMessage() {}

func (x *WalkCommitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkCommitsRequest.ProtoReflect.Descriptor instead.
func (*WalkCommitsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{33}
}

func (x *WalkCommitsRequest) GetContext() *ProjectContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *WalkCommitsRequest) GetStartCommitId() string {
	if x != nil {
		return x.StartCommitId
	}
	return ""
}

func (x *WalkCommitsRequest) GetStopCommitId() string {
	if x != nil && x.StopCommitId != nil {
		return *x.StopCommitId
	}
	return ""
}

func (x *WalkCommitsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type WalkCommitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*CommitWalkEntry     `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"` // newest first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalkCommitsResponse) Reset() {
	*x = WalkCommitsResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkCommitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkCommitsResponse) ProtoMessage() {}

func (x *WalkCommitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkCommitsResponse.ProtoReflect.Descriptor instead.
func (*WalkCommitsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{34}
}

func (x *WalkCommitsResponse) GetCommits() []*CommitWalkEntry {
	if x != nil {
		return x.Commits
	}
	return nil
}

type LoginUsernamePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUsernamePasswordRequest) Reset() {
	*x = LoginUsernamePasswordRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUsernamePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUsernamePasswordRequest) ProtoMessage() {}

func (x *LoginUsernamePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUsernamePasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginUsernamePasswordRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{35}
}

func (x *LoginUsernamePasswordRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginUsernamePasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginWithRefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithRefreshRequest) Reset() {
	*x = LoginWithRefreshRequest{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithRefreshRequest) ProtoMessage() {}

func (x *LoginWithRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithRefreshRequest.ProtoReflect.Descriptor instead.
func (*LoginWithRefreshRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{36}
}

func (x *LoginWithRefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_grpc_proto_server_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_server_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_server_proto_rawDescGZIP(), []int{37}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

var File_internal_grpc_proto_server_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_server_proto_rawDesc = "" +
	"\n" +
	" internal/grpc/proto/server.proto\x12\x05greet\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\x0eProjectContext\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\"\xa2\x01\n" +
	"\bFileNode\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x0f.greet.FileModeR\x04mode\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tis_binary\x18\x04 \x01(\bR\bisBinary\x12!\n" +
	"\fchunk_hashes\x18\x05 \x03(\tR\vchunkHashes\"\x98\x01\n" +
	"\fTreeManifest\x12\x1b\n" +
	"\ttree_hash\x18\x01 \x01(\tR\btreeHash\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x120\n" +
	"\tsub_trees\x18\x03 \x03(\v2\x13.greet.TreeManifestR\bsubTrees\x12%\n" +
	"\x05files\x18\x04 \x03(\v2\x0f.greet.FileNodeR\x05files\"\xd9\x01\n" +
	"\x16GetTreeManifestRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12 \n" +
	"\ttree_hash\x18\x04 \x01(\tH\x00R\btreeHash\x88\x01\x01\x12\x1c\n" +
	"\trecursive\x18\x05 \x01(\bR\trecursive\x12\x14\n" +
	"\x05paths\x18\x06 \x03(\tR\x05pathsB\f\n" +
	"\n" +
	"_tree_hash\"c\n" +
	"\x17GetTreeManifestResponse\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x120\n" +
	"\troot_tree\x18\x02 \x01(\v2\x13.greet.TreeManifestR\brootTree\"\xbf\x01\n" +
	"\bPushFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x0f.greet.FileModeR\x04mode\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tis_binary\x18\x04 \x01(\bR\bisBinary\x12\x1b\n" +
	"\tfile_hash\x18\x05 \x01(\tR\bfileHash\x12!\n" +
	"\fchunk_hashes\x18\x06 \x03(\tR\vchunkHashes\"m\n" +
	"\x12ChunkUploadRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"L\n" +
	"\x14UploadChunksResponse\x12\x1a\n" +
	"\buploaded\x18\x01 \x01(\x05R\buploaded\x12\x18\n" +
	"\askipped\x18\x02 \x01(\x05R\askipped\"\x91\x01\n" +
	"\x15DownloadChunksRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12/\n" +
	"\acontext\x18\x02 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x1d\n" +
	"\n" +
	"commit_ids\x18\x03 \x03(\tR\tcommitIds\x12\x14\n" +
	"\x05paths\x18\x04 \x03(\tR\x05paths\"7\n" +
	"\rDownloadChunk\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xb1\x02\n" +
	"\vPushRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12$\n" +
	"\x0ebase_tree_hash\x18\x03 \x01(\tR\fbaseTreeHash\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12%\n" +
	"\x05files\x18\x05 \x03(\v2\x0f.greet.PushFileR\x05files\x12#\n" +
	"\rremoved_files\x18\x06 \x03(\tR\fremovedFiles\x124\n" +
	"\x14parent_2_commit_hash\x18\a \x01(\tH\x00R\x11parent2CommitHash\x88\x01\x01B\x17\n" +
	"\x15_parent_2_commit_hash\"i\n" +
	"\fPushResponse\x12\x1b\n" +
	"\tcommit_id\x18\x01 \x01(\tR\bcommitId\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12\x1b\n" +
	"\ttree_hash\x18\x03 \x01(\tR\btreeHash\"\x94\x02\n" +
	"\x06Branch\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\tcommit_id\x18\x05 \x01(\tH\x00R\bcommitId\x88\x01\x01\x12!\n" +
	"\fis_protected\x18\x06 \x01(\bR\visProtected\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefaultB\f\n" +
	"\n" +
	"_commit_id\"\xe4\x01\n" +
	"\x14GetListBranchRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12G\n" +
	"\x0flast_updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\rlastUpdatedAt\x88\x01\x01\x12\x1c\n" +
	"\alast_id\x18\x04 \x01(\tH\x01R\x06lastId\x88\x01\x01B\x12\n" +
	"\x10_last_updated_atB\n" +
	"\n" +
	"\b_last_id\"B\n" +
	"\x15GetListBranchResponse\x12)\n" +
	"\bbranches\x18\x01 \x03(\v2\r.greet.BranchR\bbranches\"`\n" +
	"\x10GetBranchRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\"]\n" +
	"\x16GetBranchByNameRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"@\n" +
	"\x17GetBranchByNameResponse\x12%\n" +
	"\x06branch\x18\x01 \x01(\v2\r.greet.BranchR\x06branch\"J\n" +
	"\x17GetDefaultBranchRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\":\n" +
	"\x11GetBranchResponse\x12%\n" +
	"\x06branch\x18\x01 \x01(\v2\r.greet.BranchR\x06branch\"\xcb\x01\n" +
	"\x13CreateBranchRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vfrom_branch\x18\x03 \x01(\tR\n" +
	"fromBranch\x12$\n" +
	"\x0efrom_commit_id\x18\x04 \x01(\tR\ffromCommitId\x12(\n" +
	"\x10from_commit_hash\x18\x05 \x01(\tR\x0efromCommitHash\"=\n" +
	"\x14CreateBranchResponse\x12%\n" +
	"\x06branch\x18\x01 \x01(\v2\r.greet.BranchR\x06branch\"\x98\x02\n" +
	"\x13GetMergeBaseRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12#\n" +
	"\rtarget_branch\x18\x02 \x01(\tR\ftargetBranch\x12#\n" +
	"\rsource_branch\x18\x03 \x01(\tR\fsourceBranch\x12-\n" +
	"\x10target_commit_id\x18\x04 \x01(\tH\x00R\x0etargetCommitId\x88\x01\x01\x12-\n" +
	"\x10source_commit_id\x18\x05 \x01(\tH\x01R\x0esourceCommitId\x88\x01\x01B\x13\n" +
	"\x11_target_commit_idB\x13\n" +
	"\x11_source_commit_id\"\xfe\x02\n" +
	"\x14GetMergeBaseResponse\x12#\n" +
	"\rtarget_branch\x18\x01 \x01(\tR\ftargetBranch\x12#\n" +
	"\rsource_branch\x18\x02 \x01(\tR\fsourceBranch\x12(\n" +
	"\x10target_commit_id\x18\x03 \x01(\tR\x0etargetCommitId\x12(\n" +
	"\x10source_commit_id\x18\x04 \x01(\tR\x0esourceCommitId\x12/\n" +
	"\x14merge_base_commit_id\x18\x05 \x01(\tR\x11mergeBaseCommitId\x12;\n" +
	"\x0fmerge_base_tree\x18\x06 \x01(\v2\x13.greet.TreeManifestR\rmergeBaseTree\x12,\n" +
	"\x12target_commit_hash\x18\a \x01(\tR\x10targetCommitHash\x12,\n" +
	"\x12source_commit_hash\x18\b \x01(\tR\x10sourceCommitHash\"\x94\x01\n" +
	"\x17MergeFastForwardRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12#\n" +
	"\rtarget_branch\x18\x02 \x01(\tR\ftargetBranch\x12#\n" +
	"\rsource_branch\x18\x03 \x01(\tR\fsourceBranch\"n\n" +
	"\x18MergeFastForwardResponse\x12%\n" +
	"\x06branch\x18\x01 \x01(\v2\r.greet.BranchR\x06branch\x12+\n" +
	"\x12moved_to_commit_id\x18\x02 \x01(\tR\x0fmovedToCommitId\"\xd1\x02\n" +
	"\x0eCommitLogEntry\x12\x1b\n" +
	"\tcommit_id\x18\x01 \x01(\tR\bcommitId\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12#\n" +
	"\vparent_1_id\x18\x03 \x01(\tH\x00R\tparent1Id\x88\x01\x01\x12#\n" +
	"\vparent_2_id\x18\x04 \x01(\tH\x01R\tparent2Id\x88\x01\x01\x12\x1f\n" +
	"\vauthor_name\x18\x05 \x01(\tR\n" +
	"authorName\x12!\n" +
	"\fauthor_email\x18\x06 \x01(\tR\vauthorEmail\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0e\n" +
	"\f_parent_1_idB\x0e\n" +
	"\f_parent_2_id\"\xb5\x01\n" +
	"\x13GetCommitLogRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12+\n" +
	"\x0fstart_commit_id\x18\x03 \x01(\tH\x00R\rstartCommitId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitB\x12\n" +
	"\x10_start_commit_id\"_\n" +
	"\x14GetCommitLogResponse\x12\x16\n" +
	"\x06branch\x18\x01 \x01(\tR\x06branch\x12/\n" +
	"\acommits\x18\x02 \x03(\v2\x15.greet.CommitLogEntryR\acommits\"\xa8\x02\n" +
	"\fCommitDetail\x12\x1b\n" +
	"\tcommit_id\x18\x01 \x01(\tR\bcommitId\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12\x1b\n" +
	"\ttree_hash\x18\x03 \x01(\tR\btreeHash\x12#\n" +
	"\vparent_1_id\x18\x04 \x01(\tH\x00R\tparent1Id\x88\x01\x01\x12#\n" +
	"\vparent_2_id\x18\x05 \x01(\tH\x01R\tparent2Id\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0e\n" +
	"\f_parent_1_idB\x0e\n" +
	"\f_parent_2_id\"`\n" +
	"\x10GetCommitRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12\x1b\n" +
	"\tcommit_id\x18\x02 \x01(\tR\bcommitId\"r\n" +
	"\x11GetCommitResponse\x12+\n" +
	"\x06commit\x18\x01 \x01(\v2\x13.greet.CommitDetailR\x06commit\x120\n" +
	"\troot_tree\x18\x02 \x01(\v2\x13.greet.TreeManifestR\brootTree\"\x8e\x02\n" +
	"\x0fCommitWalkEntry\x12\x1b\n" +
	"\tcommit_id\x18\x01 \x01(\tR\bcommitId\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\x12#\n" +
	"\vparent_1_id\x18\x03 \x01(\tH\x00R\tparent1Id\x88\x01\x01\x12#\n" +
	"\vparent_2_id\x18\x04 \x01(\tH\x01R\tparent2Id\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0e\n" +
	"\f_parent_1_idB\x0e\n" +
	"\f_parent_2_id\"\xc1\x01\n" +
	"\x12WalkCommitsRequest\x12/\n" +
	"\acontext\x18\x01 \x01(\v2\x15.greet.ProjectContextR\acontext\x12&\n" +
	"\x0fstart_commit_id\x18\x02 \x01(\tR\rstartCommitId\x12)\n" +
	"\x0estop_commit_id\x18\x03 \x01(\tH\x00R\fstopCommitId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitB\x11\n" +
	"\x0f_stop_commit_id\"G\n" +
	"\x13WalkCommitsResponse\x120\n" +
	"\acommits\x18\x01 \x03(\v2\x16.greet.CommitWalkEntryR\acommits\"V\n" +
	"\x1cLoginUsernamePasswordRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\x17LoginWithRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"v\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn*r\n" +
	"\bFileMode\x12\x19\n" +
	"\x15FILE_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13FILE_MODE_READ_ONLY\x10\x01\x12\x18\n" +
	"\x14FILE_MODE_READ_WRITE\x10\x02\x12\x18\n" +
	"\x14FILE_MODE_EXECUTABLE\x10\x032\xad\t\n" +
	"\vNipaService\x12V\n" +
	"\x19LoginWithUsernamePassword\x12#.greet.LoginUsernamePasswordRequest\x1a\x14.greet.LoginResponse\x12M\n" +
	"\x15LoginWithRefreshToken\x12\x1e.greet.LoginWithRefreshRequest\x1a\x14.greet.LoginResponse\x12J\n" +
	"\rGetListBranch\x12\x1b.greet.GetListBranchRequest\x1a\x1c.greet.GetListBranchResponse\x12>\n" +
	"\tGetBranch\x12\x17.greet.GetBranchRequest\x1a\x18.greet.GetBranchResponse\x12P\n" +
	"\x0fGetBranchByName\x12\x1d.greet.GetBranchByNameRequest\x1a\x1e.greet.GetBranchByNameResponse\x12L\n" +
	"\x10GetDefaultBranch\x12\x1e.greet.GetDefaultBranchRequest\x1a\x18.greet.GetBranchResponse\x12G\n" +
	"\fCreateBranch\x12\x1a.greet.CreateBranchRequest\x1a\x1b.greet.CreateBranchResponse\x12P\n" +
	"\x0fGetTreeManifest\x12\x1d.greet.GetTreeManifestRequest\x1a\x1e.greet.GetTreeManifestResponse\x12G\n" +
	"\fGetCommitLog\x12\x1a.greet.GetCommitLogRequest\x1a\x1b.greet.GetCommitLogResponse\x12>\n" +
	"\tGetCommit\x12\x17.greet.GetCommitRequest\x1a\x18.greet.GetCommitResponse\x12D\n" +
	"\vWalkCommits\x12\x19.greet.WalkCommitsRequest\x1a\x1a.greet.WalkCommitsResponse\x12G\n" +
	"\fGetMergeBase\x12\x1a.greet.GetMergeBaseRequest\x1a\x1b.greet.GetMergeBaseResponse\x12S\n" +
	"\x10MergeFastForward\x12\x1e.greet.MergeFastForwardRequest\x1a\x1f.greet.MergeFastForwardResponse\x12/\n" +
	"\x04Push\x12\x12.greet.PushRequest\x1a\x13.greet.PushResponse\x12H\n" +
	"\fUploadChunks\x12\x19.greet.ChunkUploadRequest\x1a\x1b.greet.UploadChunksResponse(\x01\x12H\n" +
	"\x0eDownloadChunks\x12\x1c.greet.DownloadChunksRequest\x1a\x14.greet.DownloadChunk(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_internal_grpc_proto_server_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_server_proto_rawDescData []byte
)

func file_internal_grpc_proto_server_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_server_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_server_proto_rawDesc), len(file_internal_grpc_proto_server_proto_rawDesc)))
	})
	return file_internal_grpc_proto_server_proto_rawDescData
}

var file_internal_grpc_proto_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_grpc_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_internal_grpc_proto_server_proto_goTypes = []any{
	(FileMode)(0),                        // 0: greet.FileMode
	(*ProjectContext)(nil),               // 1: greet.ProjectContext
	(*FileNode)(nil),                     // 2: greet.FileNode
	(*TreeManifest)(nil),                 // 3: greet.TreeManifest
	(*GetTreeManifestRequest)(nil),       // 4: greet.GetTreeManifestRequest
	(*GetTreeManifestResponse)(nil),      // 5: greet.GetTreeManifestResponse
	(*PushFile)(nil),                     // 6: greet.PushFile
	(*ChunkUploadRequest)(nil),           // 7: greet.ChunkUploadRequest
	(*UploadChunksResponse)(nil),         // 8: greet.UploadChunksResponse
	(*DownloadChunksRequest)(nil),        // 9: greet.DownloadChunksRequest
	(*DownloadChunk)(nil),                // 10: greet.DownloadChunk
	(*PushRequest)(nil),                  // 11: greet.PushRequest
	(*PushResponse)(nil),                 // 12: greet.PushResponse
	(*Branch)(nil),                       // 13: greet.Branch
	(*GetListBranchRequest)(nil),         // 14: greet.GetListBranchRequest
	(*GetListBranchResponse)(nil),        // 15: greet.GetListBranchResponse
	(*GetBranchRequest)(nil),             // 16: greet.GetBranchRequest
	(*GetBranchByNameRequest)(nil),       // 17: greet.GetBranchByNameRequest
	(*GetBranchByNameResponse)(nil),      // 18: greet.GetBranchByNameResponse
	(*GetDefaultBranchRequest)(nil),      // 19: greet.GetDefaultBranchRequest
	(*GetBranchResponse)(nil),            // 20: greet.GetBranchResponse
	(*CreateBranchRequest)(nil),          // 21: greet.CreateBranchRequest
	(*CreateBranchResponse)(nil),         // 22: greet.CreateBranchResponse
	(*GetMergeBaseRequest)(nil),          // 23: greet.GetMergeBaseRequest
	(*GetMergeBaseResponse)(nil),         // 24: greet.GetMergeBaseResponse
	(*MergeFastForwardRequest)(nil),      // 25: greet.MergeFastForwardRequest
	(*MergeFastForwardResponse)(nil),     // 26: greet.MergeFastForwardResponse
	(*CommitLogEntry)(nil),               // 27: greet.CommitLogEntry
	(*GetCommitLogRequest)(nil),          // 28: greet.GetCommitLogRequest
	(*GetCommitLogResponse)(nil),         // 29: greet.GetCommitLogResponse
	(*CommitDetail)(nil),                 // 30: greet.CommitDetail
	(*GetCommitRequest)(nil),             // 31: greet.GetCommitRequest
	(*GetCommitResponse)(nil),            // 32: greet.GetCommitResponse
	(*CommitWalkEntry)(nil),              // 33: greet.CommitWalkEntry
	(*WalkCommitsRequest)(nil),           // 34: greet.WalkCommitsRequest
	(*WalkCommitsResponse)(nil),          // 35: greet.WalkCommitsResponse
	(*LoginUsernamePasswordRequest)(nil), // 36: greet.LoginUsernamePasswordRequest
	(*LoginWithRefreshRequest)(nil),      // 37: greet.LoginWithRefreshRequest
	(*LoginResponse)(nil),                // 38: greet.LoginResponse
	(*timestamppb.Timestamp)(nil),        // 39: google.protobuf.Timestamp
}
var file_internal_grpc_proto_server_proto_depIdxs = []int32{
	0,  // 0: greet.FileNode.mode:type_name -> greet.FileMode
	3,  // 1: greet.TreeManifest.sub_trees:type_name -> greet.TreeManifest
	2,  // 2: greet.TreeManifest.files:type_name -> greet.FileNode
	1,  // 3: greet.GetTreeManifestRequest.context:type_name -> greet.ProjectContext
	3,  // 4: greet.GetTreeManifestResponse.root_tree:type_name -> greet.TreeManifest
	0,  // 5: greet.PushFile.mode:type_name -> greet.FileMode
	1,  // 6: greet.ChunkUploadRequest.context:type_name -> greet.ProjectContext
	1,  // 7: greet.DownloadChunksRequest.context:type_name -> greet.ProjectContext
	1,  // 8: greet.PushRequest.context:type_name -> greet.ProjectContext
	6,  // 9: greet.PushRequest.files:type_name -> greet.PushFile
	39, // 10: greet.Branch.created_at:type_name -> google.protobuf.Timestamp
	39, // 11: greet.Branch.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 12: greet.GetListBranchRequest.context:type_name -> greet.ProjectContext
	39, // 13: greet.GetListBranchRequest.last_updated_at:type_name -> google.protobuf.Timestamp
	13, // 14: greet.GetListBranchResponse.branches:type_name -> greet.Branch
	1,  // 15: greet.GetBranchRequest.context:type_name -> greet.ProjectContext
	1,  // 16: greet.GetBranchByNameRequest.context:type_name -> greet.ProjectContext
	13, // 17: greet.GetBranchByNameResponse.branch:type_name -> greet.Branch
	1,  // 18: greet.GetDefaultBranchRequest.context:type_name -> greet.ProjectContext
	13, // 19: greet.GetBranchResponse.branch:type_name -> greet.Branch
	1,  // 20: greet.CreateBranchRequest.context:type_name -> greet.ProjectContext
	13, // 21: greet.CreateBranchResponse.branch:type_name -> greet.Branch
	1,  // 22: greet.GetMergeBaseRequest.context:type_name -> greet.ProjectContext
	3,  // 23: greet.GetMergeBaseResponse.merge_base_tree:type_name -> greet.TreeManifest
	1,  // 24: greet.MergeFastForwardRequest.context:type_name -> greet.ProjectContext
	13, // 25: greet.MergeFastForwardResponse.branch:type_name -> greet.Branch
	39, // 26: greet.CommitLogEntry.created_at:type_name -> google.protobuf.Timestamp
	1,  // 27: greet.GetCommitLogRequest.context:type_name -> greet.ProjectContext
	27, // 28: greet.GetCommitLogResponse.commits:type_name -> greet.CommitLogEntry
	39, // 29: greet.CommitDetail.created_at:type_name -> google.protobuf.Timestamp
	1,  // 30: greet.GetCommitRequest.context:type_name -> greet.ProjectContext
	30, // 31: greet.GetCommitResponse.commit:type_name -> greet.CommitDetail
	3,  // 32: greet.GetCommitResponse.root_tree:type_name -> greet.TreeManifest
	39, // 33: greet.CommitWalkEntry.created_at:type_name -> google.protobuf.Timestamp
	1,  // 34: greet.WalkCommitsRequest.context:type_name -> greet.ProjectContext
	33, // 35: greet.WalkCommitsResponse.commits:type_name -> greet.CommitWalkEntry
	36, // 36: greet.NipaService.LoginWithUsernamePassword:input_type -> greet.LoginUsernamePasswordRequest
	37, // 37: greet.NipaService.LoginWithRefreshToken:input_type -> greet.LoginWithRefreshRequest
	14, // 38: greet.NipaService.GetListBranch:input_type -> greet.GetListBranchRequest
	16, // 39: greet.NipaService.GetBranch:input_type -> greet.GetBranchRequest
	17, // 40: greet.NipaService.GetBranchByName:input_type -> greet.GetBranchByNameRequest
	19, // 41: greet.NipaService.GetDefaultBranch:input_type -> greet.GetDefaultBranchRequest
	21, // 42: greet.NipaService.CreateBranch:input_type -> greet.CreateBranchRequest
	4,  // 43: greet.NipaService.GetTreeManifest:input_type -> greet.GetTreeManifestRequest
	28, // 44: greet.NipaService.GetCommitLog:input_type -> greet.GetCommitLogRequest
	31, // 45: greet.NipaService.GetCommit:input_type -> greet.GetCommitRequest
	34, // 46: greet.NipaService.WalkCommits:input_type -> greet.WalkCommitsRequest
	23, // 47: greet.NipaService.GetMergeBase:input_type -> greet.GetMergeBaseRequest
	25, // 48: greet.NipaService.MergeFastForward:input_type -> greet.MergeFastForwardRequest
	11, // 49: greet.NipaService.Push:input_type -> greet.PushRequest
	7,  // 50: greet.NipaService.UploadChunks:input_type -> greet.ChunkUploadRequest
	9,  // 51: greet.NipaService.DownloadChunks:input_type -> greet.DownloadChunksRequest
	38, // 52: greet.NipaService.LoginWithUsernamePassword:output_type -> greet.LoginResponse
	38, // 53: greet.NipaService.LoginWithRefreshToken:output_type -> greet.LoginResponse
	15, // 54: greet.NipaService.GetListBranch:output_type -> greet.GetListBranchResponse
	20, // 55: greet.NipaService.GetBranch:output_type -> greet.GetBranchResponse
	18, // 56: greet.NipaService.GetBranchByName:output_type -> greet.GetBranchByNameResponse
	20, // 57: greet.NipaService.GetDefaultBranch:output_type -> greet.GetBranchResponse
	22, // 58: greet.NipaService.CreateBranch:output_type -> greet.CreateBranchResponse
	5,  // 59: greet.NipaService.GetTreeManifest:output_type -> greet.GetTreeManifestResponse
	29, // 60: greet.NipaService.GetCommitLog:output_type -> greet.GetCommitLogResponse
	32, // 61: greet.NipaService.GetCommit:output_type -> greet.GetCommitResponse
	35, // 62: greet.NipaService.WalkCommits:output_type -> greet.WalkCommitsResponse
	24, // 63: greet.NipaService.GetMergeBase:output_type -> greet.GetMergeBaseResponse
	26, // 64: greet.NipaService.MergeFastForward:output_type -> greet.MergeFastForwardResponse
	12, // 65: greet.NipaService.Push:output_type -> greet.PushResponse
	8,  // 66: greet.NipaService.UploadChunks:output_type -> greet.UploadChunksResponse
	10, // 67: greet.NipaService.DownloadChunks:output_type -> greet.DownloadChunk
	52, // [52:68] is the sub-list for method output_type
	36, // [36:52] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_server_proto_init() }
func file_internal_grpc_proto_server_proto_init() {
	if File_internal_grpc_proto_server_proto != nil {
		return
	}
	file_internal_grpc_proto_server_proto_msgTypes[3].OneofWrappers = []any{}
	file_internal_grpc_proto_server_proto_msgTypes[10].OneofWrappers = []any{}
	file_internal_grpc_proto_server_proto_msgTypes[12].OneofWrappers = []any{}
	file_internal_grpc_proto_server_proto_msgTypes[13].OneofWrappers = []any{}
	file_internal_grpc_proto_server_proto_msgTypes[22].OneofWrappers = []any{}
	file_internal_grpc_proto_server_proto_msgTypes[26].OneofWrappers = []any{}
	file_internal_grpc_proto_server_proto_msgTypes[27].OneofWrappers = []any{}
	file_internal_grpc_proto_server_proto_msgTypes[29].OneofWrappers = []any{}
	file_internal_grpc_proto_server_proto_msgTypes[32].OneofWrappers = []any{}
	file_internal_grpc_proto_server_proto_msgTypes[33].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_server_proto_rawDesc), len(file_internal_grpc_proto_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_server_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_server_proto_depIdxs,
		EnumInfos:         file_internal_grpc_proto_server_proto_enumTypes,
		MessageInfos:      file_internal_grpc_proto_server_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_server_proto = out.File
	file_internal_grpc_proto_server_proto_goTypes = nil
	file_internal_grpc_proto_server_proto_depIdxs = nil
}
