// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=auth_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockuserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockuserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockuserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockuserRepository) GetByID(ctx context.Context, id snow.ID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserRepository)(nil).GetByID), ctx, id)
}

// MockauthRepository is a mock of authRepository interface.
type MockauthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockauthRepositoryMockRecorder
	isgomock struct{}
}

// MockauthRepositoryMockRecorder is the mock recorder for MockauthRepository.
type MockauthRepositoryMockRecorder struct {
	mock *MockauthRepository
}

// NewMockauthRepository creates a new mock instance.
func NewMockauthRepository(ctrl *gomock.Controller) *MockauthRepository {
	mock := &MockauthRepository{ctrl: ctrl}
	mock.recorder = &MockauthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthRepository) EXPECT() *MockauthRepositoryMockRecorder {
	return m.recorder
}

// GetAndDeleteRefreshToken mocks base method.
func (m *MockauthRepository) GetAndDeleteRefreshToken(ctx context.Context, refreshToken string) (*domain.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAndDeleteRefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAndDeleteRefreshToken indicates an expected call of GetAndDeleteRefreshToken.
func (mr *MockauthRepositoryMockRecorder) GetAndDeleteRefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAndDeleteRefreshToken", reflect.TypeOf((*MockauthRepository)(nil).GetAndDeleteRefreshToken), ctx, refreshToken)
}

// SaveRefreshToken mocks base method.
func (m *MockauthRepository) SaveRefreshToken(ctx context.Context, userID snow.ID, refreshToken string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshToken", ctx, userID, refreshToken, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRefreshToken indicates an expected call of SaveRefreshToken.
func (mr *MockauthRepositoryMockRecorder) SaveRefreshToken(ctx, userID, refreshToken, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshToken", reflect.TypeOf((*MockauthRepository)(nil).SaveRefreshToken), ctx, userID, refreshToken, expiresAt)
}

// MockpasswordHasher is a mock of passwordHasher interface.
type MockpasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordHasherMockRecorder
	isgomock struct{}
}

// MockpasswordHasherMockRecorder is the mock recorder for MockpasswordHasher.
type MockpasswordHasherMockRecorder struct {
	mock *MockpasswordHasher
}

// NewMockpasswordHasher creates a new mock instance.
func NewMockpasswordHasher(ctrl *gomock.Controller) *MockpasswordHasher {
	mock := &MockpasswordHasher{ctrl: ctrl}
	mock.recorder = &MockpasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordHasher) EXPECT() *MockpasswordHasherMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockpasswordHasher) Compare(hash, password string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", hash, password)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Compare indicates an expected call of Compare.
func (mr *MockpasswordHasherMockRecorder) Compare(hash, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockpasswordHasher)(nil).Compare), hash, password)
}

// Hash mocks base method.
func (m *MockpasswordHasher) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockpasswordHasherMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockpasswordHasher)(nil).Hash), password)
}
