// Code generated by MockGen. DO NOT EDIT.
// Source: chunk.go
//
// Generated by this command:
//
//	mockgen -source=chunk.go -destination=chunk_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/nipalab/nipa/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockchunkRepository is a mock of chunkRepository interface.
type MockchunkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockchunkRepositoryMockRecorder
	isgomock struct{}
}

// MockchunkRepositoryMockRecorder is the mock recorder for MockchunkRepository.
type MockchunkRepositoryMockRecorder struct {
	mock *MockchunkRepository
}

// NewMockchunkRepository creates a new mock instance.
func NewMockchunkRepository(ctrl *gomock.Controller) *MockchunkRepository {
	mock := &MockchunkRepository{ctrl: ctrl}
	mock.recorder = &MockchunkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchunkRepository) EXPECT() *MockchunkRepositoryMockRecorder {
	return m.recorder
}

// InsertChunkIfNotExists mocks base method.
func (m *MockchunkRepository) InsertChunkIfNotExists(ctx context.Context, hash domain.Hash, sizeBytes int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertChunkIfNotExists", ctx, hash, sizeBytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertChunkIfNotExists indicates an expected call of InsertChunkIfNotExists.
func (mr *MockchunkRepositoryMockRecorder) InsertChunkIfNotExists(ctx, hash, sizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertChunkIfNotExists", reflect.TypeOf((*MockchunkRepository)(nil).InsertChunkIfNotExists), ctx, hash, sizeBytes)
}
