// Code generated by MockGen. DO NOT EDIT.
// Source: email_delivery.go
//
// Generated by this command:
//
//	mockgen -source=email_delivery.go -destination=email_delivery_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockemailDeliveryRepository is a mock of emailDeliveryRepository interface.
type MockemailDeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockemailDeliveryRepositoryMockRecorder
	isgomock struct{}
}

// MockemailDeliveryRepositoryMockRecorder is the mock recorder for MockemailDeliveryRepository.
type MockemailDeliveryRepositoryMockRecorder struct {
	mock *MockemailDeliveryRepository
}

// NewMockemailDeliveryRepository creates a new mock instance.
func NewMockemailDeliveryRepository(ctrl *gomock.Controller) *MockemailDeliveryRepository {
	mock := &MockemailDeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockemailDeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockemailDeliveryRepository) EXPECT() *MockemailDeliveryRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockemailDeliveryRepository) Get(ctx context.Context, id snow.ID) (*domain.EmailDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.EmailDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockemailDeliveryRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockemailDeliveryRepository)(nil).Get), ctx, id)
}

// ListDeliveries mocks base method.
func (m *MockemailDeliveryRepository) ListDeliveries(ctx context.Context, projectID snow.ID, state string, after *snow.ID, limit int64) ([]*domain.EmailDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeliveries", ctx, projectID, state, after, limit)
	ret0, _ := ret[0].([]*domain.EmailDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeliveries indicates an expected call of ListDeliveries.
func (mr *MockemailDeliveryRepositoryMockRecorder) ListDeliveries(ctx, projectID, state, after, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeliveries", reflect.TypeOf((*MockemailDeliveryRepository)(nil).ListDeliveries), ctx, projectID, state, after, limit)
}

// Redeliver mocks base method.
func (m *MockemailDeliveryRepository) Redeliver(ctx context.Context, projectID, id snow.ID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redeliver", ctx, projectID, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Redeliver indicates an expected call of Redeliver.
func (mr *MockemailDeliveryRepositoryMockRecorder) Redeliver(ctx, projectID, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redeliver", reflect.TypeOf((*MockemailDeliveryRepository)(nil).Redeliver), ctx, projectID, id, at)
}
