// Code generated by MockGen. DO NOT EDIT.
// Source: file_lock.go
//
// Generated by this command:
//
//	mockgen -source=file_lock.go -destination=file_lock_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockfileLockRepository is a mock of fileLockRepository interface.
type MockfileLockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockfileLockRepositoryMockRecorder
	isgomock struct{}
}

// MockfileLockRepositoryMockRecorder is the mock recorder for MockfileLockRepository.
type MockfileLockRepositoryMockRecorder struct {
	mock *MockfileLockRepository
}

// NewMockfileLockRepository creates a new mock instance.
func NewMockfileLockRepository(ctrl *gomock.Controller) *MockfileLockRepository {
	mock := &MockfileLockRepository{ctrl: ctrl}
	mock.recorder = &MockfileLockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileLockRepository) EXPECT() *MockfileLockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockfileLockRepository) Create(ctx context.Context, lock domain.FileLock) (*domain.FileLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, lock)
	ret0, _ := ret[0].(*domain.FileLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockfileLockRepositoryMockRecorder) Create(ctx, lock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockfileLockRepository)(nil).Create), ctx, lock)
}

// Delete mocks base method.
func (m *MockfileLockRepository) Delete(ctx context.Context, id snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockfileLockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockfileLockRepository)(nil).Delete), ctx, id)
}

// DeleteByBranch mocks base method.
func (m *MockfileLockRepository) DeleteByBranch(ctx context.Context, projectID, branchID snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByBranch", ctx, projectID, branchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByBranch indicates an expected call of DeleteByBranch.
func (mr *MockfileLockRepositoryMockRecorder) DeleteByBranch(ctx, projectID, branchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByBranch", reflect.TypeOf((*MockfileLockRepository)(nil).DeleteByBranch), ctx, projectID, branchID)
}

// DeleteByMergeRequest mocks base method.
func (m *MockfileLockRepository) DeleteByMergeRequest(ctx context.Context, projectID, mergeRequestID snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByMergeRequest", ctx, projectID, mergeRequestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByMergeRequest indicates an expected call of DeleteByMergeRequest.
func (mr *MockfileLockRepositoryMockRecorder) DeleteByMergeRequest(ctx, projectID, mergeRequestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByMergeRequest", reflect.TypeOf((*MockfileLockRepository)(nil).DeleteByMergeRequest), ctx, projectID, mergeRequestID)
}

// Get mocks base method.
func (m *MockfileLockRepository) Get(ctx context.Context, projectID snow.ID, path string, branchID *snow.ID) (*domain.FileLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, projectID, path, branchID)
	ret0, _ := ret[0].(*domain.FileLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockfileLockRepositoryMockRecorder) Get(ctx, projectID, path, branchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockfileLockRepository)(nil).Get), ctx, projectID, path, branchID)
}

// ListProject mocks base method.
func (m *MockfileLockRepository) ListProject(ctx context.Context, projectID snow.ID) ([]*domain.FileLock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProject", ctx, projectID)
	ret0, _ := ret[0].([]*domain.FileLock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProject indicates an expected call of ListProject.
func (mr *MockfileLockRepositoryMockRecorder) ListProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProject", reflect.TypeOf((*MockfileLockRepository)(nil).ListProject), ctx, projectID)
}

// MockfileLockGate is a mock of fileLockGate interface.
type MockfileLockGate struct {
	ctrl     *gomock.Controller
	recorder *MockfileLockGateMockRecorder
	isgomock struct{}
}

// MockfileLockGateMockRecorder is the mock recorder for MockfileLockGate.
type MockfileLockGateMockRecorder struct {
	mock *MockfileLockGate
}

// NewMockfileLockGate creates a new mock instance.
func NewMockfileLockGate(ctrl *gomock.Controller) *MockfileLockGate {
	mock := &MockfileLockGate{ctrl: ctrl}
	mock.recorder = &MockfileLockGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileLockGate) EXPECT() *MockfileLockGateMockRecorder {
	return m.recorder
}

// EnsureLocks mocks base method.
func (m *MockfileLockGate) EnsureLocks(ctx context.Context, projectID snow.ID, branch *domain.Branch, required, checked []string, holder snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureLocks", ctx, projectID, branch, required, checked, holder)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureLocks indicates an expected call of EnsureLocks.
func (mr *MockfileLockGateMockRecorder) EnsureLocks(ctx, projectID, branch, required, checked, holder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureLocks", reflect.TypeOf((*MockfileLockGate)(nil).EnsureLocks), ctx, projectID, branch, required, checked, holder)
}

// EnsureMergeRequestLocks mocks base method.
func (m *MockfileLockGate) EnsureMergeRequestLocks(ctx context.Context, projectID, mergeRequestID snow.ID, target *domain.Branch, paths []string, holder, author snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureMergeRequestLocks", ctx, projectID, mergeRequestID, target, paths, holder, author)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureMergeRequestLocks indicates an expected call of EnsureMergeRequestLocks.
func (mr *MockfileLockGateMockRecorder) EnsureMergeRequestLocks(ctx, projectID, mergeRequestID, target, paths, holder, author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureMergeRequestLocks", reflect.TypeOf((*MockfileLockGate)(nil).EnsureMergeRequestLocks), ctx, projectID, mergeRequestID, target, paths, holder, author)
}

// ReleaseBranch mocks base method.
func (m *MockfileLockGate) ReleaseBranch(ctx context.Context, projectID, branchID snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseBranch", ctx, projectID, branchID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseBranch indicates an expected call of ReleaseBranch.
func (mr *MockfileLockGateMockRecorder) ReleaseBranch(ctx, projectID, branchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseBranch", reflect.TypeOf((*MockfileLockGate)(nil).ReleaseBranch), ctx, projectID, branchID)
}

// ReleaseForMergeRequest mocks base method.
func (m *MockfileLockGate) ReleaseForMergeRequest(ctx context.Context, projectID, mergeRequestID snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseForMergeRequest", ctx, projectID, mergeRequestID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseForMergeRequest indicates an expected call of ReleaseForMergeRequest.
func (mr *MockfileLockGateMockRecorder) ReleaseForMergeRequest(ctx, projectID, mergeRequestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseForMergeRequest", reflect.TypeOf((*MockfileLockGate)(nil).ReleaseForMergeRequest), ctx, projectID, mergeRequestID)
}

// ReleaseLanded mocks base method.
func (m *MockfileLockGate) ReleaseLanded(ctx context.Context, projectID snow.ID, branch *domain.Branch, paths []string, holder snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseLanded", ctx, projectID, branch, paths, holder)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseLanded indicates an expected call of ReleaseLanded.
func (mr *MockfileLockGateMockRecorder) ReleaseLanded(ctx, projectID, branch, paths, holder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseLanded", reflect.TypeOf((*MockfileLockGate)(nil).ReleaseLanded), ctx, projectID, branch, paths, holder)
}
