// Code generated by MockGen. DO NOT EDIT.
// Source: merge_request.go
//
// Generated by this command:
//
//	mockgen -source=merge_request.go -destination=merge_request_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	diff "github.com/nipalab/nipa/internal/diff"
	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockmergeRequestRepository is a mock of mergeRequestRepository interface.
type MockmergeRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockmergeRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockmergeRequestRepositoryMockRecorder is the mock recorder for MockmergeRequestRepository.
type MockmergeRequestRepositoryMockRecorder struct {
	mock *MockmergeRequestRepository
}

// NewMockmergeRequestRepository creates a new mock instance.
func NewMockmergeRequestRepository(ctrl *gomock.Controller) *MockmergeRequestRepository {
	mock := &MockmergeRequestRepository{ctrl: ctrl}
	mock.recorder = &MockmergeRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmergeRequestRepository) EXPECT() *MockmergeRequestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockmergeRequestRepository) Create(ctx context.Context, mr domain.MergeRequest) (*domain.MergeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, mr)
	ret0, _ := ret[0].(*domain.MergeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr_2 *MockmergeRequestRepositoryMockRecorder) Create(ctx, mr any) *gomock.Call {
	mr_2.mock.ctrl.T.Helper()
	return mr_2.mock.ctrl.RecordCallWithMethodType(mr_2.mock, "Create", reflect.TypeOf((*MockmergeRequestRepository)(nil).Create), ctx, mr)
}

// Get mocks base method.
func (m *MockmergeRequestRepository) Get(ctx context.Context, projectID snow.ID, number int64) (*domain.MergeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, projectID, number)
	ret0, _ := ret[0].(*domain.MergeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockmergeRequestRepositoryMockRecorder) Get(ctx, projectID, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockmergeRequestRepository)(nil).Get), ctx, projectID, number)
}

// List mocks base method.
func (m *MockmergeRequestRepository) List(ctx context.Context, projectID snow.ID, status string, limit int) ([]*domain.MergeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, projectID, status, limit)
	ret0, _ := ret[0].([]*domain.MergeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockmergeRequestRepositoryMockRecorder) List(ctx, projectID, status, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockmergeRequestRepository)(nil).List), ctx, projectID, status, limit)
}

// Update mocks base method.
func (m *MockmergeRequestRepository) Update(ctx context.Context, projectID snow.ID, number int64, title, description string) (*domain.MergeRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, projectID, number, title, description)
	ret0, _ := ret[0].(*domain.MergeRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockmergeRequestRepositoryMockRecorder) Update(ctx, projectID, number, title, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockmergeRequestRepository)(nil).Update), ctx, projectID, number, title, description)
}

// UpdateStatus mocks base method.
func (m *MockmergeRequestRepository) UpdateStatus(ctx context.Context, projectID snow.ID, number int64, status string, mergeCommitID *snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, projectID, number, status, mergeCommitID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockmergeRequestRepositoryMockRecorder) UpdateStatus(ctx, projectID, number, status, mergeCommitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockmergeRequestRepository)(nil).UpdateStatus), ctx, projectID, number, status, mergeCommitID)
}

// MockbranchMerger is a mock of branchMerger interface.
type MockbranchMerger struct {
	ctrl     *gomock.Controller
	recorder *MockbranchMergerMockRecorder
	isgomock struct{}
}

// MockbranchMergerMockRecorder is the mock recorder for MockbranchMerger.
type MockbranchMergerMockRecorder struct {
	mock *MockbranchMerger
}

// NewMockbranchMerger creates a new mock instance.
func NewMockbranchMerger(ctrl *gomock.Controller) *MockbranchMerger {
	mock := &MockbranchMerger{ctrl: ctrl}
	mock.recorder = &MockbranchMergerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbranchMerger) EXPECT() *MockbranchMergerMockRecorder {
	return m.recorder
}

// BinaryChangesBetween mocks base method.
func (m *MockbranchMerger) BinaryChangesBetween(ctx context.Context, projectID snow.ID, fromCommitID, toCommitID *snow.ID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BinaryChangesBetween", ctx, projectID, fromCommitID, toCommitID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BinaryChangesBetween indicates an expected call of BinaryChangesBetween.
func (mr *MockbranchMergerMockRecorder) BinaryChangesBetween(ctx, projectID, fromCommitID, toCommitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BinaryChangesBetween", reflect.TypeOf((*MockbranchMerger)(nil).BinaryChangesBetween), ctx, projectID, fromCommitID, toCommitID)
}

// FastForwardForMergeRequest mocks base method.
func (m *MockbranchMerger) FastForwardForMergeRequest(ctx context.Context, projectID snow.ID, targetBranch, sourceBranch string) (*domain.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FastForwardForMergeRequest", ctx, projectID, targetBranch, sourceBranch)
	ret0, _ := ret[0].(*domain.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FastForwardForMergeRequest indicates an expected call of FastForwardForMergeRequest.
func (mr *MockbranchMergerMockRecorder) FastForwardForMergeRequest(ctx, projectID, targetBranch, sourceBranch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FastForwardForMergeRequest", reflect.TypeOf((*MockbranchMerger)(nil).FastForwardForMergeRequest), ctx, projectID, targetBranch, sourceBranch)
}

// GetMergeBase mocks base method.
func (m *MockbranchMerger) GetMergeBase(ctx context.Context, projectID snow.ID, target, source MergeRef) (*MergeBaseInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMergeBase", ctx, projectID, target, source)
	ret0, _ := ret[0].(*MergeBaseInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMergeBase indicates an expected call of GetMergeBase.
func (mr *MockbranchMergerMockRecorder) GetMergeBase(ctx, projectID, target, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMergeBase", reflect.TypeOf((*MockbranchMerger)(nil).GetMergeBase), ctx, projectID, target, source)
}

// TreeDiffBetween mocks base method.
func (m *MockbranchMerger) TreeDiffBetween(ctx context.Context, projectID snow.ID, baseID *snow.ID, headID snow.ID) ([]diff.FileDiff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TreeDiffBetween", ctx, projectID, baseID, headID)
	ret0, _ := ret[0].([]diff.FileDiff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TreeDiffBetween indicates an expected call of TreeDiffBetween.
func (mr *MockbranchMergerMockRecorder) TreeDiffBetween(ctx, projectID, baseID, headID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TreeDiffBetween", reflect.TypeOf((*MockbranchMerger)(nil).TreeDiffBetween), ctx, projectID, baseID, headID)
}
