// Code generated by MockGen. DO NOT EDIT.
// Source: merge_request_check.go
//
// Generated by this command:
//
//	mockgen -source=merge_request_check.go -destination=merge_request_check_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockmergeRequestCheckRepository is a mock of mergeRequestCheckRepository interface.
type MockmergeRequestCheckRepository struct {
	ctrl     *gomock.Controller
	recorder *MockmergeRequestCheckRepositoryMockRecorder
	isgomock struct{}
}

// MockmergeRequestCheckRepositoryMockRecorder is the mock recorder for MockmergeRequestCheckRepository.
type MockmergeRequestCheckRepositoryMockRecorder struct {
	mock *MockmergeRequestCheckRepository
}

// NewMockmergeRequestCheckRepository creates a new mock instance.
func NewMockmergeRequestCheckRepository(ctrl *gomock.Controller) *MockmergeRequestCheckRepository {
	mock := &MockmergeRequestCheckRepository{ctrl: ctrl}
	mock.recorder = &MockmergeRequestCheckRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmergeRequestCheckRepository) EXPECT() *MockmergeRequestCheckRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockmergeRequestCheckRepository) List(ctx context.Context, mergeRequestID int64, headCommitID snow.ID) ([]*domain.MergeRequestCheck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, mergeRequestID, headCommitID)
	ret0, _ := ret[0].([]*domain.MergeRequestCheck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockmergeRequestCheckRepositoryMockRecorder) List(ctx, mergeRequestID, headCommitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockmergeRequestCheckRepository)(nil).List), ctx, mergeRequestID, headCommitID)
}

// Upsert mocks base method.
func (m *MockmergeRequestCheckRepository) Upsert(ctx context.Context, check domain.MergeRequestCheck) (*domain.MergeRequestCheck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, check)
	ret0, _ := ret[0].(*domain.MergeRequestCheck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockmergeRequestCheckRepositoryMockRecorder) Upsert(ctx, check any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockmergeRequestCheckRepository)(nil).Upsert), ctx, check)
}
