// Code generated by MockGen. DO NOT EDIT.
// Source: notifier.go
//
// Generated by this command:
//
//	mockgen -source=notifier.go -destination=notifier_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MocknotifierOutbox is a mock of notifierOutbox interface.
type MocknotifierOutbox struct {
	ctrl     *gomock.Controller
	recorder *MocknotifierOutboxMockRecorder
	isgomock struct{}
}

// MocknotifierOutboxMockRecorder is the mock recorder for MocknotifierOutbox.
type MocknotifierOutboxMockRecorder struct {
	mock *MocknotifierOutbox
}

// NewMocknotifierOutbox creates a new mock instance.
func NewMocknotifierOutbox(ctrl *gomock.Controller) *MocknotifierOutbox {
	mock := &MocknotifierOutbox{ctrl: ctrl}
	mock.recorder = &MocknotifierOutboxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknotifierOutbox) EXPECT() *MocknotifierOutboxMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MocknotifierOutbox) Enqueue(ctx context.Context, deliveries []*domain.EmailDelivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, deliveries)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MocknotifierOutboxMockRecorder) Enqueue(ctx, deliveries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MocknotifierOutbox)(nil).Enqueue), ctx, deliveries)
}

// ThreadRecipients mocks base method.
func (m *MocknotifierOutbox) ThreadRecipients(ctx context.Context, projectID snow.ID, threadKey string) (map[snow.ID]struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ThreadRecipients", ctx, projectID, threadKey)
	ret0, _ := ret[0].(map[snow.ID]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ThreadRecipients indicates an expected call of ThreadRecipients.
func (mr *MocknotifierOutboxMockRecorder) ThreadRecipients(ctx, projectID, threadKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ThreadRecipients", reflect.TypeOf((*MocknotifierOutbox)(nil).ThreadRecipients), ctx, projectID, threadKey)
}

// MocknotifierMRRepository is a mock of notifierMRRepository interface.
type MocknotifierMRRepository struct {
	ctrl     *gomock.Controller
	recorder *MocknotifierMRRepositoryMockRecorder
	isgomock struct{}
}

// MocknotifierMRRepositoryMockRecorder is the mock recorder for MocknotifierMRRepository.
type MocknotifierMRRepositoryMockRecorder struct {
	mock *MocknotifierMRRepository
}

// NewMocknotifierMRRepository creates a new mock instance.
func NewMocknotifierMRRepository(ctrl *gomock.Controller) *MocknotifierMRRepository {
	mock := &MocknotifierMRRepository{ctrl: ctrl}
	mock.recorder = &MocknotifierMRRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknotifierMRRepository) EXPECT() *MocknotifierMRRepositoryMockRecorder {
	return m.recorder
}

// ListAssigneesByMergeRequest mocks base method.
func (m *MocknotifierMRRepository) ListAssigneesByMergeRequest(ctx context.Context, mergeRequestID int64) ([]domain.ReviewActor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAssigneesByMergeRequest", ctx, mergeRequestID)
	ret0, _ := ret[0].([]domain.ReviewActor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAssigneesByMergeRequest indicates an expected call of ListAssigneesByMergeRequest.
func (mr *MocknotifierMRRepositoryMockRecorder) ListAssigneesByMergeRequest(ctx, mergeRequestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAssigneesByMergeRequest", reflect.TypeOf((*MocknotifierMRRepository)(nil).ListAssigneesByMergeRequest), ctx, mergeRequestID)
}

// MocknotifierReviewRepository is a mock of notifierReviewRepository interface.
type MocknotifierReviewRepository struct {
	ctrl     *gomock.Controller
	recorder *MocknotifierReviewRepositoryMockRecorder
	isgomock struct{}
}

// MocknotifierReviewRepositoryMockRecorder is the mock recorder for MocknotifierReviewRepository.
type MocknotifierReviewRepositoryMockRecorder struct {
	mock *MocknotifierReviewRepository
}

// NewMocknotifierReviewRepository creates a new mock instance.
func NewMocknotifierReviewRepository(ctrl *gomock.Controller) *MocknotifierReviewRepository {
	mock := &MocknotifierReviewRepository{ctrl: ctrl}
	mock.recorder = &MocknotifierReviewRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknotifierReviewRepository) EXPECT() *MocknotifierReviewRepositoryMockRecorder {
	return m.recorder
}

// ListComments mocks base method.
func (m *MocknotifierReviewRepository) ListComments(ctx context.Context, mergeRequestID int64) ([]*domain.MergeRequestComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", ctx, mergeRequestID)
	ret0, _ := ret[0].([]*domain.MergeRequestComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MocknotifierReviewRepositoryMockRecorder) ListComments(ctx, mergeRequestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MocknotifierReviewRepository)(nil).ListComments), ctx, mergeRequestID)
}

// ListReviewRequests mocks base method.
func (m *MocknotifierReviewRepository) ListReviewRequests(ctx context.Context, mergeRequestID int64) ([]*domain.MergeRequestReviewRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviewRequests", ctx, mergeRequestID)
	ret0, _ := ret[0].([]*domain.MergeRequestReviewRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReviewRequests indicates an expected call of ListReviewRequests.
func (mr *MocknotifierReviewRepositoryMockRecorder) ListReviewRequests(ctx, mergeRequestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviewRequests", reflect.TypeOf((*MocknotifierReviewRepository)(nil).ListReviewRequests), ctx, mergeRequestID)
}

// MockdispatcherKicker is a mock of dispatcherKicker interface.
type MockdispatcherKicker struct {
	ctrl     *gomock.Controller
	recorder *MockdispatcherKickerMockRecorder
	isgomock struct{}
}

// MockdispatcherKickerMockRecorder is the mock recorder for MockdispatcherKicker.
type MockdispatcherKickerMockRecorder struct {
	mock *MockdispatcherKicker
}

// NewMockdispatcherKicker creates a new mock instance.
func NewMockdispatcherKicker(ctrl *gomock.Controller) *MockdispatcherKicker {
	mock := &MockdispatcherKicker{ctrl: ctrl}
	mock.recorder = &MockdispatcherKickerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdispatcherKicker) EXPECT() *MockdispatcherKickerMockRecorder {
	return m.recorder
}

// Kick mocks base method.
func (m *MockdispatcherKicker) Kick() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Kick")
}

// Kick indicates an expected call of Kick.
func (mr *MockdispatcherKickerMockRecorder) Kick() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kick", reflect.TypeOf((*MockdispatcherKicker)(nil).Kick))
}
