// Code generated by MockGen. DO NOT EDIT.
// Source: project.go
//
// Generated by this command:
//
//	mockgen -source=project.go -destination=project_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockprojectRepository is a mock of projectRepository interface.
type MockprojectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockprojectRepositoryMockRecorder
	isgomock struct{}
}

// MockprojectRepositoryMockRecorder is the mock recorder for MockprojectRepository.
type MockprojectRepositoryMockRecorder struct {
	mock *MockprojectRepository
}

// NewMockprojectRepository creates a new mock instance.
func NewMockprojectRepository(ctrl *gomock.Controller) *MockprojectRepository {
	mock := &MockprojectRepository{ctrl: ctrl}
	mock.recorder = &MockprojectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprojectRepository) EXPECT() *MockprojectRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockprojectRepository) Create(ctx context.Context, project domain.Project) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, project)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockprojectRepositoryMockRecorder) Create(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockprojectRepository)(nil).Create), ctx, project)
}

// Delete mocks base method.
func (m *MockprojectRepository) Delete(ctx context.Context, id snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockprojectRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockprojectRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockprojectRepository) Get(ctx context.Context, id snow.ID) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockprojectRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockprojectRepository)(nil).Get), ctx, id)
}

// GetByOrgIDAndSlug mocks base method.
func (m *MockprojectRepository) GetByOrgIDAndSlug(ctx context.Context, orgID snow.ID, slug string) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByOrgIDAndSlug", ctx, orgID, slug)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByOrgIDAndSlug indicates an expected call of GetByOrgIDAndSlug.
func (mr *MockprojectRepositoryMockRecorder) GetByOrgIDAndSlug(ctx, orgID, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByOrgIDAndSlug", reflect.TypeOf((*MockprojectRepository)(nil).GetByOrgIDAndSlug), ctx, orgID, slug)
}

// ListByOrgID mocks base method.
func (m *MockprojectRepository) ListByOrgID(ctx context.Context, orgID snow.ID) ([]domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrgID", ctx, orgID)
	ret0, _ := ret[0].([]domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOrgID indicates an expected call of ListByOrgID.
func (mr *MockprojectRepositoryMockRecorder) ListByOrgID(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrgID", reflect.TypeOf((*MockprojectRepository)(nil).ListByOrgID), ctx, orgID)
}

// Update mocks base method.
func (m *MockprojectRepository) Update(ctx context.Context, project domain.Project) (*domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, project)
	ret0, _ := ret[0].(*domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockprojectRepositoryMockRecorder) Update(ctx, project any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockprojectRepository)(nil).Update), ctx, project)
}

// MockprojectAccess is a mock of projectAccess interface.
type MockprojectAccess struct {
	ctrl     *gomock.Controller
	recorder *MockprojectAccessMockRecorder
	isgomock struct{}
}

// MockprojectAccessMockRecorder is the mock recorder for MockprojectAccess.
type MockprojectAccessMockRecorder struct {
	mock *MockprojectAccess
}

// NewMockprojectAccess creates a new mock instance.
func NewMockprojectAccess(ctrl *gomock.Controller) *MockprojectAccess {
	mock := &MockprojectAccess{ctrl: ctrl}
	mock.recorder = &MockprojectAccessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprojectAccess) EXPECT() *MockprojectAccessMockRecorder {
	return m.recorder
}

// AdminHasProject mocks base method.
func (m *MockprojectAccess) AdminHasProject(ctx context.Context, projectID snow.ID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminHasProject", ctx, projectID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AdminHasProject indicates an expected call of AdminHasProject.
func (mr *MockprojectAccessMockRecorder) AdminHasProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminHasProject", reflect.TypeOf((*MockprojectAccess)(nil).AdminHasProject), ctx, projectID)
}

// HasProjectAccess mocks base method.
func (m *MockprojectAccess) HasProjectAccess(ctx context.Context, projectID snow.ID, permission domain.Permission) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProjectAccess", ctx, projectID, permission)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasProjectAccess indicates an expected call of HasProjectAccess.
func (mr *MockprojectAccessMockRecorder) HasProjectAccess(ctx, projectID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProjectAccess", reflect.TypeOf((*MockprojectAccess)(nil).HasProjectAccess), ctx, projectID, permission)
}
