// Code generated by MockGen. DO NOT EDIT.
// Source: push.go
//
// Generated by this command:
//
//	mockgen -source=push.go -destination=push_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockpushRepository is a mock of pushRepository interface.
type MockpushRepository struct {
	ctrl     *gomock.Controller
	recorder *MockpushRepositoryMockRecorder
	isgomock struct{}
}

// MockpushRepositoryMockRecorder is the mock recorder for MockpushRepository.
type MockpushRepositoryMockRecorder struct {
	mock *MockpushRepository
}

// NewMockpushRepository creates a new mock instance.
func NewMockpushRepository(ctrl *gomock.Controller) *MockpushRepository {
	mock := &MockpushRepository{ctrl: ctrl}
	mock.recorder = &MockpushRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpushRepository) EXPECT() *MockpushRepositoryMockRecorder {
	return m.recorder
}

// ApplyPush mocks base method.
func (m *MockpushRepository) ApplyPush(ctx context.Context, req ApplyPushRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyPush", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyPush indicates an expected call of ApplyPush.
func (mr *MockpushRepositoryMockRecorder) ApplyPush(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPush", reflect.TypeOf((*MockpushRepository)(nil).ApplyPush), ctx, req)
}

// MockreviewPushGate is a mock of reviewPushGate interface.
type MockreviewPushGate struct {
	ctrl     *gomock.Controller
	recorder *MockreviewPushGateMockRecorder
	isgomock struct{}
}

// MockreviewPushGateMockRecorder is the mock recorder for MockreviewPushGate.
type MockreviewPushGateMockRecorder struct {
	mock *MockreviewPushGate
}

// NewMockreviewPushGate creates a new mock instance.
func NewMockreviewPushGate(ctrl *gomock.Controller) *MockreviewPushGate {
	mock := &MockreviewPushGate{ctrl: ctrl}
	mock.recorder = &MockreviewPushGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreviewPushGate) EXPECT() *MockreviewPushGateMockRecorder {
	return m.recorder
}

// NoteBranchPush mocks base method.
func (m *MockreviewPushGate) NoteBranchPush(ctx context.Context, projectID, branchID, newHead, actor snow.ID, commitHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoteBranchPush", ctx, projectID, branchID, newHead, actor, commitHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// NoteBranchPush indicates an expected call of NoteBranchPush.
func (mr *MockreviewPushGateMockRecorder) NoteBranchPush(ctx, projectID, branchID, newHead, actor, commitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoteBranchPush", reflect.TypeOf((*MockreviewPushGate)(nil).NoteBranchPush), ctx, projectID, branchID, newHead, actor, commitHash)
}
