// Code generated by MockGen. DO NOT EDIT.
// Source: storage_ledger.go
//
// Generated by this command:
//
//	mockgen -source=storage_ledger.go -destination=storage_ledger_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageLedger is a mock of StorageLedger interface.
type MockStorageLedger struct {
	ctrl     *gomock.Controller
	recorder *MockStorageLedgerMockRecorder
	isgomock struct{}
}

// MockStorageLedgerMockRecorder is the mock recorder for MockStorageLedger.
type MockStorageLedgerMockRecorder struct {
	mock *MockStorageLedger
}

// NewMockStorageLedger creates a new mock instance.
func NewMockStorageLedger(ctrl *gomock.Controller) *MockStorageLedger {
	mock := &MockStorageLedger{ctrl: ctrl}
	mock.recorder = &MockStorageLedgerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageLedger) EXPECT() *MockStorageLedgerMockRecorder {
	return m.recorder
}

// Attribute mocks base method.
func (m *MockStorageLedger) Attribute(ctx context.Context, org *domain.Organization, project *domain.Project, chunks []LedgerChunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attribute", ctx, org, project, chunks)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attribute indicates an expected call of Attribute.
func (mr *MockStorageLedgerMockRecorder) Attribute(ctx, org, project, chunks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attribute", reflect.TypeOf((*MockStorageLedger)(nil).Attribute), ctx, org, project, chunks)
}

// AttributedSizes mocks base method.
func (m *MockStorageLedger) AttributedSizes(ctx context.Context, projectID snow.ID, hashes []domain.Hash) (map[domain.Hash]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttributedSizes", ctx, projectID, hashes)
	ret0, _ := ret[0].(map[domain.Hash]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttributedSizes indicates an expected call of AttributedSizes.
func (mr *MockStorageLedgerMockRecorder) AttributedSizes(ctx, projectID, hashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttributedSizes", reflect.TypeOf((*MockStorageLedger)(nil).AttributedSizes), ctx, projectID, hashes)
}

// Headroom mocks base method.
func (m *MockStorageLedger) Headroom(ctx context.Context, org *domain.Organization, project *domain.Project, projectedNewBytes int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Headroom", ctx, org, project, projectedNewBytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// Headroom indicates an expected call of Headroom.
func (mr *MockStorageLedgerMockRecorder) Headroom(ctx, org, project, projectedNewBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Headroom", reflect.TypeOf((*MockStorageLedger)(nil).Headroom), ctx, org, project, projectedNewBytes)
}
