// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=user_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockuserAdminRepository is a mock of userAdminRepository interface.
type MockuserAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserAdminRepositoryMockRecorder
	isgomock struct{}
}

// MockuserAdminRepositoryMockRecorder is the mock recorder for MockuserAdminRepository.
type MockuserAdminRepositoryMockRecorder struct {
	mock *MockuserAdminRepository
}

// NewMockuserAdminRepository creates a new mock instance.
func NewMockuserAdminRepository(ctrl *gomock.Controller) *MockuserAdminRepository {
	mock := &MockuserAdminRepository{ctrl: ctrl}
	mock.recorder = &MockuserAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserAdminRepository) EXPECT() *MockuserAdminRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockuserAdminRepository) Create(ctx context.Context, user domain.User) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockuserAdminRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuserAdminRepository)(nil).Create), ctx, user)
}

// Deactivate mocks base method.
func (m *MockuserAdminRepository) Deactivate(ctx context.Context, id snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deactivate", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deactivate indicates an expected call of Deactivate.
func (mr *MockuserAdminRepositoryMockRecorder) Deactivate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deactivate", reflect.TypeOf((*MockuserAdminRepository)(nil).Deactivate), ctx, id)
}

// GetByEmail mocks base method.
func (m *MockuserAdminRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockuserAdminRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockuserAdminRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockuserAdminRepository) GetByID(ctx context.Context, id snow.ID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserAdminRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserAdminRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockuserAdminRepository) List(ctx context.Context) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockuserAdminRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockuserAdminRepository)(nil).List), ctx)
}

// UpdateAdminFlags mocks base method.
func (m *MockuserAdminRepository) UpdateAdminFlags(ctx context.Context, id snow.ID, isAdmin, isSuperAdmin bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminFlags", ctx, id, isAdmin, isSuperAdmin)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdminFlags indicates an expected call of UpdateAdminFlags.
func (mr *MockuserAdminRepositoryMockRecorder) UpdateAdminFlags(ctx, id, isAdmin, isSuperAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminFlags", reflect.TypeOf((*MockuserAdminRepository)(nil).UpdateAdminFlags), ctx, id, isAdmin, isSuperAdmin)
}

// UpdateEmail mocks base method.
func (m *MockuserAdminRepository) UpdateEmail(ctx context.Context, id snow.ID, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmail", ctx, id, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmail indicates an expected call of UpdateEmail.
func (mr *MockuserAdminRepositoryMockRecorder) UpdateEmail(ctx, id, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmail", reflect.TypeOf((*MockuserAdminRepository)(nil).UpdateEmail), ctx, id, email)
}

// UpdatePassword mocks base method.
func (m *MockuserAdminRepository) UpdatePassword(ctx context.Context, id snow.ID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, id, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockuserAdminRepositoryMockRecorder) UpdatePassword(ctx, id, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockuserAdminRepository)(nil).UpdatePassword), ctx, id, passwordHash)
}

// UpdateProfile mocks base method.
func (m *MockuserAdminRepository) UpdateProfile(ctx context.Context, id snow.ID, name, photoUrl string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, id, name, photoUrl)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockuserAdminRepositoryMockRecorder) UpdateProfile(ctx, id, name, photoUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockuserAdminRepository)(nil).UpdateProfile), ctx, id, name, photoUrl)
}
