// Code generated by MockGen. DO NOT EDIT.
// Source: webhook.go
//
// Generated by this command:
//
//	mockgen -source=webhook.go -destination=webhook_mock_test.go -package=usecase
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockwebhookRepository is a mock of webhookRepository interface.
type MockwebhookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockwebhookRepositoryMockRecorder
	isgomock struct{}
}

// MockwebhookRepositoryMockRecorder is the mock recorder for MockwebhookRepository.
type MockwebhookRepositoryMockRecorder struct {
	mock *MockwebhookRepository
}

// NewMockwebhookRepository creates a new mock instance.
func NewMockwebhookRepository(ctrl *gomock.Controller) *MockwebhookRepository {
	mock := &MockwebhookRepository{ctrl: ctrl}
	mock.recorder = &MockwebhookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwebhookRepository) EXPECT() *MockwebhookRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockwebhookRepository) Create(ctx context.Context, webhook domain.Webhook) (*domain.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, webhook)
	ret0, _ := ret[0].(*domain.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockwebhookRepositoryMockRecorder) Create(ctx, webhook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockwebhookRepository)(nil).Create), ctx, webhook)
}

// Delete mocks base method.
func (m *MockwebhookRepository) Delete(ctx context.Context, projectID, id snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, projectID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockwebhookRepositoryMockRecorder) Delete(ctx, projectID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockwebhookRepository)(nil).Delete), ctx, projectID, id)
}

// Get mocks base method.
func (m *MockwebhookRepository) Get(ctx context.Context, projectID, id snow.ID) (*domain.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, projectID, id)
	ret0, _ := ret[0].(*domain.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockwebhookRepositoryMockRecorder) Get(ctx, projectID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockwebhookRepository)(nil).Get), ctx, projectID, id)
}

// ListByProject mocks base method.
func (m *MockwebhookRepository) ListByProject(ctx context.Context, projectID snow.ID) ([]*domain.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByProject", ctx, projectID)
	ret0, _ := ret[0].([]*domain.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByProject indicates an expected call of ListByProject.
func (mr *MockwebhookRepositoryMockRecorder) ListByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByProject", reflect.TypeOf((*MockwebhookRepository)(nil).ListByProject), ctx, projectID)
}

// RotateSecret mocks base method.
func (m *MockwebhookRepository) RotateSecret(ctx context.Context, projectID, id snow.ID, secret string) (*domain.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateSecret", ctx, projectID, id, secret)
	ret0, _ := ret[0].(*domain.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateSecret indicates an expected call of RotateSecret.
func (mr *MockwebhookRepositoryMockRecorder) RotateSecret(ctx, projectID, id, secret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateSecret", reflect.TypeOf((*MockwebhookRepository)(nil).RotateSecret), ctx, projectID, id, secret)
}

// Update mocks base method.
func (m *MockwebhookRepository) Update(ctx context.Context, webhook domain.Webhook) (*domain.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, webhook)
	ret0, _ := ret[0].(*domain.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockwebhookRepositoryMockRecorder) Update(ctx, webhook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockwebhookRepository)(nil).Update), ctx, webhook)
}
