// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/branch.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/branch.go -destination=internal/grpc/server/branch_usecase_mock_test.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockpermissionUsecase is a mock of permissionUsecase interface.
type MockpermissionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockpermissionUsecaseMockRecorder
	isgomock struct{}
}

// MockpermissionUsecaseMockRecorder is the mock recorder for MockpermissionUsecase.
type MockpermissionUsecaseMockRecorder struct {
	mock *MockpermissionUsecase
}

// NewMockpermissionUsecase creates a new mock instance.
func NewMockpermissionUsecase(ctrl *gomock.Controller) *MockpermissionUsecase {
	mock := &MockpermissionUsecase{ctrl: ctrl}
	mock.recorder = &MockpermissionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpermissionUsecase) EXPECT() *MockpermissionUsecaseMockRecorder {
	return m.recorder
}

// HasProjectAccess mocks base method.
func (m *MockpermissionUsecase) HasProjectAccess(ctx context.Context, projectID snow.ID, permission domain.Permission) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasProjectAccess", ctx, projectID, permission)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasProjectAccess indicates an expected call of HasProjectAccess.
func (mr *MockpermissionUsecaseMockRecorder) HasProjectAccess(ctx, projectID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasProjectAccess", reflect.TypeOf((*MockpermissionUsecase)(nil).HasProjectAccess), ctx, projectID, permission)
}

// MockbranchRepository is a mock of branchRepository interface.
type MockbranchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockbranchRepositoryMockRecorder
	isgomock struct{}
}

// MockbranchRepositoryMockRecorder is the mock recorder for MockbranchRepository.
type MockbranchRepositoryMockRecorder struct {
	mock *MockbranchRepository
}

// NewMockbranchRepository creates a new mock instance.
func NewMockbranchRepository(ctrl *gomock.Controller) *MockbranchRepository {
	mock := &MockbranchRepository{ctrl: ctrl}
	mock.recorder = &MockbranchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbranchRepository) EXPECT() *MockbranchRepositoryMockRecorder {
	return m.recorder
}

// CreateBranch mocks base method.
func (m *MockbranchRepository) CreateBranch(ctx context.Context, branch domain.Branch) (*domain.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBranch", ctx, branch)
	ret0, _ := ret[0].(*domain.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBranch indicates an expected call of CreateBranch.
func (mr *MockbranchRepositoryMockRecorder) CreateBranch(ctx, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBranch", reflect.TypeOf((*MockbranchRepository)(nil).CreateBranch), ctx, branch)
}

// GetBranchByName mocks base method.
func (m *MockbranchRepository) GetBranchByName(ctx context.Context, projectID snow.ID, name string) (*domain.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranchByName", ctx, projectID, name)
	ret0, _ := ret[0].(*domain.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranchByName indicates an expected call of GetBranchByName.
func (mr *MockbranchRepositoryMockRecorder) GetBranchByName(ctx, projectID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranchByName", reflect.TypeOf((*MockbranchRepository)(nil).GetBranchByName), ctx, projectID, name)
}

// GetByProjectIDAndID mocks base method.
func (m *MockbranchRepository) GetByProjectIDAndID(ctx context.Context, projectID, branchID snow.ID) (*domain.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByProjectIDAndID", ctx, projectID, branchID)
	ret0, _ := ret[0].(*domain.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByProjectIDAndID indicates an expected call of GetByProjectIDAndID.
func (mr *MockbranchRepositoryMockRecorder) GetByProjectIDAndID(ctx, projectID, branchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByProjectIDAndID", reflect.TypeOf((*MockbranchRepository)(nil).GetByProjectIDAndID), ctx, projectID, branchID)
}

// GetCommit mocks base method.
func (m *MockbranchRepository) GetCommit(ctx context.Context, commitID snow.ID) (*domain.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommit", ctx, commitID)
	ret0, _ := ret[0].(*domain.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommit indicates an expected call of GetCommit.
func (mr *MockbranchRepositoryMockRecorder) GetCommit(ctx, commitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommit", reflect.TypeOf((*MockbranchRepository)(nil).GetCommit), ctx, commitID)
}

// GetCommitByHash mocks base method.
func (m *MockbranchRepository) GetCommitByHash(ctx context.Context, hash domain.Hash) (*domain.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitByHash", ctx, hash)
	ret0, _ := ret[0].(*domain.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitByHash indicates an expected call of GetCommitByHash.
func (mr *MockbranchRepositoryMockRecorder) GetCommitByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitByHash", reflect.TypeOf((*MockbranchRepository)(nil).GetCommitByHash), ctx, hash)
}

// GetDefaultBranch mocks base method.
func (m *MockbranchRepository) GetDefaultBranch(ctx context.Context, projectID snow.ID) (*domain.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultBranch", ctx, projectID)
	ret0, _ := ret[0].(*domain.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultBranch indicates an expected call of GetDefaultBranch.
func (mr *MockbranchRepositoryMockRecorder) GetDefaultBranch(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultBranch", reflect.TypeOf((*MockbranchRepository)(nil).GetDefaultBranch), ctx, projectID)
}

// GetTreeChildByName mocks base method.
func (m *MockbranchRepository) GetTreeChildByName(ctx context.Context, parentID int64, name string) (*domain.TreeNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreeChildByName", ctx, parentID, name)
	ret0, _ := ret[0].(*domain.TreeNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreeChildByName indicates an expected call of GetTreeChildByName.
func (mr *MockbranchRepositoryMockRecorder) GetTreeChildByName(ctx, parentID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreeChildByName", reflect.TypeOf((*MockbranchRepository)(nil).GetTreeChildByName), ctx, parentID, name)
}

// GetTreeNode mocks base method.
func (m *MockbranchRepository) GetTreeNode(ctx context.Context, id int64) (*domain.TreeNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreeNode", ctx, id)
	ret0, _ := ret[0].(*domain.TreeNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreeNode indicates an expected call of GetTreeNode.
func (mr *MockbranchRepositoryMockRecorder) GetTreeNode(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreeNode", reflect.TypeOf((*MockbranchRepository)(nil).GetTreeNode), ctx, id)
}

// ListBranches mocks base method.
func (m *MockbranchRepository) ListBranches(ctx context.Context, projectID snow.ID, limit int, updatedAfter *time.Time, lastID snow.ID) ([]*domain.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBranches", ctx, projectID, limit, updatedAfter, lastID)
	ret0, _ := ret[0].([]*domain.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBranches indicates an expected call of ListBranches.
func (mr *MockbranchRepositoryMockRecorder) ListBranches(ctx, projectID, limit, updatedAfter, lastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBranches", reflect.TypeOf((*MockbranchRepository)(nil).ListBranches), ctx, projectID, limit, updatedAfter, lastID)
}

// ListFilesByTree mocks base method.
func (m *MockbranchRepository) ListFilesByTree(ctx context.Context, treeID int64) ([]*domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFilesByTree", ctx, treeID)
	ret0, _ := ret[0].([]*domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilesByTree indicates an expected call of ListFilesByTree.
func (mr *MockbranchRepositoryMockRecorder) ListFilesByTree(ctx, treeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilesByTree", reflect.TypeOf((*MockbranchRepository)(nil).ListFilesByTree), ctx, treeID)
}

// ListTreeChildren mocks base method.
func (m *MockbranchRepository) ListTreeChildren(ctx context.Context, parentID int64) ([]*domain.TreeNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTreeChildren", ctx, parentID)
	ret0, _ := ret[0].([]*domain.TreeNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTreeChildren indicates an expected call of ListTreeChildren.
func (mr *MockbranchRepositoryMockRecorder) ListTreeChildren(ctx, parentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTreeChildren", reflect.TypeOf((*MockbranchRepository)(nil).ListTreeChildren), ctx, parentID)
}
