// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/org.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/org.go -destination=internal/grpc/server/org_repo_mock_test.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockorgMemberRepository is a mock of orgMemberRepository interface.
type MockorgMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockorgMemberRepositoryMockRecorder
	isgomock struct{}
}

// MockorgMemberRepositoryMockRecorder is the mock recorder for MockorgMemberRepository.
type MockorgMemberRepositoryMockRecorder struct {
	mock *MockorgMemberRepository
}

// NewMockorgMemberRepository creates a new mock instance.
func NewMockorgMemberRepository(ctrl *gomock.Controller) *MockorgMemberRepository {
	mock := &MockorgMemberRepository{ctrl: ctrl}
	mock.recorder = &MockorgMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorgMemberRepository) EXPECT() *MockorgMemberRepositoryMockRecorder {
	return m.recorder
}

// CountMembersByRole mocks base method.
func (m *MockorgMemberRepository) CountMembersByRole(ctx context.Context, orgID snow.ID, role string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMembersByRole", ctx, orgID, role)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMembersByRole indicates an expected call of CountMembersByRole.
func (mr *MockorgMemberRepositoryMockRecorder) CountMembersByRole(ctx, orgID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMembersByRole", reflect.TypeOf((*MockorgMemberRepository)(nil).CountMembersByRole), ctx, orgID, role)
}

// ListForUser mocks base method.
func (m *MockorgMemberRepository) ListForUser(ctx context.Context, userID snow.ID) ([]*domain.OrgMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForUser", ctx, userID)
	ret0, _ := ret[0].([]*domain.OrgMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListForUser indicates an expected call of ListForUser.
func (mr *MockorgMemberRepositoryMockRecorder) ListForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForUser", reflect.TypeOf((*MockorgMemberRepository)(nil).ListForUser), ctx, userID)
}

// ListMembers mocks base method.
func (m *MockorgMemberRepository) ListMembers(ctx context.Context, orgID snow.ID) ([]*domain.OrgMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, orgID)
	ret0, _ := ret[0].([]*domain.OrgMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockorgMemberRepositoryMockRecorder) ListMembers(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockorgMemberRepository)(nil).ListMembers), ctx, orgID)
}

// MemberRole mocks base method.
func (m *MockorgMemberRepository) MemberRole(ctx context.Context, orgID, userID snow.ID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemberRole", ctx, orgID, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemberRole indicates an expected call of MemberRole.
func (mr *MockorgMemberRepositoryMockRecorder) MemberRole(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemberRole", reflect.TypeOf((*MockorgMemberRepository)(nil).MemberRole), ctx, orgID, userID)
}

// RemoveMember mocks base method.
func (m *MockorgMemberRepository) RemoveMember(ctx context.Context, orgID, userID snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", ctx, orgID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockorgMemberRepositoryMockRecorder) RemoveMember(ctx, orgID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockorgMemberRepository)(nil).RemoveMember), ctx, orgID, userID)
}

// UpsertMember mocks base method.
func (m *MockorgMemberRepository) UpsertMember(ctx context.Context, orgID, userID snow.ID, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertMember", ctx, orgID, userID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertMember indicates an expected call of UpsertMember.
func (mr *MockorgMemberRepositoryMockRecorder) UpsertMember(ctx, orgID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertMember", reflect.TypeOf((*MockorgMemberRepository)(nil).UpsertMember), ctx, orgID, userID, role)
}

// MockorgAuthorizer is a mock of orgAuthorizer interface.
type MockorgAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockorgAuthorizerMockRecorder
	isgomock struct{}
}

// MockorgAuthorizerMockRecorder is the mock recorder for MockorgAuthorizer.
type MockorgAuthorizerMockRecorder struct {
	mock *MockorgAuthorizer
}

// NewMockorgAuthorizer creates a new mock instance.
func NewMockorgAuthorizer(ctrl *gomock.Controller) *MockorgAuthorizer {
	mock := &MockorgAuthorizer{ctrl: ctrl}
	mock.recorder = &MockorgAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorgAuthorizer) EXPECT() *MockorgAuthorizerMockRecorder {
	return m.recorder
}

// IsOrgOwner mocks base method.
func (m *MockorgAuthorizer) IsOrgOwner(ctx context.Context, orgID snow.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOrgOwner", ctx, orgID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsOrgOwner indicates an expected call of IsOrgOwner.
func (mr *MockorgAuthorizerMockRecorder) IsOrgOwner(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOrgOwner", reflect.TypeOf((*MockorgAuthorizer)(nil).IsOrgOwner), ctx, orgID)
}
