// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/permission.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/permission.go -destination=internal/grpc/server/permission_repo_mock_test.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MockpbacRepository is a mock of pbacRepository interface.
type MockpbacRepository struct {
	ctrl     *gomock.Controller
	recorder *MockpbacRepositoryMockRecorder
	isgomock struct{}
}

// MockpbacRepositoryMockRecorder is the mock recorder for MockpbacRepository.
type MockpbacRepositoryMockRecorder struct {
	mock *MockpbacRepository
}

// NewMockpbacRepository creates a new mock instance.
func NewMockpbacRepository(ctrl *gomock.Controller) *MockpbacRepository {
	mock := &MockpbacRepository{ctrl: ctrl}
	mock.recorder = &MockpbacRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpbacRepository) EXPECT() *MockpbacRepositoryMockRecorder {
	return m.recorder
}

// CreateRule mocks base method.
func (m *MockpbacRepository) CreateRule(ctx context.Context, rule domain.PBACRule) (*domain.PBACRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, rule)
	ret0, _ := ret[0].(*domain.PBACRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockpbacRepositoryMockRecorder) CreateRule(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockpbacRepository)(nil).CreateRule), ctx, rule)
}

// DeletePathPermission mocks base method.
func (m *MockpbacRepository) DeletePathPermission(ctx context.Context, projectID snow.ID, pathPrefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePathPermission", ctx, projectID, pathPrefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePathPermission indicates an expected call of DeletePathPermission.
func (mr *MockpbacRepositoryMockRecorder) DeletePathPermission(ctx, projectID, pathPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePathPermission", reflect.TypeOf((*MockpbacRepository)(nil).DeletePathPermission), ctx, projectID, pathPrefix)
}

// DeleteRuleForProject mocks base method.
func (m *MockpbacRepository) DeleteRuleForProject(ctx context.Context, projectID snow.ID, ruleID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRuleForProject", ctx, projectID, ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRuleForProject indicates an expected call of DeleteRuleForProject.
func (mr *MockpbacRepositoryMockRecorder) DeleteRuleForProject(ctx, projectID, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRuleForProject", reflect.TypeOf((*MockpbacRepository)(nil).DeleteRuleForProject), ctx, projectID, ruleID)
}

// ListEffectiveRules mocks base method.
func (m *MockpbacRepository) ListEffectiveRules(ctx context.Context, projectID, userID snow.ID) ([]*domain.PBACRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEffectiveRules", ctx, projectID, userID)
	ret0, _ := ret[0].([]*domain.PBACRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEffectiveRules indicates an expected call of ListEffectiveRules.
func (mr *MockpbacRepositoryMockRecorder) ListEffectiveRules(ctx, projectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEffectiveRules", reflect.TypeOf((*MockpbacRepository)(nil).ListEffectiveRules), ctx, projectID, userID)
}

// ListPathPermissions mocks base method.
func (m *MockpbacRepository) ListPathPermissions(ctx context.Context, projectID snow.ID) ([]*domain.ProjectPathPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPathPermissions", ctx, projectID)
	ret0, _ := ret[0].([]*domain.ProjectPathPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPathPermissions indicates an expected call of ListPathPermissions.
func (mr *MockpbacRepositoryMockRecorder) ListPathPermissions(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPathPermissions", reflect.TypeOf((*MockpbacRepository)(nil).ListPathPermissions), ctx, projectID)
}

// ListRulesByProject mocks base method.
func (m *MockpbacRepository) ListRulesByProject(ctx context.Context, projectID snow.ID) ([]*domain.PBACRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRulesByProject", ctx, projectID)
	ret0, _ := ret[0].([]*domain.PBACRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRulesByProject indicates an expected call of ListRulesByProject.
func (mr *MockpbacRepositoryMockRecorder) ListRulesByProject(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRulesByProject", reflect.TypeOf((*MockpbacRepository)(nil).ListRulesByProject), ctx, projectID)
}

// UpsertPathPermission mocks base method.
func (m *MockpbacRepository) UpsertPathPermission(ctx context.Context, perm domain.ProjectPathPermission) (*domain.ProjectPathPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPathPermission", ctx, perm)
	ret0, _ := ret[0].(*domain.ProjectPathPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPathPermission indicates an expected call of UpsertPathPermission.
func (mr *MockpbacRepositoryMockRecorder) UpsertPathPermission(ctx, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPathPermission", reflect.TypeOf((*MockpbacRepository)(nil).UpsertPathPermission), ctx, perm)
}
