// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/push.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/push.go -destination=internal/grpc/server/push_usecase_mock_test.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	usecase "github.com/nipalab/nipa/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockpushRepository is a mock of pushRepository interface.
type MockpushRepository struct {
	ctrl     *gomock.Controller
	recorder *MockpushRepositoryMockRecorder
	isgomock struct{}
}

// MockpushRepositoryMockRecorder is the mock recorder for MockpushRepository.
type MockpushRepositoryMockRecorder struct {
	mock *MockpushRepository
}

// NewMockpushRepository creates a new mock instance.
func NewMockpushRepository(ctrl *gomock.Controller) *MockpushRepository {
	mock := &MockpushRepository{ctrl: ctrl}
	mock.recorder = &MockpushRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpushRepository) EXPECT() *MockpushRepositoryMockRecorder {
	return m.recorder
}

// ApplyPush mocks base method.
func (m *MockpushRepository) ApplyPush(ctx context.Context, req usecase.ApplyPushRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyPush", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyPush indicates an expected call of ApplyPush.
func (mr *MockpushRepositoryMockRecorder) ApplyPush(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPush", reflect.TypeOf((*MockpushRepository)(nil).ApplyPush), ctx, req)
}
