// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/tag.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/tag.go -destination=internal/grpc/server/tag_usecase_mock_test.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/nipalab/nipa/internal/domain"
	snow "github.com/nipalab/nipa/internal/snow"
	gomock "go.uber.org/mock/gomock"
)

// MocktagRepository is a mock of tagRepository interface.
type MocktagRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktagRepositoryMockRecorder
	isgomock struct{}
}

// MocktagRepositoryMockRecorder is the mock recorder for MocktagRepository.
type MocktagRepositoryMockRecorder struct {
	mock *MocktagRepository
}

// NewMocktagRepository creates a new mock instance.
func NewMocktagRepository(ctrl *gomock.Controller) *MocktagRepository {
	mock := &MocktagRepository{ctrl: ctrl}
	mock.recorder = &MocktagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktagRepository) EXPECT() *MocktagRepositoryMockRecorder {
	return m.recorder
}

// CreateTag mocks base method.
func (m *MocktagRepository) CreateTag(ctx context.Context, tag domain.Tag) (*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, tag)
	ret0, _ := ret[0].(*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MocktagRepositoryMockRecorder) CreateTag(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MocktagRepository)(nil).CreateTag), ctx, tag)
}

// DeleteTag mocks base method.
func (m *MocktagRepository) DeleteTag(ctx context.Context, projectID, tagID snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", ctx, projectID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTag indicates an expected call of DeleteTag.
func (mr *MocktagRepositoryMockRecorder) DeleteTag(ctx, projectID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MocktagRepository)(nil).DeleteTag), ctx, projectID, tagID)
}

// GetTagByName mocks base method.
func (m *MocktagRepository) GetTagByName(ctx context.Context, projectID snow.ID, name string) (*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagByName", ctx, projectID, name)
	ret0, _ := ret[0].(*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagByName indicates an expected call of GetTagByName.
func (mr *MocktagRepositoryMockRecorder) GetTagByName(ctx, projectID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagByName", reflect.TypeOf((*MocktagRepository)(nil).GetTagByName), ctx, projectID, name)
}

// ListTags mocks base method.
func (m *MocktagRepository) ListTags(ctx context.Context, projectID snow.ID, limit int, createdBefore *time.Time, lastID snow.ID) ([]*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx, projectID, limit, createdBefore, lastID)
	ret0, _ := ret[0].([]*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MocktagRepositoryMockRecorder) ListTags(ctx, projectID, limit, createdBefore, lastID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MocktagRepository)(nil).ListTags), ctx, projectID, limit, createdBefore, lastID)
}

// MockhookTagGate is a mock of hookTagGate interface.
type MockhookTagGate struct {
	ctrl     *gomock.Controller
	recorder *MockhookTagGateMockRecorder
	isgomock struct{}
}

// MockhookTagGateMockRecorder is the mock recorder for MockhookTagGate.
type MockhookTagGateMockRecorder struct {
	mock *MockhookTagGate
}

// NewMockhookTagGate creates a new mock instance.
func NewMockhookTagGate(ctrl *gomock.Controller) *MockhookTagGate {
	mock := &MockhookTagGate{ctrl: ctrl}
	mock.recorder = &MockhookTagGateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhookTagGate) EXPECT() *MockhookTagGateMockRecorder {
	return m.recorder
}

// EmitTag mocks base method.
func (m *MockhookTagGate) EmitTag(ctx context.Context, event string, projectID snow.ID, tag *domain.Tag, actor snow.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmitTag", ctx, event, projectID, tag, actor)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmitTag indicates an expected call of EmitTag.
func (mr *MockhookTagGateMockRecorder) EmitTag(ctx, event, projectID, tag, actor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitTag", reflect.TypeOf((*MockhookTagGate)(nil).EmitTag), ctx, event, projectID, tag, actor)
}
